# v3 Annotated Transformer + DailyDialog (resume + chat)

Same paper Transformer as v2, plus:

- Native PyTorch checkpoint dicts (`last.pt`, `epoch_N.pt`, `step_N.pt`, `final.pt`)
- Resume after Stop / interrupt
- Greedy one-turn chat (`chat_loop`)
- **All v2 visualizations** (EDA, training curves, quality, weights)

Dataset (Hugging Face): `roskoN/dailydialog` — **not** a pretrained chat model.

## Kaggle

1. **Accelerator: GPU** (T4)
2. **Internet: ON** (dataset + spaCy)
3. Run All. On Kaggle, `RUN_MODE` defaults to **`full`** (all DailyDialog, N=6, 8 epochs).
4. Outputs save under `/kaggle/working` (`dailydialog_full_final.pt`, `vocab.json`).

If packages are missing, run once:

```
%pip install -q datasets altair tokenizers GPUtil pandas
!python -m spacy download en_core_web_sm
```

Do **not** `pip install torch` from `requirements.txt` on Kaggle (Kaggle already has CUDA torch).

Kaggle **Save Version** is a batch run: interactive `input()` chat is skipped; a **demo chat** still prints. In an interactive session, run the last cell for live chat.

Local laptop: kernel `transformer-env`, `RUN_MODE=local` (default off Kaggle).

## Time estimates (your GTX 1650, from the 3000-pair run)

- **Local now (38000 pairs ≈ half of train, N=2, 8 epochs):** about **3–5 hours** on GTX 1650. Keep the laptop awake.
- **All DailyDialog pairs, still N=2, 8 epochs:** about **6–10 hours**
- **Paper full (`RUN_MODE=full`: all data, N=6, 8 epochs, batch 32):** about **1 day** if it fits in 4 GB. On this laptop it often **runs out of GPU memory**. Use **Kaggle T4** for that run (T4 16 GB: often **6–12 hours**).

## Resume (automatic)

Training writes (new prefix so the old 15k/1-epoch files are not reused):
- `dailydialog_local38k8e_last.pt` — always the newest; **re-run the notebook to continue**
- `dailydialog_local38k8e_step_N.pt` — every 2500 steps
- `dailydialog_local38k8e_epoch_N.pt` — end of each epoch
- `dailydialog_local38k8e_final.pt` — only when training **finished**
- `vocab_local38k.json` — vocab for this 38k run (do not reuse old `vocab.json`)

If you Stop / crash: keep `last.pt`, Run All again. It resumes. Delete `final.pt` + `last.pt` only when you want a **new** train from scratch.

In [1]:
import os

# Local laptop run (not Kaggle full).
# Local laptop: 38000 train pairs (half of DailyDialog train), 3500 valid, 8 epochs, N=2.
# Expect about 3-5 hours on GTX 1650. Keep the machine awake.
# New checkpoint prefix dailydialog_local38k8e_ so the old 15k/1-epoch run is not loaded.
os.environ["RUN_MODE"] = "local"
print("RUN_MODE =", os.environ["RUN_MODE"])

# Hugging Face token — used to download DailyDialog. Keep this notebook private.
os.environ["HF_TOKEN"] = "hf_YOUR_HUGGINGFACE_TOKEN"
os.environ["HUGGING_FACE_HUB_TOKEN"] = os.environ["HF_TOKEN"]
try:
    from huggingface_hub import login
    login(token=os.environ["HF_TOKEN"], add_to_git_credential=False)
    print("Hugging Face login: OK")
except Exception as err:
    print("Hugging Face login skipped:", err)

import torch
print(torch.cuda.is_available(), torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    print(torch.cuda.get_device_name(i))

RUN_MODE = local

/home/creator/miniconda3/envs/transformer-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Hugging Face login: OK
True 1
NVIDIA GeForce GTX 1650

In [2]:
import re
import os
import random
from os.path import exists
import torch
import torch.nn as nn
from torch.nn.functional import log_softmax, pad
import math
import copy
import time
from torch.optim.lr_scheduler import LambdaLR
import pandas as pd

def setup_human_numbers():
    def _fmt(v):
        try:
            x = float(v)
        except Exception:
            return str(v)
        if abs(x) >= 1:
            s = "%.4f" % x
        else:
            s = "%.8f" % x
        return s.rstrip("0").rstrip(".")
    pd.set_option("display.float_format", _fmt)
    pd.set_option("display.max_colwidth", 100)
    try:
        import numpy as np
        np.set_printoptions(suppress=True, precision=4)
    except Exception:
        pass
    print("Number display: normal decimals (not 1.1e-05)")

setup_human_numbers()
import altair as alt
from torch.utils.data import DataLoader, Dataset
from datasets import load_dataset
import spacy
import GPUtil
import warnings

warnings.filterwarnings("ignore")
RUN_EXAMPLES = True


def running_on_kaggle():
    return bool(
        os.environ.get("KAGGLE_KERNEL_RUN_TYPE")
        or os.path.isdir("/kaggle/working")
    )


def default_run_mode():
    env = os.environ.get("RUN_MODE")
    if env:
        return env
    # Kaggle T4: use the full DailyDialog / paper-size run unless overridden
    if running_on_kaggle():
        return "full"
    return "local"


# "local" = laptop one-go; "full" = Colab/Kaggle
RUN_MODE = default_run_mode()
if running_on_kaggle() and os.path.isdir("/kaggle/working"):
    os.chdir("/kaggle/working")
    print("Kaggle detected. cwd=/kaggle/working  RUN_MODE=%s" % RUN_MODE)

# Some convenience helper functions used throughout the notebook


def is_interactive_notebook():
    return __name__ == "__main__"


def show_example(fn, args=[]):
    if __name__ == "__main__" and RUN_EXAMPLES:
        return fn(*args)


def execute_example(fn, args=[]):
    if __name__ == "__main__" and RUN_EXAMPLES:
        fn(*args)

Number display: normal decimals (not 1.1e-05)

# Part 1: Model Architecture

In [3]:
class DummyOptimizer(torch.optim.Optimizer):
    def __init__(self):
        self.param_groups = [{"lr": 0}]
        None

    def step(self):
        None

    def zero_grad(self, set_to_none=False):
        None


class DummyScheduler:
    def step(self):
        None

class EncoderDecoder(nn.Module):
    """
    A standard Encoder-Decoder architecture. Base for this and many
    other models.
    """

    def __init__(self, encoder, decoder, src_embed, tgt_embed, generator):
        super(EncoderDecoder, self).__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.src_embed = src_embed
        self.tgt_embed = tgt_embed
        self.generator = generator

    def forward(self, src, tgt, src_mask, tgt_mask):
        "Take in and process masked src and target sequences."
        return self.decode(self.encode(src, src_mask), src_mask, tgt, tgt_mask)

    def encode(self, src, src_mask):
        return self.encoder(self.src_embed(src), src_mask)

    def decode(self, memory, src_mask, tgt, tgt_mask):
        return self.decoder(self.tgt_embed(tgt), memory, src_mask, tgt_mask)

class Generator(nn.Module):
    "Define standard linear + softmax generation step."

    def __init__(self, d_model, vocab):
        super(Generator, self).__init__()
        self.proj = nn.Linear(d_model, vocab)

    def forward(self, x):
        return log_softmax(self.proj(x), dim=-1)

def clones(module, N):
    "Produce N identical layers."
    return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])

class Encoder(nn.Module):
    "Core encoder is a stack of N layers"

    def __init__(self, layer, N):
        super(Encoder, self).__init__()
        self.layers = clones(layer, N)
        self.norm = LayerNorm(layer.size)

    def forward(self, x, mask):
        "Pass the input (and mask) through each layer in turn."
        for layer in self.layers:
            x = layer(x, mask)
        return self.norm(x)

class LayerNorm(nn.Module):
    "Construct a layernorm module (See citation for details)."

    def __init__(self, features, eps=1e-6):
        super(LayerNorm, self).__init__()
        self.a_2 = nn.Parameter(torch.ones(features))
        self.b_2 = nn.Parameter(torch.zeros(features))
        self.eps = eps

    def forward(self, x):
        mean = x.mean(-1, keepdim=True)
        std = x.std(-1, keepdim=True)
        return self.a_2 * (x - mean) / (std + self.eps) + self.b_2

class SublayerConnection(nn.Module):
    """
    A residual connection followed by a layer norm.
    Note for code simplicity the norm is first as opposed to last.
    """

    def __init__(self, size, dropout):
        super(SublayerConnection, self).__init__()
        self.norm = LayerNorm(size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, sublayer):
        "Apply residual connection to any sublayer with the same size."
        return x + self.dropout(sublayer(self.norm(x)))



class EncoderLayer(nn.Module):
    "Encoder is made up of self-attn and feed forward (defined below)"

    def __init__(self, size, self_attn, feed_forward, dropout):
        super(EncoderLayer, self).__init__()
        self.self_attn = self_attn
        self.feed_forward = feed_forward
        self.sublayer = clones(SublayerConnection(size, dropout), 2)
        self.size = size

    def forward(self, x, mask):
        "Follow Figure 1 (left) for connections."
        x = self.sublayer[0](x, lambda x: self.self_attn(x, x, x, mask))
        return self.sublayer[1](x, self.feed_forward)

class Decoder(nn.Module):
    "Generic N layer decoder with masking."

    def __init__(self, layer, N):
        super(Decoder, self).__init__()
        self.layers = clones(layer, N)
        self.norm = LayerNorm(layer.size)

    def forward(self, x, memory, src_mask, tgt_mask):
        for layer in self.layers:
            x = layer(x, memory, src_mask, tgt_mask)
        return self.norm(x)

class DecoderLayer(nn.Module):
    "Decoder is made of self-attn, src-attn, and feed forward (defined below)"

    def __init__(self, size, self_attn, src_attn, feed_forward, dropout):
        super(DecoderLayer, self).__init__()
        self.size = size
        self.self_attn = self_attn
        self.src_attn = src_attn
        self.feed_forward = feed_forward
        self.sublayer = clones(SublayerConnection(size, dropout), 3)

    def forward(self, x, memory, src_mask, tgt_mask):
        "Follow Figure 1 (right) for connections."
        m = memory
        x = self.sublayer[0](x, lambda x: self.self_attn(x, x, x, tgt_mask))
        x = self.sublayer[1](x, lambda x: self.src_attn(x, m, m, src_mask))
        return self.sublayer[2](x, self.feed_forward)

def subsequent_mask(size):
    "Mask out subsequent positions."
    attn_shape = (1, size, size)
    subsequent_mask = torch.triu(torch.ones(attn_shape), diagonal=1).type(
        torch.uint8
    )
    return subsequent_mask == 0

def example_mask():
    LS_data = pd.concat(
        [
            pd.DataFrame(
                {
                    "Subsequent Mask": subsequent_mask(20)[0][x, y].flatten(),
                    "Window": y,
                    "Masking": x,
                }
            )
            for y in range(20)
            for x in range(20)
        ]
    )

    return (
        alt.Chart(LS_data)
        .mark_rect()
        .properties(height=250, width=250)
        .encode(
            alt.X("Window:O"),
            alt.Y("Masking:O"),
            alt.Color("Subsequent Mask:Q", scale=alt.Scale(scheme="viridis")),
        )
        .interactive()
    )


show_example(example_mask)

def attention(query, key, value, mask=None, dropout=None):
    "Compute 'Scaled Dot Product Attention'"
    d_k = query.size(-1)
    scores = torch.matmul(query, key.transpose(-2, -1)) / math.sqrt(d_k)
    if mask is not None:
        scores = scores.masked_fill(mask == 0, -1e9)
    p_attn = scores.softmax(dim=-1)
    if dropout is not None:
        p_attn = dropout(p_attn)
    return torch.matmul(p_attn, value), p_attn

class MultiHeadedAttention(nn.Module):
    def __init__(self, h, d_model, dropout=0.1):
        "Take in model size and number of heads."
        super(MultiHeadedAttention, self).__init__()
        assert d_model % h == 0
        # We assume d_v always equals d_k
        self.d_k = d_model // h
        self.h = h
        self.linears = clones(nn.Linear(d_model, d_model), 4)
        self.attn = None
        self.dropout = nn.Dropout(p=dropout)

    def forward(self, query, key, value, mask=None):
        "Implements Figure 2"
        if mask is not None:
            # Same mask applied to all h heads.
            mask = mask.unsqueeze(1)
        nbatches = query.size(0)

        # 1) Do all the linear projections in batch from d_model => h x d_k
        query, key, value = [
            lin(x).view(nbatches, -1, self.h, self.d_k).transpose(1, 2)
            for lin, x in zip(self.linears, (query, key, value))
        ]

        # 2) Apply attention on all the projected vectors in batch.
        x, self.attn = attention(
            query, key, value, mask=mask, dropout=self.dropout
        )

        # 3) "Concat" using a view and apply a final linear.
        x = (
            x.transpose(1, 2)
            .contiguous()
            .view(nbatches, -1, self.h * self.d_k)
        )
        del query
        del key
        del value
        return self.linears[-1](x)

class PositionwiseFeedForward(nn.Module):
    "Implements FFN equation."

    def __init__(self, d_model, d_ff, dropout=0.1):
        super(PositionwiseFeedForward, self).__init__()
        self.w_1 = nn.Linear(d_model, d_ff)
        self.w_2 = nn.Linear(d_ff, d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        return self.w_2(self.dropout(self.w_1(x).relu()))

class Embeddings(nn.Module):
    def __init__(self, d_model, vocab):
        super(Embeddings, self).__init__()
        self.lut = nn.Embedding(vocab, d_model)
        self.d_model = d_model

    def forward(self, x):
        return self.lut(x) * math.sqrt(self.d_model)

class PositionalEncoding(nn.Module):
    "Implement the PE function."

    def __init__(self, d_model, dropout, max_len=5000):
        super(PositionalEncoding, self).__init__()
        self.dropout = nn.Dropout(p=dropout)

        # Compute the positional encodings once in log space.
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, d_model, 2) * -(math.log(10000.0) / d_model)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer("pe", pe)

    def forward(self, x):
        x = x + self.pe[:, : x.size(1)].requires_grad_(False)
        return self.dropout(x)

def example_positional():
    pe = PositionalEncoding(20, 0)
    y = pe.forward(torch.zeros(1, 100, 20))

    data = pd.concat(
        [
            pd.DataFrame(
                {
                    "embedding": y[0, :, dim],
                    "dimension": dim,
                    "position": list(range(100)),
                }
            )
            for dim in [4, 5, 6, 7]
        ]
    )

    return (
        alt.Chart(data)
        .mark_line()
        .properties(width=800)
        .encode(x="position", y="embedding", color="dimension:N")
        .interactive()
    )


show_example(example_positional)

def make_model(
    src_vocab, tgt_vocab, N=6, d_model=512, d_ff=2048, h=8, dropout=0.1
):
    "Helper: Construct a model from hyperparameters."
    c = copy.deepcopy
    attn = MultiHeadedAttention(h, d_model)
    ff = PositionwiseFeedForward(d_model, d_ff, dropout)
    position = PositionalEncoding(d_model, dropout)
    model = EncoderDecoder(
        Encoder(EncoderLayer(d_model, c(attn), c(ff), dropout), N),
        Decoder(DecoderLayer(d_model, c(attn), c(attn), c(ff), dropout), N),
        nn.Sequential(Embeddings(d_model, src_vocab), c(position)),
        nn.Sequential(Embeddings(d_model, tgt_vocab), c(position)),
        Generator(d_model, tgt_vocab),
    )

    # This was important from their code.
    # Initialize parameters with Glorot / fan_avg.
    for p in model.parameters():
        if p.dim() > 1:
            nn.init.xavier_uniform_(p)
    return model

def inference_test():
    test_model = make_model(11, 11, 2)
    test_model.eval()
    src = torch.LongTensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
    src_mask = torch.ones(1, 1, 10)

    memory = test_model.encode(src, src_mask)
    ys = torch.zeros(1, 1).type_as(src)

    for i in range(9):
        out = test_model.decode(
            memory, src_mask, ys, subsequent_mask(ys.size(1)).type_as(src.data)
        )
        prob = test_model.generator(out[:, -1])
        _, next_word = torch.max(prob, dim=1)
        next_word = next_word.data[0]
        ys = torch.cat(
            [ys, torch.empty(1, 1).type_as(src.data).fill_(next_word)], dim=1
        )

    print("Example Untrained Model Prediction:", ys)


def run_tests():
    for _ in range(10):
        inference_test()


show_example(run_tests)

Example Untrained Model Prediction: tensor([[0, 5, 5, 5, 5, 5, 5, 5, 5, 5]])
Example Untrained Model Prediction: tensor([[0, 5, 6, 6, 6, 6, 6, 6, 6, 6]])
Example Untrained Model Prediction: tensor([[0, 2, 2, 2, 2, 2, 2, 2, 2, 2]])
Example Untrained Model Prediction: tensor([[0, 3, 6, 0, 3, 2, 3, 3, 3, 3]])
Example Untrained Model Prediction: tensor([[0, 4, 6, 7, 8, 8, 8, 8, 8, 8]])
Example Untrained Model Prediction: tensor([[0, 9, 9, 9, 9, 9, 9, 9, 9, 9]])
Example Untrained Model Prediction: tensor([[0, 7, 9, 7, 9, 7, 9, 7, 9, 7]])
Example Untrained Model Prediction: tensor([[0, 7, 5, 1, 7, 1, 7, 1, 7, 1]])
Example Untrained Model Prediction: tensor([[ 0,  8,  4, 10,  4, 10,  9,  3,  5,  9]])
Example Untrained Model Prediction: tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Part 2: Model Training

In [4]:
"""# Part 2: Model Training"""

class Batch:
    """Object for holding a batch of data with mask during training."""

    def __init__(self, src, tgt=None, pad=2):  # 2 = <blank>
        self.src = src
        self.src_mask = (src != pad).unsqueeze(-2)
        if tgt is not None:
            self.tgt = tgt[:, :-1]
            self.tgt_y = tgt[:, 1:]
            self.tgt_mask = self.make_std_mask(self.tgt, pad)
            self.ntokens = (self.tgt_y != pad).data.sum()

    @staticmethod
    def make_std_mask(tgt, pad):
        "Create a mask to hide padding and future words."
        tgt_mask = (tgt != pad).unsqueeze(-2)
        tgt_mask = tgt_mask & subsequent_mask(tgt.size(-1)).type_as(
            tgt_mask.data
        )
        return tgt_mask

class TrainState:
    """Track number of steps, examples, and tokens processed"""

    def __init__(self):
        self.step = 0
        self.accum_step = 0
        self.samples = 0
        self.tokens = 0

# Commented out IPython magic to ensure Python compatibility.
def run_epoch(
    data_iter,
    model,
    loss_compute,
    optimizer,
    scheduler,
    mode="train",
    accum_iter=1,
    train_state=TrainState(),
    on_step=None,
    history=None,
    epoch=0,
):
    """Train a single epoch.

    Training math is unchanged from the paper notebook.
    Optional `history` only records loss/lr for charts.
    Optional `on_step` is v3 checkpointing (every N steps).
    """
    start = time.time()
    total_tokens = 0
    total_loss = 0
    tokens = 0
    n_accum = 0
    for i, batch in enumerate(data_iter):
        out = model.forward(
            batch.src, batch.tgt, batch.src_mask, batch.tgt_mask
        )
        loss, loss_node = loss_compute(out, batch.tgt_y, batch.ntokens)
        if mode == "train" or mode == "train+log":
            loss_node.backward()
            train_state.step += 1
            train_state.samples += batch.src.shape[0]
            train_state.tokens += batch.ntokens
            if i % accum_iter == 0:
                optimizer.step()
                optimizer.zero_grad(set_to_none=True)
                n_accum += 1
                train_state.accum_step += 1
            scheduler.step()
            if on_step is not None:
                on_step(i, train_state)

        total_loss += loss
        total_tokens += batch.ntokens
        tokens += batch.ntokens
        if i % 40 == 1 and (mode == "train" or mode == "train+log"):
            lr = optimizer.param_groups[0]["lr"]
            elapsed = time.time() - start
            step_loss = float(loss / batch.ntokens)
            tok_s = float(tokens / elapsed) if elapsed > 0 else 0.0
            print(
                (
                    "Step %d | Loss %.2f "
                    + "| Speed %.0f tokens/sec | Learning rate %s"
                )
                % (i, step_loss, tok_s, ("%.8f" % float(lr)).rstrip("0").rstrip("."))
            )
            if history is not None:
                history.append(
                    {
                        "epoch": epoch,
                        "batch": i,
                        "global_step": train_state.step,
                        "loss": step_loss,
                        "tokens_per_sec": tok_s,
                        "lr": float(lr),
                    }
                )
            start = time.time()
            tokens = 0
        del loss
        del loss_node
    mean_loss = total_loss / total_tokens
    return mean_loss, train_state

def rate(step, model_size, factor, warmup):
    """
    we have to default the step to 1 for LambdaLR function
    to avoid zero raising to negative power.
    """
    if step == 0:
        step = 1
    return factor * (
        model_size ** (-0.5) * min(step ** (-0.5), step * warmup ** (-1.5))
    )

def example_learning_schedule():
    opts = [
        [512, 1, 4000],  # example 1
        [512, 1, 8000],  # example 2
        [256, 1, 4000],  # example 3
    ]

    dummy_model = torch.nn.Linear(1, 1)
    learning_rates = []

    # we have 3 examples in opts list.
    for idx, example in enumerate(opts):
        # run 20000 epoch for each example
        optimizer = torch.optim.Adam(
            dummy_model.parameters(), lr=1, betas=(0.9, 0.98), eps=1e-9
        )
        lr_scheduler = LambdaLR(
            optimizer=optimizer, lr_lambda=lambda step: rate(step, *example)
        )
        tmp = []
        # take 20K dummy training steps, save the learning rate at each step
        for step in range(20000):
            tmp.append(optimizer.param_groups[0]["lr"])
            optimizer.step()
            lr_scheduler.step()
        learning_rates.append(tmp)

    learning_rates = torch.tensor(learning_rates)

    # Enable altair to handle more than 5000 rows
    alt.data_transformers.disable_max_rows()

    opts_data = pd.concat(
        [
            pd.DataFrame(
                {
                    "Learning Rate": learning_rates[warmup_idx, :],
                    "model_size_warmup": ["512:4000", "512:8000", "256:4000"][
                        warmup_idx
                    ],
                    "step": range(20000),
                }
            )
            for warmup_idx in [0, 1, 2]
        ]
    )

    return (
        alt.Chart(opts_data)
        .mark_line()
        .properties(width=600)
        .encode(x="step", y="Learning Rate", color="model_size_warmup:N")
        .interactive()
    )


show_example(example_learning_schedule)

class LabelSmoothing(nn.Module):
    "Implement label smoothing."

    def __init__(self, size, padding_idx, smoothing=0.0):
        super(LabelSmoothing, self).__init__()
        self.criterion = nn.KLDivLoss(reduction="sum")
        self.padding_idx = padding_idx
        self.confidence = 1.0 - smoothing
        self.smoothing = smoothing
        self.size = size
        self.true_dist = None

    def forward(self, x, target):
        assert x.size(1) == self.size
        true_dist = x.data.clone()
        true_dist.fill_(self.smoothing / (self.size - 2))
        true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
        true_dist[:, self.padding_idx] = 0
        mask = torch.nonzero(target.data == self.padding_idx)
        if mask.dim() > 0:
            true_dist.index_fill_(0, mask.squeeze(), 0.0)
        self.true_dist = true_dist
        return self.criterion(x, true_dist.clone().detach())

# Example of label smoothing.


def example_label_smoothing():
    crit = LabelSmoothing(5, 0, 0.4)
    predict = torch.FloatTensor(
        [
            [0, 0.2, 0.7, 0.1, 0],
            [0, 0.2, 0.7, 0.1, 0],
            [0, 0.2, 0.7, 0.1, 0],
            [0, 0.2, 0.7, 0.1, 0],
            [0, 0.2, 0.7, 0.1, 0],
        ]
    )
    crit(x=predict.log(), target=torch.LongTensor([2, 1, 0, 3, 3]))
    LS_data = pd.concat(
        [
            pd.DataFrame(
                {
                    "target distribution": crit.true_dist[x, y].flatten(),
                    "columns": y,
                    "rows": x,
                }
            )
            for y in range(5)
            for x in range(5)
        ]
    )

    return (
        alt.Chart(LS_data)
        .mark_rect(color="Blue", opacity=1)
        .properties(height=200, width=200)
        .encode(
            alt.X("columns:O", title=None),
            alt.Y("rows:O", title=None),
            alt.Color(
                "target distribution:Q", scale=alt.Scale(scheme="viridis")
            ),
        )
        .interactive()
    )


show_example(example_label_smoothing)

def loss(x, crit):
    d = x + 3 * 1
    predict = torch.FloatTensor([[0, x / d, 1 / d, 1 / d, 1 / d]])
    return crit(predict.log(), torch.LongTensor([1])).data


def penalization_visualization():
    crit = LabelSmoothing(5, 0, 0.1)
    loss_data = pd.DataFrame(
        {
            "Loss": [loss(x, crit) for x in range(1, 100)],
            "Steps": list(range(99)),
        }
    ).astype("float")

    return (
        alt.Chart(loss_data)
        .mark_line()
        .properties(width=350)
        .encode(
            x="Steps",
            y="Loss",
        )
        .interactive()
    )


show_example(penalization_visualization)

def data_gen(V, batch_size, nbatches):
    "Generate random data for a src-tgt copy task."
    for i in range(nbatches):
        data = torch.randint(1, V, size=(batch_size, 10))
        data[:, 0] = 1
        src = data.requires_grad_(False).clone().detach()
        tgt = data.requires_grad_(False).clone().detach()
        yield Batch(src, tgt, 0)

class SimpleLossCompute:
    "A simple loss compute and train function."

    def __init__(self, generator, criterion):
        self.generator = generator
        self.criterion = criterion

    def __call__(self, x, y, norm):
        x = self.generator(x)
        sloss = (
            self.criterion(
                x.contiguous().view(-1, x.size(-1)), y.contiguous().view(-1)
            )
            / norm
        )
        return sloss.data * norm, sloss

def greedy_decode(model, src, src_mask, max_len, start_symbol):
    memory = model.encode(src, src_mask)
    ys = torch.zeros(1, 1).fill_(start_symbol).type_as(src.data)
    for i in range(max_len - 1):
        out = model.decode(
            memory, src_mask, ys, subsequent_mask(ys.size(1)).type_as(src.data)
        )
        prob = model.generator(out[:, -1])
        _, next_word = torch.max(prob, dim=1)
        next_word = next_word.data[0]
        ys = torch.cat(
            [ys, torch.zeros(1, 1).type_as(src.data).fill_(next_word)], dim=1
        )
    return ys

# Train the simple copy task.


def example_simple_model():
    V = 11
    criterion = LabelSmoothing(size=V, padding_idx=0, smoothing=0.0)
    model = make_model(V, V, N=2)

    optimizer = torch.optim.Adam(
        model.parameters(), lr=0.5, betas=(0.9, 0.98), eps=1e-9
    )
    lr_scheduler = LambdaLR(
        optimizer=optimizer,
        lr_lambda=lambda step: rate(
            step, model_size=model.src_embed[0].d_model, factor=1.0, warmup=400
        ),
    )

    batch_size = 80
    for epoch in range(20):
        model.train()
        run_epoch(
            data_gen(V, batch_size, 20),
            model,
            SimpleLossCompute(model.generator, criterion),
            optimizer,
            lr_scheduler,
            mode="train",
        )
        model.eval()
        run_epoch(
            data_gen(V, batch_size, 5),
            model,
            SimpleLossCompute(model.generator, criterion),
            DummyOptimizer(),
            DummyScheduler(),
            mode="eval",
        )[0]

    model.eval()
    src = torch.LongTensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
    max_len = src.shape[1]
    src_mask = torch.ones(1, 1, max_len)
    print(greedy_decode(model, src, src_mask, max_len=max_len, start_symbol=0))


# execute_example(example_simple_model)

# Part 3: DailyDialog + resume + chat

Same data and paper model as v2. v3 extras: checkpoint resume and chat.

**Visualization (same as v2)**
- EDA: repeated lines, example pairs, length charts, correlation matrix
- Training: loss / LR / throughput / epoch progress (also stored in checkpoints)
- Quality: accuracy vs chance, expected vs predicted, overlap, diffs
- Weights: embeddings / attention / FFN counts, layer L2, multi-correlation

**Checkpoints** (prefix `dailydialog_full_` on Kaggle, `dailydialog_local38k8e_` on a laptop)

- `...last.pt` — resume here
- `...epoch_N.pt` / `...step_N.pt`
- `...final.pt` — finished model

Chat is greedy decode of the 2017 encoder–decoder, not ChatGPT.

In [5]:
## Part 3: DailyDialog training with resume + chat
# Original Annotated Transformer used Multi30k (de->en).
# v3 uses Hugging Face dataset `roskoN/dailydialog` as next-utterance pairs.
# Checkpoints use native torch.save dicts. Chat uses greedy_decode.
# Visualization matches v2 (EDA, training curves, quality, weights).
# Encoder / decoder / attention are unchanged from the paper.

from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.trainers import WordLevelTrainer
from tokenizers.pre_tokenizers import WhitespaceSplit


def get_run_config():
    mode = str(RUN_MODE).lower()
    if mode not in ("local", "full"):
        raise ValueError("RUN_MODE must be 'local' or 'full', got %r" % mode)
    if mode == "local":
        # Half of DailyDialog train (~76k pairs) + 8 epochs. N=2 fits a 4 GB 1650.
        # New prefix/vocab so the old 15k / 1-epoch run is not reused by accident.
        return {
            "mode": "local",
            "train_pairs": 76052,
            "valid_pairs": 7069,
            "batch_size": 8,
            "num_epochs": 8,
            "accum_iter": 4,
            "base_lr": 1.0,
            "max_padding": 48,
            "warmup": 2000,
            "N": 2,
            "d_model": 512,
            "file_prefix": "dailydialog_local38k8e_",
            "vocab_path": "vocab_local38k.json",
            "save_every_steps": 2500,
        }
    return {
        "mode": "full",
        "train_pairs": None,
        "valid_pairs": None,
        "batch_size": 32,
        "num_epochs": 8,
        "accum_iter": 10,
        "base_lr": 1.0,
        "max_padding": 72,
        "warmup": 3000,
        "N": 6,
        "d_model": 512,
        "file_prefix": "dailydialog_full_",
        "vocab_path": "vocab.json",
        "save_every_steps": 2000,
    }


def load_tokenizer_en():
    try:
        spacy_en = spacy.load("en_core_web_sm")
    except IOError:
        os.system("python -m spacy download en_core_web_sm")
        spacy_en = spacy.load("en_core_web_sm")
    return spacy_en


def tokenize(text, tokenizer):
    return [tok.text for tok in tokenizer.tokenizer(text)]


def normalize_text(text):
    text = re.sub(r"\s+'\s+", "'", text)
    text = re.sub(r"\s+([.,!?])", r"\1", text)
    text = text.replace("。", ".")
    return text.strip()


def build_dailydialog_pairs(split="train", max_pairs=None):
    raw = load_dataset(
        "roskoN/dailydialog",
        revision="refs/convert/parquet",
        token=os.environ.get("HF_TOKEN"),
    )
    pairs = []
    for entry in raw[split]:
        utts = [normalize_text(u) for u in entry["utterances"]]
        for i in range(len(utts) - 1):
            pairs.append((utts[i], utts[i + 1]))
            if max_pairs is not None and len(pairs) >= max_pairs:
                return pairs
    return pairs


def yield_tokens(pairs, tokenizer):
    for src, tgt in pairs:
        yield tokenize(src, tokenizer)
        yield tokenize(tgt, tokenizer)


def build_vocabulary(spacy_en, pairs):
    print("Building shared English Vocabulary ...")
    tok = Tokenizer(WordLevel(unk_token="<unk>"))
    tok.pre_tokenizer = WhitespaceSplit()
    trainer = WordLevelTrainer(
        min_frequency=2,
        special_tokens=["<s>", "</s>", "<blank>", "<unk>"],
    )

    def text_iterator():
        for tokens in yield_tokens(pairs, spacy_en):
            yield " ".join(tokens)

    tok.train_from_iterator(text_iterator(), trainer=trainer)
    return tok


def load_vocab(spacy_en, pairs, vocab_path="vocab.json"):
    if not exists(vocab_path):
        vocab = build_vocabulary(spacy_en, pairs)
        vocab.save(vocab_path)
    else:
        vocab = Tokenizer.from_file(vocab_path)
    print("Finished.\nVocabulary size:")
    print(vocab.get_vocab_size())
    return vocab


def collate_batch(
    batch,
    pipeline,
    vocab,
    device,
    max_padding=128,
):
    bs_id = torch.tensor([vocab.token_to_id("<s>")], device=device)
    eos_id = torch.tensor([vocab.token_to_id("</s>")], device=device)
    pad_id = vocab.token_to_id("<blank>")
    max_body = max(1, max_padding - 2)
    src_list, tgt_list = [], []
    for (_src, _tgt) in batch:
        src_ids = vocab.encode(" ".join(pipeline(_src))).ids[:max_body]
        tgt_ids = vocab.encode(" ".join(pipeline(_tgt))).ids[:max_body]

        processed_src = torch.cat(
            [
                bs_id,
                torch.tensor(src_ids, dtype=torch.int64, device=device),
                eos_id,
            ],
            0,
        )
        processed_tgt = torch.cat(
            [
                bs_id,
                torch.tensor(tgt_ids, dtype=torch.int64, device=device),
                eos_id,
            ],
            0,
        )
        src_list.append(
            pad(
                processed_src,
                (0, max_padding - len(processed_src)),
                value=pad_id,
            )
        )
        tgt_list.append(
            pad(
                processed_tgt,
                (0, max_padding - len(processed_tgt)),
                value=pad_id,
            )
        )
    src = torch.stack(src_list)
    tgt = torch.stack(tgt_list)
    return (src, tgt)


def create_dataloaders(
    device,
    vocab,
    spacy_en,
    train_pairs,
    valid_pairs,
    batch_size=32,
    max_padding=128,
):
    def pipeline(text):
        return tokenize(text, spacy_en)

    def collate_fn(batch):
        return collate_batch(
            batch,
            pipeline,
            vocab,
            device,
            max_padding=max_padding,
        )

    train_dataloader = DataLoader(
        train_pairs,
        batch_size=batch_size,
        shuffle=True,
        collate_fn=collate_fn,
    )
    valid_dataloader = DataLoader(
        valid_pairs,
        batch_size=batch_size,
        shuffle=False,
        collate_fn=collate_fn,
    )
    return train_dataloader, valid_dataloader


# ---------------------------------------------------------------------------
# Visualization (charts only — model math stays the 2017 paper Transformer)
# Two data views: (1) repeated conversation text  (2) how sequences look
# After training: loss curves, epoch progress, accuracy vs expected, weights
# ---------------------------------------------------------------------------

VIZ_STATE = {
    "history": [],
    "epoch_rows": [],
    "did_train": False,
}


def display_viz(obj):
    """Show a chart/table in Jupyter; print a text fallback in a script."""
    try:
        from IPython.display import display

        display(obj)
    except Exception:
        if isinstance(obj, pd.DataFrame):
            print(obj.to_string(index=False))
        else:
            print(obj)


def display_note(text):
    try:
        from IPython.display import display, Markdown

        display(Markdown(text))
    except Exception:
        print(text)


def _unwrap_model(model):
    return model.module if hasattr(model, "module") else model


def epoch_progress_bar(epoch, num_epochs, width=28):
    done = int(width * (epoch + 1) / max(num_epochs, 1))
    bar = "█" * done + "░" * (width - done)
    return f"[{bar}]  epoch {epoch + 1}/{num_epochs} complete"


def pair_stats_frame(pairs, tokenizer, vocab=None, max_pairs=None):
    """Numeric view of how each utterance looks as a sequence."""
    rows = []
    sample = pairs if max_pairs is None else pairs[:max_pairs]
    for src, tgt in sample:
        src_toks = tokenize(src, tokenizer)
        tgt_toks = tokenize(tgt, tokenizer)
        src_ids = vocab.encode(" ".join(src_toks)).ids if vocab is not None else src_toks
        tgt_ids = vocab.encode(" ".join(tgt_toks)).ids if vocab is not None else tgt_toks
        rows.append(
            {
                "src_chars": len(src),
                "tgt_chars": len(tgt),
                "src_words": len(src_toks),
                "tgt_words": len(tgt_toks),
                "src_tokens": len(src_ids),
                "tgt_tokens": len(tgt_ids),
            }
        )
    return pd.DataFrame(rows)


def show_dataset_views(train_pairs, valid_pairs, tokenizer, vocab=None, n_examples=10):
    """Two data views only: repeated chat text, and how those sequences look."""
    alt.data_transformers.disable_max_rows()
    display_note(
        "### Data view 1 — what the conversations look like\n"
        "DailyDialog is everyday chat. Each **row** is one training example: "
        "previous utterance (`src`) → next utterance (`tgt`). "
        "The same short lines (hello, thanks, okay) often **repeat**."
    )
    from collections import Counter

    src_counts = Counter(src for src, _ in train_pairs)
    repeated = [
        {"times": n, "utterance": u}
        for u, n in src_counts.most_common(12)
        if n > 1
    ]
    if not repeated:
        repeated = [{"times": n, "utterance": u} for u, n in src_counts.most_common(8)]
    repeat_df = pd.DataFrame(repeated)
    display_viz(repeat_df)

    examples = []
    for i, (src, tgt) in enumerate(train_pairs[:n_examples]):
        examples.append(
            {
                "pair": i,
                "previous (src)": src,
                "next reply (tgt)": tgt,
            }
        )
    example_df = pd.DataFrame(examples)
    display_note(
        "### Data view 2 — example pairs the model actually trains on\n"
        "This is the seq2seq layout from *Attention Is All You Need*: "
        "encode `src`, decode `tgt`. No extra chat template."
    )
    display_viz(example_df)

    stats = pair_stats_frame(
        train_pairs, tokenizer, vocab=vocab, max_pairs=min(len(train_pairs), 15000)
    )
    display_note(
        "### How those pairs look as sequences\n"
        f"Train pairs: **{len(train_pairs)}** · valid pairs: **{len(valid_pairs)}**. "
        "Bars are word counts after the spaCy tokenizer used by the paper notebook."
    )

    src_hist = (
        alt.Chart(stats)
        .mark_bar(opacity=0.85, color="#2563eb")
        .encode(
            alt.X("src_words:Q", bin=alt.Bin(maxbins=24), title="Words in previous utterance"),
            alt.Y("count()", title="Pairs"),
            tooltip=["count()"],
        )
        .properties(title="Source length", width=360, height=220)
    )
    tgt_hist = (
        alt.Chart(stats)
        .mark_bar(opacity=0.85, color="#db2777")
        .encode(
            alt.X("tgt_words:Q", bin=alt.Bin(maxbins=24), title="Words in next reply"),
            alt.Y("count()", title="Pairs"),
            tooltip=["count()"],
        )
        .properties(title="Target length", width=360, height=220)
    )
    scatter = (
        alt.Chart(stats.sample(n=min(len(stats), 800), random_state=0))
        .mark_circle(size=36, opacity=0.35)
        .encode(
            alt.X("src_words:Q", title="Source words"),
            alt.Y("tgt_words:Q", title="Target words"),
            alt.Color("src_tokens:Q", scale=alt.Scale(scheme="plasma"), title="Src tokens"),
            tooltip=["src_words", "tgt_words", "src_tokens", "tgt_tokens"],
        )
        .properties(title="Source vs target length", width=360, height=220)
    )
    display_viz(alt.hconcat(src_hist, tgt_hist, scatter).resolve_scale(color="independent"))

    corr = stats.corr(numeric_only=True).reset_index().melt("index")
    corr.columns = ["row", "col", "correlation"]
    corr_chart = (
        alt.Chart(corr)
        .mark_rect()
        .encode(
            alt.X("col:O", title=None),
            alt.Y("row:O", title=None),
            alt.Color(
                "correlation:Q",
                scale=alt.Scale(scheme="redblue", domain=[-1, 1]),
                title="corr",
            ),
            tooltip=["row", "col", alt.Tooltip("correlation:Q", format=".2f")],
        )
        .properties(title="Length correlations (src/tgt chars, words, tokens)", width=320, height=280)
    )
    display_note(
        "Longer previous turns tend to get slightly longer replies. "
        "That correlation is in the **data**, not added to the model."
    )
    display_viz(corr_chart)
    print()
    print("How long the chat sentences are (%d training pairs)" % len(stats))
    print("Typical previous line: %.0f words (%.0f letters). Typical reply: %.0f words (%.0f letters)."
          % (stats["src_words"].mean(), stats["src_chars"].mean(), stats["tgt_words"].mean(), stats["tgt_chars"].mean()))
    print("Most turns are between %.0f and %.0f words. Shortest %.0f, longest %.0f."
          % (stats["src_words"].quantile(0.25), stats["src_words"].quantile(0.75), stats["src_words"].min(), stats["src_words"].max()))

    return example_df, stats


def show_training_charts(history, epoch_rows, num_epochs):
    """Charts of loss, learning rate, speed, and how many epochs finished."""
    display_note("### Training progress\nPaper optimizer: Adam + warmup `rate()`. Charts record the same loop.")
    charts = []
    if history:
        hdf = pd.DataFrame(history)
        loss_c = (
            alt.Chart(hdf)
            .mark_line(point=alt.OverlayMarkDef(size=40), strokeWidth=2.2, color="#2563eb")
            .encode(
                alt.X("global_step:Q", title="Optimizer step"),
                alt.Y("loss:Q", title="Batch token loss"),
                tooltip=["epoch", "batch", "global_step", "loss", "lr", "tokens_per_sec"],
            )
            .properties(title="Loss while training", width=400, height=230)
            .interactive()
        )
        lr_c = (
            alt.Chart(hdf)
            .mark_line(strokeWidth=2.2, color="#059669")
            .encode(
                alt.X("global_step:Q", title="Optimizer step"),
                alt.Y("lr:Q", title="Learning rate", axis=alt.Axis(format=".6f")),
                tooltip=["global_step", "lr", "epoch"],
            )
            .properties(title="Learning-rate schedule", width=400, height=230)
            .interactive()
        )
        spd_c = (
            alt.Chart(hdf)
            .mark_area(opacity=0.45, color="#7c3aed")
            .encode(
                alt.X("global_step:Q", title="Optimizer step"),
                alt.Y("tokens_per_sec:Q", title="Tokens / sec"),
                tooltip=["global_step", "tokens_per_sec", "epoch"],
            )
            .properties(title="Throughput", width=400, height=230)
            .interactive()
        )
        charts.append(alt.hconcat(loss_c, lr_c, spd_c))

        if len(hdf) >= 4:
            step_corr = hdf[["loss", "lr", "tokens_per_sec", "global_step"]].corr()
            melt = step_corr.reset_index().melt("index")
            melt.columns = ["row", "col", "correlation"]
            charts.append(
                alt.Chart(melt)
                .mark_rect()
                .encode(
                    alt.X("col:O", title=None),
                    alt.Y("row:O", title=None),
                    alt.Color(
                        "correlation:Q",
                        scale=alt.Scale(scheme="redblue", domain=[-1, 1]),
                    ),
                    tooltip=["row", "col", alt.Tooltip("correlation:Q", format=".2f")],
                )
                .properties(title="Training-curve correlations", width=260, height=230)
            )

    if epoch_rows:
        edf = pd.DataFrame(epoch_rows)
        edf["epoch_label"] = edf["epoch"].map(lambda e: f"epoch {int(e)}")
        fold = edf.melt(
            id_vars=["epoch", "epoch_label"],
            value_vars=["train_loss", "val_loss"],
            var_name="split",
            value_name="loss",
        )
        epoch_c = (
            alt.Chart(fold)
            .mark_bar(size=28, cornerRadius=3)
            .encode(
                alt.X("epoch_label:N", title="Completed epoch"),
                alt.Y("loss:Q", title="Mean token loss"),
                alt.Color(
                    "split:N",
                    scale=alt.Scale(
                        domain=["train_loss", "val_loss"],
                        range=["#2563eb", "#f59e0b"],
                    ),
                    legend=alt.Legend(title="Split"),
                ),
                alt.XOffset("split:N"),
                tooltip=["epoch", "split", alt.Tooltip("loss:Q", format=".3f")],
            )
            .properties(
                title=f"Train vs valid loss · {len(edf)}/{num_epochs} epochs done",
                width=max(220, 90 * len(edf)),
                height=230,
            )
        )
        done_n = int(len(edf))
        prog_df = pd.DataFrame(
            [
                {"status": "complete", "epochs": done_n},
                {"status": "remaining", "epochs": max(num_epochs - done_n, 0)},
            ]
        )
        prog_c = (
            alt.Chart(prog_df)
            .mark_bar(size=42, cornerRadius=4)
            .encode(
                alt.Y("status:N", title=None, sort=["complete", "remaining"]),
                alt.X("epochs:Q", title="Epochs"),
                alt.Color(
                    "status:N",
                    scale=alt.Scale(
                        domain=["complete", "remaining"],
                        range=["#059669", "#e5e7eb"],
                    ),
                    legend=None,
                ),
                tooltip=["status", "epochs"],
            )
            .properties(
                title=f"Epoch progress  {done_n}/{num_epochs}",
                width=360,
                height=120,
            )
        )
        charts.append(alt.hconcat(epoch_c, prog_c))

    if not charts:
        print("No training history yet (model was loaded, not trained this run).")
        return
    display_viz(alt.vconcat(*charts))


def weight_table(model):
    """Per-tensor weight stats. Architecture is unchanged; this only reads tensors."""
    rows = []
    for name, p in _unwrap_model(model).named_parameters():
        w = p.detach().float().cpu().reshape(-1)
        rows.append(
            {
                "parameter": name,
                "shape": "x".join(str(s) for s in p.shape),
                "n_weights": int(p.numel()),
                "mean": float(w.mean()),
                "std": float(w.std()) if w.numel() > 1 else 0.0,
                "l2": float(w.norm()),
                "abs_max": float(w.abs().max()),
            }
        )
    return pd.DataFrame(rows)


def show_weight_dashboard(model):
    display_note(
        "### How many weights, and how they look\n"
        "Same Encoder / Decoder / Multi-Head Attention as the paper. "
        "These plots only **inspect** `named_parameters()`."
    )
    wdf = weight_table(model)
    total = int(wdf["n_weights"].sum())
    print(f"Total trainable weights: {total:,}")

    def bucket(name):
        n = name.lower()
        if n.startswith("src_embed") or n.startswith("tgt_embed"):
            return "embeddings + PE"
        if "attn" in n:
            return "attention"
        if "feed_forward" in n or ".w_1" in n or ".w_2" in n:
            return "feed-forward"
        if "norm" in n:
            return "layer-norm"
        if n.startswith("generator"):
            return "generator"
        if n.startswith("encoder"):
            return "encoder (other)"
        if n.startswith("decoder"):
            return "decoder (other)"
        return "other"

    wdf["part"] = wdf["parameter"].map(bucket)
    parts = wdf.groupby("part", as_index=False)["n_weights"].sum()
    part_chart = (
        alt.Chart(parts)
        .mark_bar(cornerRadius=4, color="#4f46e5")
        .encode(
            alt.Y("part:N", sort="-x", title=None),
            alt.X("n_weights:Q", title="Number of weights"),
            tooltip=["part", "n_weights"],
        )
        .properties(title="Weights by block", width=420, height=180)
    )

    top = wdf.sort_values("n_weights", ascending=False).head(18)
    top_chart = (
        alt.Chart(top)
        .mark_bar(cornerRadius=2, color="#0ea5e9")
        .encode(
            alt.Y("parameter:N", sort="-x", title=None),
            alt.X("n_weights:Q", title="Weights"),
            alt.Color("std:Q", scale=alt.Scale(scheme="plasma"), title="std"),
            tooltip=["parameter", "shape", "n_weights", "mean", "std", "l2"],
        )
        .properties(title="Largest parameter tensors", width=480, height=360)
    )
    display_viz(alt.hconcat(part_chart, top_chart))

    # Layer-wise L2 and multi-correlation across encoder/decoder stacks
    layer_rows = []
    core = _unwrap_model(model)
    for stack_name, stack in (("encoder", core.encoder), ("decoder", core.decoder)):
        for i, layer in enumerate(stack.layers):
            flat = torch.cat(
                [p.detach().float().cpu().reshape(-1) for p in layer.parameters()]
            )
            layer_rows.append(
                {
                    "stack": stack_name,
                    "layer": i,
                    "n_weights": int(flat.numel()),
                    "mean": float(flat.mean()),
                    "std": float(flat.std()),
                    "l2": float(flat.norm()),
                }
            )
    ldf = pd.DataFrame(layer_rows)
    layer_chart = (
        alt.Chart(ldf)
        .mark_line(point=True, strokeWidth=2.4)
        .encode(
            alt.X("layer:O", title="Layer index (paper N-stack)"),
            alt.Y("l2:Q", title="L2 of all weights in the layer"),
            alt.Color("stack:N", scale=alt.Scale(range=["#2563eb", "#db2777"])),
            tooltip=["stack", "layer", "n_weights", "mean", "std", "l2"],
        )
        .properties(title="Weight L2 by Transformer layer", width=380, height=230)
        .interactive()
    )

    # Sampled Pearson correlation between layer weight vectors (same length via sample)
    rng = torch.Generator().manual_seed(0)
    samples = {}
    k = 2048
    for stack_name, stack in (("enc", core.encoder), ("dec", core.decoder)):
        for i, layer in enumerate(stack.layers):
            flat = torch.cat(
                [p.detach().float().cpu().reshape(-1) for p in layer.parameters()]
            )
            idx = torch.randint(0, flat.numel(), (k,), generator=rng)
            samples[f"{stack_name}{i}"] = flat[idx]
    names = list(samples.keys())
    mat = torch.stack([samples[n] for n in names], dim=0)
    # correlation across sampled dims
    mat = mat - mat.mean(dim=1, keepdim=True)
    std = mat.std(dim=1, keepdim=True).clamp_min(1e-8)
    corr = (mat / std) @ (mat / std).T / (k - 1)
    corr_rows = []
    for i, a in enumerate(names):
        for j, b in enumerate(names):
            corr_rows.append({"row": a, "col": b, "correlation": float(corr[i, j])})
    heat = (
        alt.Chart(pd.DataFrame(corr_rows))
        .mark_rect()
        .encode(
            alt.X("col:O", title=None),
            alt.Y("row:O", title=None),
            alt.Color(
                "correlation:Q",
                scale=alt.Scale(scheme="redblue", domain=[-1, 1]),
                title="corr",
            ),
            tooltip=["row", "col", alt.Tooltip("correlation:Q", format=".2f")],
        )
        .properties(
            title="Multi-correlation of sampled layer weights",
            width=280,
            height=280,
        )
    )
    display_viz(alt.hconcat(layer_chart, heat))
    display_viz(wdf.sort_values("n_weights", ascending=False).head(12))
    return wdf


@torch.no_grad()
def token_accuracy(model, dataloader, pad_idx, max_batches=40):
    """Teacher-forced next-token accuracy (argmax vs tgt_y, ignore pad)."""
    model.eval()
    module = _unwrap_model(model)
    correct = 0
    total = 0
    for i, b in enumerate(dataloader):
        batch = Batch(b[0], b[1], pad_idx)
        out = model.forward(batch.src, batch.tgt, batch.src_mask, batch.tgt_mask)
        pred = module.generator(out).argmax(-1)
        mask = batch.tgt_y != pad_idx
        correct += int((pred[mask] == batch.tgt_y[mask]).sum().item())
        total += int(mask.sum().item())
        if i + 1 >= max_batches:
            break
    acc = correct / max(total, 1)
    return acc, correct, total


def _clean_tokens(tokens, pad_idx, vocab, eos_string="</s>"):
    ids = [t for t in tokens if t != pad_idx]
    text = " ".join(vocab.id_to_token(x) for x in ids)
    return (text.split(eos_string, 1)[0] + " " + eos_string).strip()


def expected_vs_predicted_table(valid_dataloader, model, vocab, n_examples=8):
    """Expected reply vs greedy decode, plus overlap / difference."""
    pad_idx = vocab.token_to_id("<blank>")
    start_symbol = vocab.token_to_id("<s>")
    device = next(model.parameters()).device
    model.eval()
    rows = []
    data_iter = iter(valid_dataloader)
    for idx in range(n_examples):
        b = next(data_iter)
        rb = Batch(b[0], b[1], pad_idx)
        src = rb.src.to(device)
        src_mask = rb.src_mask.to(device)
        expected = _clean_tokens(rb.tgt[0].tolist(), pad_idx, vocab)
        pred_ids = greedy_decode(model, src[:1], src_mask[:1], 64, start_symbol)[0]
        predicted = _clean_tokens(pred_ids.tolist(), pad_idx, vocab)
        exp_set = set(expected.replace("<s>", "").replace("</s>", "").split())
        pred_set = set(predicted.replace("<s>", "").replace("</s>", "").split())
        exp_set.discard("")
        pred_set.discard("")
        inter = exp_set & pred_set
        union = exp_set | pred_set
        overlap = len(inter) / max(len(union), 1)
        missing = " ".join(sorted(exp_set - pred_set))
        extra = " ".join(sorted(pred_set - exp_set))
        rows.append(
            {
                "example": idx,
                "input": _clean_tokens(rb.src[0].tolist(), pad_idx, vocab),
                "expected": expected,
                "predicted": predicted,
                "overlap": round(overlap, 3),
                "missing_from_pred": missing[:120],
                "extra_in_pred": extra[:120],
            }
        )
    return pd.DataFrame(rows)


def show_quality_dashboard(model, vocab, spacy_en, config, valid_pairs, val_loss=None):
    """Accuracy, expected vs predicted, overlap, and what is realistic."""
    display_note(
        "### After training — model quality\n"
        "Teacher-forced **token accuracy** scores next-token argmax vs `tgt_y` "
        "(padding ignored). **Expected** is the true DailyDialog reply. "
        "**Predicted** is paper greedy decode. **Overlap** is Jaccard on words. "
        "**missing / extra** is the word-level difference."
    )
    device = next(model.parameters()).device
    pad_idx = vocab.token_to_id("<blank>")
    vocab_size = vocab.get_vocab_size()
    chance = 1.0 / max(vocab_size, 1)
    _, valid_loader = create_dataloaders(
        device,
        vocab,
        spacy_en,
        valid_pairs,
        valid_pairs,
        batch_size=config["batch_size"],
        max_padding=config["max_padding"],
    )
    acc, correct, total = token_accuracy(model, valid_loader, pad_idx)
    ppl = float(math.exp(min(val_loss, 20))) if val_loss is not None else None
    epochs_done = len(VIZ_STATE.get("epoch_rows") or [])
    if epochs_done == 0 and VIZ_STATE.get("did_train"):
        epochs_done = config["num_epochs"]

    _, single_loader = create_dataloaders(
        device,
        vocab,
        spacy_en,
        valid_pairs,
        valid_pairs,
        batch_size=1,
        max_padding=config["max_padding"],
    )
    cmp = expected_vs_predicted_table(single_loader, model, vocab, n_examples=8)
    mean_overlap = float(cmp["overlap"].mean()) if len(cmp) else 0.0
    exact = int((cmp["overlap"] >= 0.999).sum()) if len(cmp) else 0

    summary = pd.DataFrame(
        [
            {
                "epochs_configured": config["num_epochs"],
                "epochs_logged": epochs_done,
                "N_layers": config["N"],
                "d_model": config["d_model"],
                "vocab_size": vocab_size,
                "valid_pairs": len(valid_pairs),
                "token_accuracy": round(acc, 4),
                "chance_accuracy": round(chance, 6),
                "accuracy_minus_chance": round(acc - chance, 4),
                "correct_tokens": correct,
                "scored_tokens": total,
                "val_loss": None if val_loss is None else round(float(val_loss), 4),
                "perplexity": None if ppl is None else round(ppl, 2),
                "mean_overlap": round(mean_overlap, 3),
                "exact_match_shown": exact,
            }
        ]
    )
    display_viz(summary)

    metric_df = pd.DataFrame(
        [
            {"metric": "token accuracy", "value": acc},
            {"metric": "chance (1 / vocab)", "value": chance},
            {"metric": "mean overlap vs expected", "value": mean_overlap},
        ]
    )
    metric_chart = (
        alt.Chart(metric_df)
        .mark_bar(cornerRadius=4)
        .encode(
            alt.Y("metric:N", sort=["token accuracy", "mean overlap vs expected", "chance (1 / vocab)"], title=None),
            alt.X("value:Q", title="Score", scale=alt.Scale(domain=[0, 1])),
            alt.Color(
                "metric:N",
                scale=alt.Scale(
                    domain=["token accuracy", "mean overlap vs expected", "chance (1 / vocab)"],
                    range=["#2563eb", "#0891b2", "#9ca3af"],
                ),
                legend=None,
            ),
            tooltip=["metric", alt.Tooltip("value:Q", format=".3f")],
        )
        .properties(title="Accuracy vs chance vs overlap", width=480, height=160)
    )

    len_rows = []
    for _, row in cmp.iterrows():
        exp_n = len(str(row["expected"]).split())
        pred_n = len(str(row["predicted"]).split())
        len_rows.append(
            {
                "example": int(row["example"]),
                "expected_words": exp_n,
                "predicted_words": pred_n,
                "word_diff": pred_n - exp_n,
            }
        )
    len_df = pd.DataFrame(len_rows)
    len_fold = len_df.melt(
        id_vars=["example"],
        value_vars=["expected_words", "predicted_words"],
        var_name="side",
        value_name="words",
    )
    len_chart = (
        alt.Chart(len_fold)
        .mark_bar(size=18, cornerRadius=2)
        .encode(
            alt.X("example:O", title="Example"),
            alt.Y("words:Q", title="Words"),
            alt.Color(
                "side:N",
                scale=alt.Scale(
                    domain=["expected_words", "predicted_words"],
                    range=["#059669", "#db2777"],
                ),
                legend=alt.Legend(title="Reply"),
            ),
            alt.XOffset("side:N"),
            tooltip=["example", "side", "words"],
        )
        .properties(title="Expected vs predicted length", width=420, height=200)
    )
    display_viz(alt.hconcat(metric_chart, len_chart))

    if config["mode"] == "local":
        expected_note = (
            "**What to expect (local half-data):** 8 epochs, N=2, ~38k train pairs. "
            "Token accuracy should beat the old 15k/1-epoch run (~26%), but greedy "
            "replies can still look repetitive. That is normal for this 2017 model."
        )
    else:
        expected_note = (
            "**What to expect (full / Kaggle run):** more data and N=6. Token accuracy "
            "and overlap should beat local mode, still far from a modern chatbot."
        )
    display_note(
        expected_note
        + "\n\n**Difference column:** `missing_from_pred` = words in the true reply "
        "the model dropped. `extra_in_pred` = words the model added."
    )
    display_viz(cmp)

    overlap_chart = (
        alt.Chart(cmp)
        .mark_bar(cornerRadius=3, color="#0891b2")
        .encode(
            alt.X("example:O", title="Validation example"),
            alt.Y("overlap:Q", title="Token overlap vs expected", scale=alt.Scale(domain=[0, 1])),
            tooltip=["example", "overlap", "expected", "predicted"],
        )
        .properties(title="Expected vs predicted overlap", width=420, height=220)
    )
    display_viz(overlap_chart)
    print(
        f"Mean overlap on shown examples: {mean_overlap:.3f}  |  "
        f"token accuracy: {acc:.3%}  ({correct}/{total})  |  "
        f"chance: {chance:.3%}  |  lift: {acc - chance:.3%}"
    )
    return summary, cmp


def checkpoint_paths(config):
    prefix = config["file_prefix"]
    return {
        "last": "%slast.pt" % prefix,
        "final": "%sfinal.pt" % prefix,
        "epoch": lambda n: "%sepoch_%d.pt" % (prefix, n),
        "step": lambda n: "%sstep_%d.pt" % (prefix, n),
    }


def collect_rng_state():
    state = {
        "python": random.getstate(),
        "torch": torch.get_rng_state(),
    }
    if torch.cuda.is_available():
        state["cuda"] = torch.cuda.get_rng_state_all()
    return state


def restore_rng_state(state):
    if not state:
        return
    random.setstate(state["python"])
    torch.set_rng_state(state["torch"])
    if torch.cuda.is_available() and "cuda" in state:
        torch.cuda.set_rng_state_all(state["cuda"])


def build_checkpoint(
    module,
    optimizer,
    scheduler,
    epoch,
    train_state,
    config,
    epoch_done,
    history=None,
    epoch_rows=None,
    val_loss=None,
):
    return {
        "model": module.state_dict(),
        "optimizer": optimizer.state_dict(),
        "scheduler": scheduler.state_dict(),
        "epoch": epoch,
        "step": train_state.step,
        "accum_step": train_state.accum_step,
        "samples": train_state.samples,
        "tokens": int(train_state.tokens),
        "epoch_done": epoch_done,
        "config": config,
        "rng": collect_rng_state(),
        "viz_history": list(history or []),
        "epoch_rows": list(epoch_rows or []),
        "val_loss": val_loss,
    }


def save_checkpoint(path, payload):
    torch.save(payload, path)
    print(f"Saved {path}", flush=True)


def load_checkpoint_file(path, map_location="cpu"):
    return torch.load(path, map_location=map_location)


def unwrap_model_state(obj):
    "Accept v3 checkpoint dict or a raw state_dict from v2."
    if isinstance(obj, dict) and "model" in obj and "optimizer" in obj:
        return obj["model"], obj
    return obj, None


def train_worker(vocab, spacy_en, config):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Train worker using device: {device}", flush=True)
    print(f"RUN_MODE={config['mode']} N={config['N']} epochs={config['num_epochs']}", flush=True)

    pad_idx = vocab.token_to_id("<blank>")
    d_model = config["d_model"]
    vocab_size = vocab.get_vocab_size()
    paths = checkpoint_paths(config)
    save_every = int(config.get("save_every_steps", 200))

    model = make_model(
        vocab_size,
        vocab_size,
        N=config["N"],
        d_model=d_model,
    )
    model.to(device)
    module = model

    if torch.cuda.device_count() > 1:
        print(f"Using DataParallel across {torch.cuda.device_count()} GPUs", flush=True)
        model = nn.DataParallel(model)
        module = model.module

    criterion = LabelSmoothing(size=vocab_size, padding_idx=pad_idx, smoothing=0.1)
    criterion.to(device)

    train_pairs = build_dailydialog_pairs("train", max_pairs=config["train_pairs"])
    valid_pairs = build_dailydialog_pairs("validation", max_pairs=config["valid_pairs"])
    print(f"Train pairs: {len(train_pairs)} | Valid pairs: {len(valid_pairs)}", flush=True)
    show_dataset_views(train_pairs, valid_pairs, spacy_en, vocab=vocab)

    train_dataloader, valid_dataloader = create_dataloaders(
        device,
        vocab,
        spacy_en,
        train_pairs,
        valid_pairs,
        batch_size=config["batch_size"],
        max_padding=config["max_padding"],
    )

    optimizer = torch.optim.Adam(
        model.parameters(), lr=config["base_lr"], betas=(0.9, 0.98), eps=1e-9
    )
    lr_scheduler = LambdaLR(
        optimizer=optimizer,
        lr_lambda=lambda step: rate(
            step, d_model, factor=1, warmup=config["warmup"]
        ),
    )

    train_state = TrainState()
    history = []
    epoch_rows = []
    last_val_loss = None
    start_epoch = 0
    resume_path = paths["last"]
    if exists(resume_path):
        print(f"Resuming from {resume_path}", flush=True)
        ckpt = load_checkpoint_file(resume_path, map_location=device)
        model_state, full = unwrap_model_state(ckpt)
        module.load_state_dict(model_state)
        if full is not None:
            optimizer.load_state_dict(full["optimizer"])
            lr_scheduler.load_state_dict(full["scheduler"])
            train_state.step = full.get("step", 0)
            train_state.accum_step = full.get("accum_step", 0)
            train_state.samples = full.get("samples", 0)
            train_state.tokens = full.get("tokens", 0)
            restore_rng_state(full.get("rng"))
            history = list(full.get("viz_history") or [])
            epoch_rows = list(full.get("epoch_rows") or [])
            last_val_loss = full.get("val_loss")
            done = bool(full.get("epoch_done", False))
            start_epoch = full["epoch"] + (1 if done else 0)
            print(
                f"Resume at epoch {start_epoch} (saved epoch={full['epoch']}, "
                f"epoch_done={done}, step={train_state.step})",
                flush=True,
            )
        else:
            print("Loaded raw state_dict; training epochs restart at 0 with these weights.", flush=True)

    current_epoch = start_epoch
    finished = False

    def pack_ckpt(epoch, epoch_done, state=None):
        return build_checkpoint(
            module,
            optimizer,
            lr_scheduler,
            epoch,
            state if state is not None else train_state,
            config,
            epoch_done,
            history=history,
            epoch_rows=epoch_rows,
            val_loss=last_val_loss,
        )

    def write_last(epoch, epoch_done):
        save_checkpoint(paths["last"], pack_ckpt(epoch, epoch_done))

    try:
        for epoch in range(start_epoch, config["num_epochs"]):
            current_epoch = epoch
            model.train()
            print(f"Epoch {epoch} Training ====", flush=True)

            def on_step(batch_i, state):
                if save_every > 0 and state.step > 0 and state.step % save_every == 0:
                    save_checkpoint(
                        paths["step"](state.step),
                        pack_ckpt(epoch, False, state=state),
                    )
                    write_last(epoch, False)

            train_loss, train_state = run_epoch(
                (Batch(b[0], b[1], pad_idx) for b in train_dataloader),
                model,
                SimpleLossCompute(module.generator, criterion),
                optimizer,
                lr_scheduler,
                mode="train+log",
                accum_iter=config["accum_iter"],
                train_state=train_state,
                on_step=on_step,
                history=history,
                epoch=epoch,
            )
            train_loss = float(train_loss)

            try:
                GPUtil.showUtilization()
            except Exception:
                pass

            print(f"Epoch {epoch} Validation ====", flush=True)
            model.eval()
            val_loss, _ = run_epoch(
                (Batch(b[0], b[1], pad_idx) for b in valid_dataloader),
                model,
                SimpleLossCompute(module.generator, criterion),
                DummyOptimizer(),
                DummyScheduler(),
                mode="eval",
            )
            val_loss = float(val_loss)
            last_val_loss = val_loss
            print(f"Validation loss: {val_loss:.4f}", flush=True)
            epoch_rows.append(
                {
                    "epoch": epoch,
                    "train_loss": train_loss,
                    "val_loss": val_loss,
                    "steps": train_state.step,
                    "tokens": train_state.tokens,
                }
            )
            print(epoch_progress_bar(epoch, config["num_epochs"]), flush=True)
            print(
                f"  train_loss={train_loss:.4f}  val_loss={val_loss:.4f}  "
                f"steps={train_state.step}  tokens_seen={train_state.tokens}",
                flush=True,
            )
            show_training_charts(history, epoch_rows, config["num_epochs"])

            save_checkpoint(paths["epoch"](epoch), pack_ckpt(epoch, True))
            write_last(epoch, True)
            if device.type == "cuda":
                torch.cuda.empty_cache()

        save_checkpoint(
            paths["final"],
            pack_ckpt(config["num_epochs"] - 1, True),
        )
        write_last(config["num_epochs"] - 1, True)
        finished = True
        print("=" * 60, flush=True)
        print(
            "Training complete. Saved chat model: %s" % paths["final"],
            flush=True,
        )
        print(
            f"Epochs finished: {config['num_epochs']}/{config['num_epochs']}  "
            f"final val_loss={last_val_loss}",
            flush=True,
        )
        print("=" * 60, flush=True)
    except KeyboardInterrupt:
        print("Interrupted. Writing last checkpoint...", flush=True)
        write_last(current_epoch, False)
        raise
    finally:
        if not finished:
            write_last(current_epoch, False)

    VIZ_STATE["history"] = history
    VIZ_STATE["epoch_rows"] = epoch_rows
    VIZ_STATE["did_train"] = True
    VIZ_STATE["val_loss"] = last_val_loss
    VIZ_STATE["valid_pairs"] = valid_pairs

    show_quality_dashboard(
        module, vocab, spacy_en, config, valid_pairs, val_loss=last_val_loss
    )
    show_weight_dashboard(module)
    return module


def train_model(vocab, spacy_en, config):
    return train_worker(vocab, spacy_en, config)


def load_model_weights(model, path, map_location="cpu"):
    obj = load_checkpoint_file(path, map_location=map_location)
    state, _ = unwrap_model_state(obj)
    model.load_state_dict(state)
    return model


def load_trained_model(vocab, spacy_en, config=None):
    if config is None:
        config = get_run_config()
    paths = checkpoint_paths(config)
    model_path = paths["final"]
    last_path = paths["last"]

    if exists(model_path):
        print(f"Loading finished model {model_path}", flush=True)
        VIZ_STATE["did_train"] = False
    elif exists(last_path):
        print(f"No final checkpoint. Continuing from {last_path}", flush=True)
        train_model(vocab, spacy_en, config)
        model_path = paths["final"] if exists(paths["final"]) else last_path
    else:
        print("No checkpoint found. Starting training from scratch...", flush=True)
        train_model(vocab, spacy_en, config)
        model_path = paths["final"] if exists(paths["final"]) else last_path

    model = make_model(
        vocab.get_vocab_size(),
        vocab.get_vocab_size(),
        N=config["N"],
        d_model=config["d_model"],
    )
    load_model_weights(model, model_path, map_location="cpu")
    if not VIZ_STATE.get("did_train"):
        try:
            obj = load_checkpoint_file(model_path, map_location="cpu")
            if isinstance(obj, dict):
                VIZ_STATE["history"] = list(obj.get("viz_history") or [])
                VIZ_STATE["epoch_rows"] = list(obj.get("epoch_rows") or [])
                VIZ_STATE["val_loss"] = obj.get("val_loss")
        except Exception:
            pass
    return model


def check_outputs(
    valid_dataloader,
    model,
    vocab,
    n_examples=5,
    eos_string="</s>",
):
    pad_idx = vocab.token_to_id("<blank>")
    start_symbol = vocab.token_to_id("<s>")
    device = next(model.parameters()).device
    model.eval()
    results = [()] * n_examples
    data_iter = iter(valid_dataloader)
    for idx in range(n_examples):
        print("\nExample %d ========\n" % idx)
        b = next(data_iter)
        rb = Batch(b[0], b[1], pad_idx)
        src = rb.src.to(device)
        src_mask = rb.src_mask.to(device)

        src_tokens = [
            vocab.id_to_token(x) for x in rb.src[0].tolist() if x != pad_idx
        ]
        tgt_tokens = [
            vocab.id_to_token(x) for x in rb.tgt[0].tolist() if x != pad_idx
        ]

        print("Input Utterance    : " + " ".join(src_tokens).replace("\n", ""))
        print("Ground Truth Reply : " + " ".join(tgt_tokens).replace("\n", ""))

        model_out = greedy_decode(
            model, src[:1], src_mask[:1], 64, start_symbol
        )[0]
        model_txt = (
            " ".join(
                [vocab.id_to_token(x) for x in model_out.tolist() if x != pad_idx]
            ).split(eos_string, 1)[0]
            + eos_string
        )
        print("Model Reply        : " + model_txt.replace("\n", ""))
        results[idx] = (rb, src_tokens, tgt_tokens, model_out, model_txt)
    return results


def run_model_example(n_examples=5):
    global vocab, spacy_en, model, RUN_CONFIG

    print("Preparing Data ...")
    valid_pairs = build_dailydialog_pairs(
        "validation", max_pairs=RUN_CONFIG["valid_pairs"]
    )
    _, valid_dataloader = create_dataloaders(
        torch.device("cpu"),
        vocab,
        spacy_en,
        valid_pairs,
        valid_pairs,
        batch_size=1,
        max_padding=RUN_CONFIG["max_padding"],
    )

    print("Checking Model Outputs:")
    cpu_model = model.cpu()
    example_data = check_outputs(
        valid_dataloader, cpu_model, vocab, n_examples=n_examples
    )
    return cpu_model, example_data


def encode_user_text(text, vocab, spacy_en, device, max_padding):
    pad_id = vocab.token_to_id("<blank>")
    bos_id = vocab.token_to_id("<s>")
    eos_id = vocab.token_to_id("</s>")
    max_body = max(1, max_padding - 2)
    ids = vocab.encode(" ".join(tokenize(normalize_text(text), spacy_en))).ids[:max_body]
    src = torch.tensor([[bos_id] + ids + [eos_id]], dtype=torch.int64, device=device)
    if src.size(1) < max_padding:
        src = pad(src, (0, max_padding - src.size(1)), value=pad_id)
    src_mask = (src != pad_id).unsqueeze(-2)
    return src, src_mask


def decode_ids(ids, vocab, eos_string="</s>"):
    pad_id = vocab.token_to_id("<blank>")
    bos_id = vocab.token_to_id("<s>")
    tokens = []
    for x in ids:
        if x == pad_id or x == bos_id:
            continue
        tok = vocab.id_to_token(int(x))
        if tok == eos_string:
            break
        tokens.append(tok)
    return " ".join(tokens)


def generate_reply(model, vocab, spacy_en, text, max_len=64, max_padding=48):
    device = next(model.parameters()).device
    model.eval()
    src, src_mask = encode_user_text(text, vocab, spacy_en, device, max_padding)
    start_symbol = vocab.token_to_id("<s>")
    with torch.no_grad():
        out = greedy_decode(model, src, src_mask, max_len, start_symbol)[0]
    return decode_ids(out.tolist(), vocab)


def demo_chat(model, vocab, spacy_en, max_padding=48, max_len=64):
    """Fixed prompts so Kaggle Save Version / batch runs do not block on input()."""
    prompts = [
        "hello",
        "how are you",
        "what are you doing today",
        "thanks a lot",
    ]
    print("Demo chat (non-interactive). This is a 2017 seq2seq reply model, not ChatGPT.")
    for user in prompts:
        reply = generate_reply(
            model, vocab, spacy_en, user, max_len=max_len, max_padding=max_padding
        )
        print("You:", user)
        print("Bot:", reply)
        print()


def chat_loop(model, vocab, spacy_en, max_padding=48, max_len=64):
    """One-turn seq2seq chat. Type quit/exit to stop."""
    print("Chat ready. Type a sentence and press Enter. Type 'quit' to stop.")
    print("This is a 2017 encoder-decoder reply model, not ChatGPT.")
    while True:
        try:
            user = input("You: ").strip()
        except EOFError:
            print()
            break
        if not user:
            continue
        if user.lower() in ("quit", "exit", "q"):
            print("Bye.")
            break
        reply = generate_reply(
            model, vocab, spacy_en, user, max_len=max_len, max_padding=max_padding
        )
        print("Bot:", reply)



def launch_gradio_chat(model, vocab, spacy_en, max_padding=48, max_len=64):
    """Notebook chat UI with 4 example prompts. Uses the same greedy_decode as chat_loop."""
    try:
        import gradio as gr
    except ImportError:
        import subprocess
        import sys

        print("Installing gradio ...", flush=True)
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "gradio"])
        import gradio as gr

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    chat_model = model.to(device)
    chat_model.eval()
    examples = [
        "hello",
        "how are you",
        "what are you doing today",
        "thanks a lot",
    ]

    def reply_one(message):
        text = (message or "").strip()
        if not text:
            return "Type a short everyday sentence, then Send."
        return generate_reply(
            chat_model,
            vocab,
            spacy_en,
            text,
            max_len=max_len,
            max_padding=max_padding,
        )

    def submit(user_text, history):
        history = list(history or [])
        text = (user_text or "").strip()
        if not text:
            return history, user_text or ""
        bot = reply_one(text)
        history.append({"role": "user", "content": text})
        history.append({"role": "assistant", "content": bot})
        return history, ""

    print("Opening Gradio chat. This is one-turn seq2seq, not ChatGPT.", flush=True)
    with gr.Blocks(title="v3 Transformer chat") as demo:
        gr.Markdown(
            "## Chat with your trained Transformer\n"
            "Type in the box and press **Send**. The 4 buttons are example sentences.\n"
            "Each reply is a new greedy decode (no long memory)."
        )
        try:
            chatbot = gr.Chatbot(label="Conversation", height=380, type="messages")
        except TypeError:
            chatbot = gr.Chatbot(label="Conversation", height=380)
        msg = gr.Textbox(
            label="You",
            placeholder="Type here, then Send",
            lines=2,
        )
        with gr.Row():
            send = gr.Button("Send", variant="primary")
            clear = gr.Button("Clear")
        gr.Examples(examples, inputs=msg, label="4 example sentences")
        send.click(submit, [msg, chatbot], [chatbot, msg])
        msg.submit(submit, [msg, chatbot], [chatbot, msg])
        clear.click(lambda: ([], ""), outputs=[chatbot, msg])

    return demo.launch(inline=True, quiet=False)


def should_run_interactive_chat():
    if os.environ.get("ENABLE_CHAT", "1").lower() in ("0", "false", "no"):
        return False
    if os.environ.get("KAGGLE_KERNEL_RUN_TYPE") == "Batch":
        return False
    return True


if is_interactive_notebook():
    RUN_CONFIG = get_run_config()
    print("Using config:", RUN_CONFIG)
    if running_on_kaggle():
        print(
            "Kaggle: GPU + Internet must be on. Checkpoints write to /kaggle/working "
            "with prefix",
            RUN_CONFIG["file_prefix"],
            flush=True,
        )
    spacy_en = load_tokenizer_en()
    train_pairs_for_vocab = build_dailydialog_pairs(
        "train", max_pairs=RUN_CONFIG["train_pairs"]
    )
    vocab = load_vocab(spacy_en, train_pairs_for_vocab, vocab_path=RUN_CONFIG.get("vocab_path", "vocab.json"))
    model = load_trained_model(vocab, spacy_en, RUN_CONFIG)
    print(
        "Model ready. Checkpoints use prefix:",
        RUN_CONFIG["file_prefix"],
        flush=True,
    )

    if not VIZ_STATE.get("did_train"):
        valid_pairs = build_dailydialog_pairs(
            "validation", max_pairs=RUN_CONFIG["valid_pairs"]
        )
        show_dataset_views(
            train_pairs_for_vocab, valid_pairs, spacy_en, vocab=vocab
        )
        show_training_charts(
            VIZ_STATE.get("history") or [],
            VIZ_STATE.get("epoch_rows") or [],
            RUN_CONFIG["num_epochs"],
        )
        show_quality_dashboard(
            model,
            vocab,
            spacy_en,
            RUN_CONFIG,
            valid_pairs,
            val_loss=VIZ_STATE.get("val_loss"),
        )
        show_weight_dashboard(model)

    run_model_example(n_examples=3)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)

    def _in_notebook():
        try:
            from IPython import get_ipython
            return get_ipython() is not None
        except Exception:
            return False

    demo_chat(
        model,
        vocab,
        spacy_en,
        max_padding=RUN_CONFIG["max_padding"],
    )

    if should_run_interactive_chat() and not _in_notebook():
        chat_loop(
            model,
            vocab,
            spacy_en,
            max_padding=RUN_CONFIG["max_padding"],
        )
    elif _in_notebook():
        print(
            "Training/load done. Demo chat ran above. Run the last cell for Gradio chat."
        )

Using config: {'mode': 'local', 'train_pairs': 76052, 'valid_pairs': 7069, 'batch_size': 8, 'num_epochs': 8, 'accum_iter': 4, 'base_lr': 1.0, 'max_padding': 48, 'warmup': 2000, 'N': 2, 'd_model': 512, 'file_prefix': 'dailydialog_local38k8e_', 'vocab_path': 'vocab_local38k.json', 'save_every_steps': 2500}
Finished.
Vocabulary size:
14578
No checkpoint found. Starting training from scratch...
Train worker using device: cuda
RUN_MODE=local N=2 epochs=8
Train pairs: 76052 | Valid pairs: 7069

### Data view 1 — what the conversations look like
DailyDialog is everyday chat. Each **row** is one training example: previous utterance (`src`) → next utterance (`tgt`). The same short lines (hello, thanks, okay) often **repeat**.

    times             utterance
0     144                  Yes.
1     110            Thank you.
2      90                  Why?
3      77         Here you are.
4      64       Can I help you?
5      64               Really?
6      61     What do you mean?
7      61       May I help you?
8      55                 Sure.
9      55  Thank you very much.
10     53              Why not?
11     48                   OK.

### Data view 2 — example pairs the model actually trains on
This is the seq2seq layout from *Attention Is All You Need*: encode `src`, decode `tgt`. No extra chat template.

,pair,previous (src),next reply (tgt)
0,0,"Say, Jim, how about going for a few beers after dinner?",You know that is tempting but is really not good for our fitness.
1,1,You know that is tempting but is really not good for our fitness.,What do you mean? It will help us to relax.
2,2,What do you mean? It will help us to relax.,Do you really think so? I don't. It will just make us fat and act silly. Remember last time?
3,3,Do you really think so? I don't. It will just make us fat and act silly. Remember last time?,I guess you are right.But what shall we do? I don't feel like sitting at home.
4,4,I guess you are right.But what shall we do? I don't feel like sitting at home.,I suggest a walk over to the gym where we can play singsong and meet some of our friends.
5,5,I suggest a walk over to the gym where we can play singsong and meet some of our friends.,That's a good idea. I hear Mary and Sally often go there to play pingpong.Perhaps we can make a ...
6,6,That's a good idea. I hear Mary and Sally often go there to play pingpong.Perhaps we can make a ...,"Sounds great to me! If they are willing, we could ask them to go dancing with us.That is excelle..."
7,7,"Sounds great to me! If they are willing, we could ask them to go dancing with us.That is excelle...",Good.Let's go now.
8,8,Good.Let's go now.,All right.
9,9,Can you do push-ups?,"Of course I can. It's a piece of cake! Believe it or not, I can do 30 push-ups a minute."

### How those pairs look as sequences
Train pairs: **76052** · valid pairs: **7069**. Bars are word counts after the spaCy tokenizer used by the paper notebook.

alt.HConcatChart(...)

Longer previous turns tend to get slightly longer replies. That correlation is in the **data**, not added to the model.

alt.Chart(...)

How long the chat sentences are (15000 training pairs)
Typical previous line: 15 words (60 letters). Typical reply: 15 words (60 letters).
Most turns are between 8 and 18 words. Shortest 1, longest 152.
Epoch 0 Training ====
Step 1 | Loss 8.33 | Speed 154 tokens/sec | Learning rate 0.00000099
Step 41 | Loss 8.14 | Speed 2413 tokens/sec | Learning rate 0.00002075
Step 81 | Loss 7.63 | Speed 2525 tokens/sec | Learning rate 0.00004052
Step 121 | Loss 7.43 | Speed 2371 tokens/sec | Learning rate 0.00006028
Step 161 | Loss 7.06 | Speed 2302 tokens/sec | Learning rate 0.00008005
Step 201 | Loss 6.50 | Speed 2418 tokens/sec | Learning rate 0.00009981
Step 241 | Loss 6.13 | Speed 2281 tokens/sec | Learning rate 0.00011957
Step 281 | Loss 5.65 | Speed 2436 tokens/sec | Learning rate 0.00013934
Step 321 | Loss 5.16 | Speed 2258 tokens/sec | Learning rate 0.0001591
Step 361 | Loss 4.71 | Speed 2414 tokens/sec | Learning rate 0.00017887
Step 401 | Loss 5.35 | Speed 2404 tokens/sec | Learning rate 0.00019863
Step 441 | Loss 5.11 | Speed 2391 tokens/sec | Learning rate 0.00021839
Step 481 | Loss 4.32 | Speed 2315 tokens/sec | Learning rate 0.00023816
Step 521 | Loss 4.90 | Speed 2518 tokens/sec | Learning rate 0.00025792
Step 561 | Loss 4.61 | Speed 2371 tokens/sec | Learning rate 0.00027769
Step 601 | Loss 4.96 | Speed 2479 tokens/sec | Learning rate 0.00029745
Step 641 | Loss 4.51 | Speed 2354 tokens/sec | Learning rate 0.00031722
Step 681 | Loss 4.74 | Speed 2425 tokens/sec | Learning rate 0.00033698
Step 721 | Loss 4.32 | Speed 2333 tokens/sec | Learning rate 0.00035674
Step 761 | Loss 4.10 | Speed 2506 tokens/sec | Learning rate 0.00037651
Step 801 | Loss 4.46 | Speed 2338 tokens/sec | Learning rate 0.00039627
Step 841 | Loss 4.27 | Speed 2386 tokens/sec | Learning rate 0.00041604
Step 881 | Loss 4.41 | Speed 2323 tokens/sec | Learning rate 0.0004358
Step 921 | Loss 4.53 | Speed 2276 tokens/sec | Learning rate 0.00045557
Step 961 | Loss 3.94 | Speed 2269 tokens/sec | Learning rate 0.00047533
Step 1001 | Loss 4.25 | Speed 2238 tokens/sec | Learning rate 0.00049509
Step 1041 | Loss 4.34 | Speed 2126 tokens/sec | Learning rate 0.00051486
Step 1081 | Loss 4.50 | Speed 2385 tokens/sec | Learning rate 0.00053462
Step 1121 | Loss 4.04 | Speed 2100 tokens/sec | Learning rate 0.00055439
Step 1161 | Loss 3.59 | Speed 2342 tokens/sec | Learning rate 0.00057415
Step 1201 | Loss 3.97 | Speed 2327 tokens/sec | Learning rate 0.00059392
Step 1241 | Loss 4.06 | Speed 2219 tokens/sec | Learning rate 0.00061368
Step 1281 | Loss 4.38 | Speed 2303 tokens/sec | Learning rate 0.00063344
Step 1321 | Loss 4.02 | Speed 2222 tokens/sec | Learning rate 0.00065321
Step 1361 | Loss 4.23 | Speed 2274 tokens/sec | Learning rate 0.00067297
Step 1401 | Loss 4.87 | Speed 2224 tokens/sec | Learning rate 0.00069274
Step 1441 | Loss 3.47 | Speed 2149 tokens/sec | Learning rate 0.0007125
Step 1481 | Loss 3.91 | Speed 2137 tokens/sec | Learning rate 0.00073226
Step 1521 | Loss 4.16 | Speed 2136 tokens/sec | Learning rate 0.00075203
Step 1561 | Loss 4.17 | Speed 2183 tokens/sec | Learning rate 0.00077179
Step 1601 | Loss 3.48 | Speed 2077 tokens/sec | Learning rate 0.00079156
Step 1641 | Loss 4.30 | Speed 2115 tokens/sec | Learning rate 0.00081132
Step 1681 | Loss 3.33 | Speed 2076 tokens/sec | Learning rate 0.00083109
Step 1721 | Loss 3.87 | Speed 2073 tokens/sec | Learning rate 0.00085085
Step 1761 | Loss 3.95 | Speed 2184 tokens/sec | Learning rate 0.00087061
Step 1801 | Loss 4.43 | Speed 2169 tokens/sec | Learning rate 0.00089038
Step 1841 | Loss 4.16 | Speed 2164 tokens/sec | Learning rate 0.00091014
Step 1881 | Loss 4.29 | Speed 2253 tokens/sec | Learning rate 0.00092991
Step 1921 | Loss 4.16 | Speed 2235 tokens/sec | Learning rate 0.00094967
Step 1961 | Loss 4.68 | Speed 2216 tokens/sec | Learning rate 0.00096944
Step 2001 | Loss 3.72 | Speed 2144 tokens/sec | Learning rate 0.00098772
Step 2041 | Loss 3.61 | Speed 2154 tokens/sec | Learning rate 0.000978
Step 2081 | Loss 3.47 | Speed 2172 tokens/sec | Learning rate 0.00096856
Step 2121 | Loss 3.39 | Speed 2078 tokens/sec | Learning rate 0.00095938
Step 2161 | Loss 3.62 | Speed 2002 tokens/sec | Learning rate 0.00095047
Step 2201 | Loss 3.85 | Speed 2139 tokens/sec | Learning rate 0.00094179
Step 2241 | Loss 4.02 | Speed 2202 tokens/sec | Learning rate 0.00093336
Step 2281 | Loss 3.81 | Speed 1928 tokens/sec | Learning rate 0.00092514
Step 2321 | Loss 3.88 | Speed 2129 tokens/sec | Learning rate 0.00091714
Step 2361 | Loss 3.87 | Speed 1959 tokens/sec | Learning rate 0.00090934
Step 2401 | Loss 3.58 | Speed 2063 tokens/sec | Learning rate 0.00090173
Step 2441 | Loss 3.56 | Speed 2154 tokens/sec | Learning rate 0.00089432
Step 2481 | Loss 3.52 | Speed 1986 tokens/sec | Learning rate 0.00088708
Saved dailydialog_local38k8e_step_2500.pt
Saved dailydialog_local38k8e_last.pt
Step 2521 | Loss 4.21 | Speed 889 tokens/sec | Learning rate 0.00088002
Step 2561 | Loss 3.41 | Speed 2093 tokens/sec | Learning rate 0.00087312
Step 2601 | Loss 3.62 | Speed 2048 tokens/sec | Learning rate 0.00086639
Step 2641 | Loss 4.19 | Speed 2255 tokens/sec | Learning rate 0.0008598
Step 2681 | Loss 2.83 | Speed 1974 tokens/sec | Learning rate 0.00085337
Step 2721 | Loss 4.02 | Speed 2062 tokens/sec | Learning rate 0.00084707
Step 2761 | Loss 4.43 | Speed 2047 tokens/sec | Learning rate 0.00084092
Step 2801 | Loss 4.03 | Speed 1916 tokens/sec | Learning rate 0.00083489
Step 2841 | Loss 3.57 | Speed 2083 tokens/sec | Learning rate 0.000829
Step 2881 | Loss 3.41 | Speed 1970 tokens/sec | Learning rate 0.00082322
Step 2921 | Loss 4.11 | Speed 2039 tokens/sec | Learning rate 0.00081757
Step 2961 | Loss 3.74 | Speed 1940 tokens/sec | Learning rate 0.00081203
Step 3001 | Loss 3.30 | Speed 2006 tokens/sec | Learning rate 0.0008066
Step 3041 | Loss 3.31 | Speed 1955 tokens/sec | Learning rate 0.00080128
Step 3081 | Loss 4.08 | Speed 1494 tokens/sec | Learning rate 0.00079607
Step 3121 | Loss 3.82 | Speed 2055 tokens/sec | Learning rate 0.00079095
Step 3161 | Loss 3.32 | Speed 2085 tokens/sec | Learning rate 0.00078593
Step 3201 | Loss 3.75 | Speed 2111 tokens/sec | Learning rate 0.00078101
Step 3241 | Loss 3.11 | Speed 2141 tokens/sec | Learning rate 0.00077617
Step 3281 | Loss 3.96 | Speed 2170 tokens/sec | Learning rate 0.00077143
Step 3321 | Loss 3.01 | Speed 1998 tokens/sec | Learning rate 0.00076677
Step 3361 | Loss 3.45 | Speed 2084 tokens/sec | Learning rate 0.0007622
Step 3401 | Loss 4.10 | Speed 2154 tokens/sec | Learning rate 0.0007577
Step 3441 | Loss 4.19 | Speed 2162 tokens/sec | Learning rate 0.00075329
Step 3481 | Loss 3.32 | Speed 2135 tokens/sec | Learning rate 0.00074895
Step 3521 | Loss 3.69 | Speed 2089 tokens/sec | Learning rate 0.00074468
Step 3561 | Loss 4.03 | Speed 2104 tokens/sec | Learning rate 0.00074049
Step 3601 | Loss 3.51 | Speed 2044 tokens/sec | Learning rate 0.00073637
Step 3641 | Loss 3.97 | Speed 1827 tokens/sec | Learning rate 0.00073231
Step 3681 | Loss 4.03 | Speed 2174 tokens/sec | Learning rate 0.00072832
Step 3721 | Loss 3.88 | Speed 1996 tokens/sec | Learning rate 0.0007244
Step 3761 | Loss 3.21 | Speed 2020 tokens/sec | Learning rate 0.00072054
Step 3801 | Loss 3.65 | Speed 2165 tokens/sec | Learning rate 0.00071674
Step 3841 | Loss 4.33 | Speed 2111 tokens/sec | Learning rate 0.00071299
Step 3881 | Loss 2.98 | Speed 1989 tokens/sec | Learning rate 0.00070931
Step 3921 | Loss 4.11 | Speed 2197 tokens/sec | Learning rate 0.00070569
Step 3961 | Loss 3.28 | Speed 2047 tokens/sec | Learning rate 0.00070211
Step 4001 | Loss 3.71 | Speed 2136 tokens/sec | Learning rate 0.0006986
Step 4041 | Loss 4.15 | Speed 2087 tokens/sec | Learning rate 0.00069513
Step 4081 | Loss 3.97 | Speed 1968 tokens/sec | Learning rate 0.00069172
Step 4121 | Loss 3.75 | Speed 2240 tokens/sec | Learning rate 0.00068835
Step 4161 | Loss 3.83 | Speed 2153 tokens/sec | Learning rate 0.00068504
Step 4201 | Loss 3.84 | Speed 2229 tokens/sec | Learning rate 0.00068177
Step 4241 | Loss 3.87 | Speed 2250 tokens/sec | Learning rate 0.00067855
Step 4281 | Loss 3.05 | Speed 2289 tokens/sec | Learning rate 0.00067537
Step 4321 | Loss 3.29 | Speed 2200 tokens/sec | Learning rate 0.00067224
Step 4361 | Loss 3.31 | Speed 2187 tokens/sec | Learning rate 0.00066915
Step 4401 | Loss 2.98 | Speed 2196 tokens/sec | Learning rate 0.0006661
Step 4441 | Loss 3.36 | Speed 2116 tokens/sec | Learning rate 0.00066309
Step 4481 | Loss 3.70 | Speed 2215 tokens/sec | Learning rate 0.00066013
Step 4521 | Loss 3.47 | Speed 2224 tokens/sec | Learning rate 0.0006572
Step 4561 | Loss 3.57 | Speed 2153 tokens/sec | Learning rate 0.00065432
Step 4601 | Loss 3.68 | Speed 2188 tokens/sec | Learning rate 0.00065147
Step 4641 | Loss 3.28 | Speed 2125 tokens/sec | Learning rate 0.00064865
Step 4681 | Loss 3.52 | Speed 2078 tokens/sec | Learning rate 0.00064588
Step 4721 | Loss 3.05 | Speed 2136 tokens/sec | Learning rate 0.00064313
Step 4761 | Loss 3.30 | Speed 2135 tokens/sec | Learning rate 0.00064043
Step 4801 | Loss 3.97 | Speed 2052 tokens/sec | Learning rate 0.00063776
Step 4841 | Loss 3.76 | Speed 2283 tokens/sec | Learning rate 0.00063512
Step 4881 | Loss 4.14 | Speed 2153 tokens/sec | Learning rate 0.00063251
Step 4921 | Loss 4.03 | Speed 2163 tokens/sec | Learning rate 0.00062993
Step 4961 | Loss 3.31 | Speed 2166 tokens/sec | Learning rate 0.00062739
Saved dailydialog_local38k8e_step_5000.pt
Saved dailydialog_local38k8e_last.pt
Step 5001 | Loss 2.99 | Speed 943 tokens/sec | Learning rate 0.00062488
Step 5041 | Loss 3.89 | Speed 2234 tokens/sec | Learning rate 0.00062239
Step 5081 | Loss 4.45 | Speed 2300 tokens/sec | Learning rate 0.00061994
Step 5121 | Loss 3.47 | Speed 2212 tokens/sec | Learning rate 0.00061751
Step 5161 | Loss 3.32 | Speed 2250 tokens/sec | Learning rate 0.00061511
Step 5201 | Loss 3.99 | Speed 1976 tokens/sec | Learning rate 0.00061275
Step 5241 | Loss 3.57 | Speed 2134 tokens/sec | Learning rate 0.0006104
Step 5281 | Loss 3.38 | Speed 2090 tokens/sec | Learning rate 0.00060809
Step 5321 | Loss 3.59 | Speed 2156 tokens/sec | Learning rate 0.0006058
Step 5361 | Loss 3.35 | Speed 2251 tokens/sec | Learning rate 0.00060353
Step 5401 | Loss 3.73 | Speed 2311 tokens/sec | Learning rate 0.0006013
Step 5441 | Loss 4.02 | Speed 2125 tokens/sec | Learning rate 0.00059908
Step 5481 | Loss 3.11 | Speed 2200 tokens/sec | Learning rate 0.00059689
Step 5521 | Loss 3.61 | Speed 2235 tokens/sec | Learning rate 0.00059473
Step 5561 | Loss 3.28 | Speed 2167 tokens/sec | Learning rate 0.00059258
Step 5601 | Loss 3.57 | Speed 2136 tokens/sec | Learning rate 0.00059046
Step 5641 | Loss 3.54 | Speed 2087 tokens/sec | Learning rate 0.00058837
Step 5681 | Loss 3.07 | Speed 2082 tokens/sec | Learning rate 0.00058629
Step 5721 | Loss 3.59 | Speed 2233 tokens/sec | Learning rate 0.00058424
Step 5761 | Loss 3.76 | Speed 2169 tokens/sec | Learning rate 0.00058221
Step 5801 | Loss 3.32 | Speed 2231 tokens/sec | Learning rate 0.0005802
Step 5841 | Loss 3.06 | Speed 2117 tokens/sec | Learning rate 0.00057821
Step 5881 | Loss 3.94 | Speed 2232 tokens/sec | Learning rate 0.00057624
Step 5921 | Loss 3.73 | Speed 2094 tokens/sec | Learning rate 0.00057429
Step 5961 | Loss 3.70 | Speed 2309 tokens/sec | Learning rate 0.00057236
Step 6001 | Loss 4.46 | Speed 2194 tokens/sec | Learning rate 0.00057045
Step 6041 | Loss 3.61 | Speed 2168 tokens/sec | Learning rate 0.00056856
Step 6081 | Loss 3.43 | Speed 2064 tokens/sec | Learning rate 0.00056669
Step 6121 | Loss 4.14 | Speed 2211 tokens/sec | Learning rate 0.00056483
Step 6161 | Loss 4.11 | Speed 2022 tokens/sec | Learning rate 0.00056299
Step 6201 | Loss 4.11 | Speed 2227 tokens/sec | Learning rate 0.00056118
Step 6241 | Loss 3.37 | Speed 2207 tokens/sec | Learning rate 0.00055938
Step 6281 | Loss 4.13 | Speed 2112 tokens/sec | Learning rate 0.00055759
Step 6321 | Loss 2.73 | Speed 2067 tokens/sec | Learning rate 0.00055582
Step 6361 | Loss 3.45 | Speed 2185 tokens/sec | Learning rate 0.00055407
Step 6401 | Loss 3.80 | Speed 2143 tokens/sec | Learning rate 0.00055234
Step 6441 | Loss 3.24 | Speed 2074 tokens/sec | Learning rate 0.00055062
Step 6481 | Loss 3.38 | Speed 2133 tokens/sec | Learning rate 0.00054892
Step 6521 | Loss 3.71 | Speed 2274 tokens/sec | Learning rate 0.00054724
Step 6561 | Loss 3.32 | Speed 2196 tokens/sec | Learning rate 0.00054557
Step 6601 | Loss 3.66 | Speed 2182 tokens/sec | Learning rate 0.00054391
Step 6641 | Loss 3.70 | Speed 2087 tokens/sec | Learning rate 0.00054227
Step 6681 | Loss 3.58 | Speed 2178 tokens/sec | Learning rate 0.00054064
Step 6721 | Loss 3.06 | Speed 2201 tokens/sec | Learning rate 0.00053903
Step 6761 | Loss 3.44 | Speed 2145 tokens/sec | Learning rate 0.00053744
Step 6801 | Loss 3.63 | Speed 2165 tokens/sec | Learning rate 0.00053585
Step 6841 | Loss 3.96 | Speed 2099 tokens/sec | Learning rate 0.00053429
Step 6881 | Loss 3.75 | Speed 2365 tokens/sec | Learning rate 0.00053273
Step 6921 | Loss 3.51 | Speed 2118 tokens/sec | Learning rate 0.00053119
Step 6961 | Loss 3.16 | Speed 2241 tokens/sec | Learning rate 0.00052966
Step 7001 | Loss 3.01 | Speed 2163 tokens/sec | Learning rate 0.00052815
Step 7041 | Loss 3.52 | Speed 2257 tokens/sec | Learning rate 0.00052664
Step 7081 | Loss 2.86 | Speed 2178 tokens/sec | Learning rate 0.00052515
Step 7121 | Loss 3.42 | Speed 2084 tokens/sec | Learning rate 0.00052368
Step 7161 | Loss 4.20 | Speed 2334 tokens/sec | Learning rate 0.00052221
Step 7201 | Loss 3.66 | Speed 1989 tokens/sec | Learning rate 0.00052076
Step 7241 | Loss 4.13 | Speed 2277 tokens/sec | Learning rate 0.00051932
Step 7281 | Loss 3.98 | Speed 2253 tokens/sec | Learning rate 0.00051789
Step 7321 | Loss 2.71 | Speed 2174 tokens/sec | Learning rate 0.00051648
Step 7361 | Loss 3.48 | Speed 2205 tokens/sec | Learning rate 0.00051507
Step 7401 | Loss 3.76 | Speed 2234 tokens/sec | Learning rate 0.00051368
Step 7441 | Loss 3.35 | Speed 2097 tokens/sec | Learning rate 0.0005123
Step 7481 | Loss 3.46 | Speed 2179 tokens/sec | Learning rate 0.00051092
Saved dailydialog_local38k8e_step_7500.pt
Saved dailydialog_local38k8e_last.pt
Step 7521 | Loss 3.34 | Speed 1345 tokens/sec | Learning rate 0.00050956
Step 7561 | Loss 3.39 | Speed 2231 tokens/sec | Learning rate 0.00050821
Step 7601 | Loss 3.34 | Speed 2200 tokens/sec | Learning rate 0.00050688
Step 7641 | Loss 3.76 | Speed 2158 tokens/sec | Learning rate 0.00050555
Step 7681 | Loss 3.08 | Speed 2238 tokens/sec | Learning rate 0.00050423
Step 7721 | Loss 3.90 | Speed 2055 tokens/sec | Learning rate 0.00050292
Step 7761 | Loss 3.52 | Speed 2115 tokens/sec | Learning rate 0.00050162
Step 7801 | Loss 3.36 | Speed 2069 tokens/sec | Learning rate 0.00050034
Step 7841 | Loss 3.19 | Speed 2078 tokens/sec | Learning rate 0.00049906
Step 7881 | Loss 3.41 | Speed 2203 tokens/sec | Learning rate 0.00049779
Step 7921 | Loss 3.07 | Speed 2245 tokens/sec | Learning rate 0.00049653
Step 7961 | Loss 3.48 | Speed 2142 tokens/sec | Learning rate 0.00049528
Step 8001 | Loss 3.41 | Speed 2118 tokens/sec | Learning rate 0.00049404
Step 8041 | Loss 3.10 | Speed 2218 tokens/sec | Learning rate 0.00049281
Step 8081 | Loss 3.63 | Speed 2098 tokens/sec | Learning rate 0.00049159
Step 8121 | Loss 3.50 | Speed 2196 tokens/sec | Learning rate 0.00049038
Step 8161 | Loss 3.60 | Speed 2028 tokens/sec | Learning rate 0.00048918
Step 8201 | Loss 3.24 | Speed 2137 tokens/sec | Learning rate 0.00048798
Step 8241 | Loss 3.86 | Speed 2151 tokens/sec | Learning rate 0.0004868
Step 8281 | Loss 3.23 | Speed 1999 tokens/sec | Learning rate 0.00048562
Step 8321 | Loss 3.48 | Speed 2231 tokens/sec | Learning rate 0.00048445
Step 8361 | Loss 3.97 | Speed 2076 tokens/sec | Learning rate 0.00048329
Step 8401 | Loss 3.76 | Speed 2131 tokens/sec | Learning rate 0.00048214
Step 8441 | Loss 3.13 | Speed 2207 tokens/sec | Learning rate 0.000481
Step 8481 | Loss 3.47 | Speed 2209 tokens/sec | Learning rate 0.00047986
Step 8521 | Loss 3.91 | Speed 2197 tokens/sec | Learning rate 0.00047873
Step 8561 | Loss 3.28 | Speed 2166 tokens/sec | Learning rate 0.00047761
Step 8601 | Loss 3.79 | Speed 2103 tokens/sec | Learning rate 0.0004765
Step 8641 | Loss 3.86 | Speed 2318 tokens/sec | Learning rate 0.0004754
Step 8681 | Loss 3.95 | Speed 2241 tokens/sec | Learning rate 0.0004743
Step 8721 | Loss 3.41 | Speed 2114 tokens/sec | Learning rate 0.00047321
Step 8761 | Loss 3.34 | Speed 2185 tokens/sec | Learning rate 0.00047213
Step 8801 | Loss 3.83 | Speed 2027 tokens/sec | Learning rate 0.00047106
Step 8841 | Loss 3.53 | Speed 2248 tokens/sec | Learning rate 0.00046999
Step 8881 | Loss 3.69 | Speed 2195 tokens/sec | Learning rate 0.00046893
Step 8921 | Loss 3.18 | Speed 2118 tokens/sec | Learning rate 0.00046788
Step 8961 | Loss 3.43 | Speed 2035 tokens/sec | Learning rate 0.00046683
Step 9001 | Loss 2.99 | Speed 2285 tokens/sec | Learning rate 0.0004658
Step 9041 | Loss 3.57 | Speed 2283 tokens/sec | Learning rate 0.00046476
Step 9081 | Loss 3.91 | Speed 2126 tokens/sec | Learning rate 0.00046374
Step 9121 | Loss 3.23 | Speed 2139 tokens/sec | Learning rate 0.00046272
Step 9161 | Loss 3.56 | Speed 2260 tokens/sec | Learning rate 0.00046171
Step 9201 | Loss 3.69 | Speed 2132 tokens/sec | Learning rate 0.00046071
Step 9241 | Loss 3.38 | Speed 2131 tokens/sec | Learning rate 0.00045971
Step 9281 | Loss 3.21 | Speed 2121 tokens/sec | Learning rate 0.00045872
Step 9321 | Loss 2.75 | Speed 2243 tokens/sec | Learning rate 0.00045773
Step 9361 | Loss 3.30 | Speed 2047 tokens/sec | Learning rate 0.00045675
Step 9401 | Loss 3.49 | Speed 2164 tokens/sec | Learning rate 0.00045578
Step 9441 | Loss 3.72 | Speed 2020 tokens/sec | Learning rate 0.00045481
Step 9481 | Loss 3.49 | Speed 2151 tokens/sec | Learning rate 0.00045385
| ID | GPU | MEM |
------------------
|  0 | 93% | 25% |
Epoch 0 Validation ====
Validation loss: 3.4006
[███░░░░░░░░░░░░░░░░░░░░░░░░░]  epoch 1/8 complete
  train_loss=3.8851  val_loss=3.4006  steps=9507  tokens_seen=1148359

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_0.pt
Saved dailydialog_local38k8e_last.pt
Epoch 1 Training ====
Step 1 | Loss 3.46 | Speed 2782 tokens/sec | Learning rate 0.00045321
Step 41 | Loss 3.75 | Speed 2457 tokens/sec | Learning rate 0.00045226
Step 81 | Loss 3.23 | Speed 2261 tokens/sec | Learning rate 0.00045131
Step 121 | Loss 3.07 | Speed 2259 tokens/sec | Learning rate 0.00045038
Step 161 | Loss 3.74 | Speed 2284 tokens/sec | Learning rate 0.00044944
Step 201 | Loss 3.38 | Speed 2168 tokens/sec | Learning rate 0.00044852
Step 241 | Loss 3.20 | Speed 2217 tokens/sec | Learning rate 0.00044759
Step 281 | Loss 3.60 | Speed 2171 tokens/sec | Learning rate 0.00044668
Step 321 | Loss 3.47 | Speed 2113 tokens/sec | Learning rate 0.00044577
Step 361 | Loss 3.57 | Speed 2219 tokens/sec | Learning rate 0.00044487
Step 401 | Loss 3.05 | Speed 2091 tokens/sec | Learning rate 0.00044397
Step 441 | Loss 3.26 | Speed 2141 tokens/sec | Learning rate 0.00044307
Step 481 | Loss 2.93 | Speed 2011 tokens/sec | Learning rate 0.00044219
Saved dailydialog_local38k8e_step_10000.pt
Saved dailydialog_local38k8e_last.pt
Step 521 | Loss 3.55 | Speed 1233 tokens/sec | Learning rate 0.0004413
Step 561 | Loss 3.62 | Speed 2112 tokens/sec | Learning rate 0.00044042
Step 601 | Loss 3.16 | Speed 2033 tokens/sec | Learning rate 0.00043955
Step 641 | Loss 3.50 | Speed 2125 tokens/sec | Learning rate 0.00043869
Step 681 | Loss 3.36 | Speed 2213 tokens/sec | Learning rate 0.00043782
Step 721 | Loss 3.34 | Speed 1981 tokens/sec | Learning rate 0.00043697
Step 761 | Loss 3.31 | Speed 2146 tokens/sec | Learning rate 0.00043611
Step 801 | Loss 3.70 | Speed 2011 tokens/sec | Learning rate 0.00043527
Step 841 | Loss 3.13 | Speed 2103 tokens/sec | Learning rate 0.00043443
Step 881 | Loss 3.83 | Speed 2181 tokens/sec | Learning rate 0.00043359
Step 921 | Loss 2.93 | Speed 2255 tokens/sec | Learning rate 0.00043276
Step 961 | Loss 3.78 | Speed 2256 tokens/sec | Learning rate 0.00043193
Step 1001 | Loss 3.37 | Speed 2157 tokens/sec | Learning rate 0.00043111
Step 1041 | Loss 3.28 | Speed 2097 tokens/sec | Learning rate 0.00043029
Step 1081 | Loss 3.43 | Speed 2167 tokens/sec | Learning rate 0.00042947
Step 1121 | Loss 3.40 | Speed 2187 tokens/sec | Learning rate 0.00042867
Step 1161 | Loss 3.07 | Speed 2232 tokens/sec | Learning rate 0.00042786
Step 1201 | Loss 3.39 | Speed 2042 tokens/sec | Learning rate 0.00042706
Step 1241 | Loss 3.78 | Speed 2014 tokens/sec | Learning rate 0.00042627
Step 1281 | Loss 3.04 | Speed 2199 tokens/sec | Learning rate 0.00042548
Step 1321 | Loss 3.12 | Speed 2150 tokens/sec | Learning rate 0.00042469
Step 1361 | Loss 3.71 | Speed 2147 tokens/sec | Learning rate 0.00042391
Step 1401 | Loss 3.43 | Speed 2225 tokens/sec | Learning rate 0.00042313
Step 1441 | Loss 2.52 | Speed 2093 tokens/sec | Learning rate 0.00042236
Step 1481 | Loss 3.36 | Speed 2134 tokens/sec | Learning rate 0.00042159
Step 1521 | Loss 3.02 | Speed 2057 tokens/sec | Learning rate 0.00042082
Step 1561 | Loss 3.33 | Speed 1992 tokens/sec | Learning rate 0.00042006
Step 1601 | Loss 3.34 | Speed 2134 tokens/sec | Learning rate 0.0004193
Step 1641 | Loss 3.42 | Speed 2091 tokens/sec | Learning rate 0.00041855
Step 1681 | Loss 3.51 | Speed 2032 tokens/sec | Learning rate 0.0004178
Step 1721 | Loss 3.66 | Speed 2181 tokens/sec | Learning rate 0.00041706
Step 1761 | Loss 3.18 | Speed 2115 tokens/sec | Learning rate 0.00041632
Step 1801 | Loss 2.82 | Speed 2070 tokens/sec | Learning rate 0.00041558
Step 1841 | Loss 3.44 | Speed 2074 tokens/sec | Learning rate 0.00041485
Step 1881 | Loss 3.02 | Speed 2009 tokens/sec | Learning rate 0.00041412
Step 1921 | Loss 4.04 | Speed 2138 tokens/sec | Learning rate 0.00041339
Step 1961 | Loss 3.72 | Speed 2084 tokens/sec | Learning rate 0.00041267
Step 2001 | Loss 3.16 | Speed 2055 tokens/sec | Learning rate 0.00041195
Step 2041 | Loss 3.22 | Speed 2189 tokens/sec | Learning rate 0.00041124
Step 2081 | Loss 3.37 | Speed 2061 tokens/sec | Learning rate 0.00041053
Step 2121 | Loss 3.02 | Speed 1944 tokens/sec | Learning rate 0.00040982
Step 2161 | Loss 3.45 | Speed 2126 tokens/sec | Learning rate 0.00040912
Step 2201 | Loss 3.60 | Speed 2091 tokens/sec | Learning rate 0.00040842
Step 2241 | Loss 3.09 | Speed 1948 tokens/sec | Learning rate 0.00040772
Step 2281 | Loss 3.23 | Speed 2033 tokens/sec | Learning rate 0.00040703
Step 2321 | Loss 3.30 | Speed 2028 tokens/sec | Learning rate 0.00040634
Step 2361 | Loss 3.11 | Speed 2210 tokens/sec | Learning rate 0.00040566
Step 2401 | Loss 3.75 | Speed 2141 tokens/sec | Learning rate 0.00040497
Step 2441 | Loss 3.51 | Speed 2149 tokens/sec | Learning rate 0.0004043
Step 2481 | Loss 3.50 | Speed 2180 tokens/sec | Learning rate 0.00040362
Step 2521 | Loss 3.53 | Speed 1984 tokens/sec | Learning rate 0.00040295
Step 2561 | Loss 3.53 | Speed 2071 tokens/sec | Learning rate 0.00040228
Step 2601 | Loss 3.27 | Speed 2141 tokens/sec | Learning rate 0.00040162
Step 2641 | Loss 3.73 | Speed 2238 tokens/sec | Learning rate 0.00040095
Step 2681 | Loss 3.24 | Speed 2050 tokens/sec | Learning rate 0.0004003
Step 2721 | Loss 3.33 | Speed 2033 tokens/sec | Learning rate 0.00039964
Step 2761 | Loss 2.96 | Speed 2119 tokens/sec | Learning rate 0.00039899
Step 2801 | Loss 3.03 | Speed 2040 tokens/sec | Learning rate 0.00039834
Step 2841 | Loss 3.06 | Speed 2114 tokens/sec | Learning rate 0.00039769
Step 2881 | Loss 3.37 | Speed 2080 tokens/sec | Learning rate 0.00039705
Step 2921 | Loss 3.21 | Speed 2078 tokens/sec | Learning rate 0.00039641
Step 2961 | Loss 3.21 | Speed 2168 tokens/sec | Learning rate 0.00039578
Saved dailydialog_local38k8e_step_12500.pt
Saved dailydialog_local38k8e_last.pt
Step 3001 | Loss 2.82 | Speed 1221 tokens/sec | Learning rate 0.00039514
Step 3041 | Loss 2.96 | Speed 2132 tokens/sec | Learning rate 0.00039451
Step 3081 | Loss 3.61 | Speed 2048 tokens/sec | Learning rate 0.00039388
Step 3121 | Loss 3.58 | Speed 2165 tokens/sec | Learning rate 0.00039326
Step 3161 | Loss 2.99 | Speed 2100 tokens/sec | Learning rate 0.00039264
Step 3201 | Loss 2.99 | Speed 2017 tokens/sec | Learning rate 0.00039202
Step 3241 | Loss 3.20 | Speed 2008 tokens/sec | Learning rate 0.00039141
Step 3281 | Loss 2.84 | Speed 2017 tokens/sec | Learning rate 0.00039079
Step 3321 | Loss 3.57 | Speed 2012 tokens/sec | Learning rate 0.00039018
Step 3361 | Loss 3.27 | Speed 2116 tokens/sec | Learning rate 0.00038958
Step 3401 | Loss 3.27 | Speed 1967 tokens/sec | Learning rate 0.00038897
Step 3441 | Loss 3.84 | Speed 1910 tokens/sec | Learning rate 0.00038837
Step 3481 | Loss 3.25 | Speed 2002 tokens/sec | Learning rate 0.00038777
Step 3521 | Loss 3.49 | Speed 1961 tokens/sec | Learning rate 0.00038718
Step 3561 | Loss 3.14 | Speed 2112 tokens/sec | Learning rate 0.00038658
Step 3601 | Loss 3.79 | Speed 2095 tokens/sec | Learning rate 0.00038599
Step 3641 | Loss 2.72 | Speed 2082 tokens/sec | Learning rate 0.00038541
Step 3681 | Loss 3.86 | Speed 2046 tokens/sec | Learning rate 0.00038482
Step 3721 | Loss 3.53 | Speed 2135 tokens/sec | Learning rate 0.00038424
Step 3761 | Loss 3.77 | Speed 2136 tokens/sec | Learning rate 0.00038366
Step 3801 | Loss 3.75 | Speed 1892 tokens/sec | Learning rate 0.00038308
Step 3841 | Loss 3.54 | Speed 2078 tokens/sec | Learning rate 0.00038251
Step 3881 | Loss 3.79 | Speed 2163 tokens/sec | Learning rate 0.00038194
Step 3921 | Loss 2.88 | Speed 2047 tokens/sec | Learning rate 0.00038137
Step 3961 | Loss 3.21 | Speed 2224 tokens/sec | Learning rate 0.0003808
Step 4001 | Loss 3.35 | Speed 2201 tokens/sec | Learning rate 0.00038024
Step 4041 | Loss 3.28 | Speed 2252 tokens/sec | Learning rate 0.00037967
Step 4081 | Loss 4.43 | Speed 2311 tokens/sec | Learning rate 0.00037912
Step 4121 | Loss 3.46 | Speed 2232 tokens/sec | Learning rate 0.00037856
Step 4161 | Loss 3.59 | Speed 2066 tokens/sec | Learning rate 0.000378
Step 4201 | Loss 3.22 | Speed 2144 tokens/sec | Learning rate 0.00037745
Step 4241 | Loss 3.50 | Speed 2146 tokens/sec | Learning rate 0.0003769
Step 4281 | Loss 3.41 | Speed 2226 tokens/sec | Learning rate 0.00037636
Step 4321 | Loss 2.80 | Speed 2073 tokens/sec | Learning rate 0.00037581
Step 4361 | Loss 2.64 | Speed 2042 tokens/sec | Learning rate 0.00037527
Step 4401 | Loss 3.01 | Speed 2005 tokens/sec | Learning rate 0.00037473
Step 4441 | Loss 3.19 | Speed 2188 tokens/sec | Learning rate 0.00037419
Step 4481 | Loss 2.80 | Speed 2023 tokens/sec | Learning rate 0.00037366
Step 4521 | Loss 3.40 | Speed 2014 tokens/sec | Learning rate 0.00037312
Step 4561 | Loss 2.79 | Speed 2105 tokens/sec | Learning rate 0.00037259
Step 4601 | Loss 3.36 | Speed 2098 tokens/sec | Learning rate 0.00037206
Step 4641 | Loss 3.64 | Speed 2107 tokens/sec | Learning rate 0.00037154
Step 4681 | Loss 2.99 | Speed 2109 tokens/sec | Learning rate 0.00037101
Step 4721 | Loss 3.36 | Speed 2083 tokens/sec | Learning rate 0.00037049
Step 4761 | Loss 3.28 | Speed 2138 tokens/sec | Learning rate 0.00036997
Step 4801 | Loss 3.82 | Speed 2174 tokens/sec | Learning rate 0.00036945
Step 4841 | Loss 3.27 | Speed 1966 tokens/sec | Learning rate 0.00036894
Step 4881 | Loss 3.42 | Speed 2033 tokens/sec | Learning rate 0.00036843
Step 4921 | Loss 3.41 | Speed 2129 tokens/sec | Learning rate 0.00036791
Step 4961 | Loss 3.19 | Speed 2123 tokens/sec | Learning rate 0.00036741
Step 5001 | Loss 3.14 | Speed 2266 tokens/sec | Learning rate 0.0003669
Step 5041 | Loss 2.90 | Speed 2293 tokens/sec | Learning rate 0.00036639
Step 5081 | Loss 3.14 | Speed 2211 tokens/sec | Learning rate 0.00036589
Step 5121 | Loss 3.14 | Speed 2045 tokens/sec | Learning rate 0.00036539
Step 5161 | Loss 3.82 | Speed 1999 tokens/sec | Learning rate 0.00036489
Step 5201 | Loss 3.75 | Speed 2142 tokens/sec | Learning rate 0.0003644
Step 5241 | Loss 3.25 | Speed 2301 tokens/sec | Learning rate 0.0003639
Step 5281 | Loss 3.26 | Speed 2155 tokens/sec | Learning rate 0.00036341
Step 5321 | Loss 3.85 | Speed 2250 tokens/sec | Learning rate 0.00036292
Step 5361 | Loss 3.55 | Speed 2109 tokens/sec | Learning rate 0.00036243
Step 5401 | Loss 3.67 | Speed 2129 tokens/sec | Learning rate 0.00036194
Step 5441 | Loss 3.63 | Speed 2226 tokens/sec | Learning rate 0.00036146
Step 5481 | Loss 3.67 | Speed 2188 tokens/sec | Learning rate 0.00036098
Saved dailydialog_local38k8e_step_15000.pt
Saved dailydialog_local38k8e_last.pt
Step 5521 | Loss 2.64 | Speed 1085 tokens/sec | Learning rate 0.0003605
Step 5561 | Loss 3.18 | Speed 2023 tokens/sec | Learning rate 0.00036002
Step 5601 | Loss 3.80 | Speed 2254 tokens/sec | Learning rate 0.00035954
Step 5641 | Loss 3.35 | Speed 2038 tokens/sec | Learning rate 0.00035906
Step 5681 | Loss 3.02 | Speed 2269 tokens/sec | Learning rate 0.00035859
Step 5721 | Loss 3.22 | Speed 2140 tokens/sec | Learning rate 0.00035812
Step 5761 | Loss 3.24 | Speed 1935 tokens/sec | Learning rate 0.00035765
Step 5801 | Loss 3.21 | Speed 2021 tokens/sec | Learning rate 0.00035718
Step 5841 | Loss 3.32 | Speed 1962 tokens/sec | Learning rate 0.00035672
Step 5881 | Loss 3.22 | Speed 2037 tokens/sec | Learning rate 0.00035625
Step 5921 | Loss 3.12 | Speed 2123 tokens/sec | Learning rate 0.00035579
Step 5961 | Loss 3.63 | Speed 2146 tokens/sec | Learning rate 0.00035533
Step 6001 | Loss 3.67 | Speed 2070 tokens/sec | Learning rate 0.00035487
Step 6041 | Loss 2.92 | Speed 2005 tokens/sec | Learning rate 0.00035442
Step 6081 | Loss 3.30 | Speed 2021 tokens/sec | Learning rate 0.00035396
Step 6121 | Loss 3.77 | Speed 2077 tokens/sec | Learning rate 0.00035351
Step 6161 | Loss 2.98 | Speed 2103 tokens/sec | Learning rate 0.00035306
Step 6201 | Loss 3.43 | Speed 2015 tokens/sec | Learning rate 0.00035261
Step 6241 | Loss 3.68 | Speed 2202 tokens/sec | Learning rate 0.00035216
Step 6281 | Loss 3.16 | Speed 2173 tokens/sec | Learning rate 0.00035171
Step 6321 | Loss 3.33 | Speed 2167 tokens/sec | Learning rate 0.00035127
Step 6361 | Loss 3.25 | Speed 2156 tokens/sec | Learning rate 0.00035082
Step 6401 | Loss 3.09 | Speed 2269 tokens/sec | Learning rate 0.00035038
Step 6441 | Loss 3.03 | Speed 2166 tokens/sec | Learning rate 0.00034994
Step 6481 | Loss 3.44 | Speed 2065 tokens/sec | Learning rate 0.00034951
Step 6521 | Loss 3.84 | Speed 2220 tokens/sec | Learning rate 0.00034907
Step 6561 | Loss 3.44 | Speed 2207 tokens/sec | Learning rate 0.00034863
Step 6601 | Loss 3.95 | Speed 2196 tokens/sec | Learning rate 0.0003482
Step 6641 | Loss 3.13 | Speed 2137 tokens/sec | Learning rate 0.00034777
Step 6681 | Loss 4.14 | Speed 2075 tokens/sec | Learning rate 0.00034734
Step 6721 | Loss 3.74 | Speed 2148 tokens/sec | Learning rate 0.00034691
Step 6761 | Loss 3.38 | Speed 2250 tokens/sec | Learning rate 0.00034649
Step 6801 | Loss 2.88 | Speed 2000 tokens/sec | Learning rate 0.00034606
Step 6841 | Loss 2.84 | Speed 2073 tokens/sec | Learning rate 0.00034564
Step 6881 | Loss 3.74 | Speed 2061 tokens/sec | Learning rate 0.00034521
Step 6921 | Loss 2.83 | Speed 2139 tokens/sec | Learning rate 0.00034479
Step 6961 | Loss 4.11 | Speed 2172 tokens/sec | Learning rate 0.00034437
Step 7001 | Loss 3.60 | Speed 2128 tokens/sec | Learning rate 0.00034396
Step 7041 | Loss 3.21 | Speed 2180 tokens/sec | Learning rate 0.00034354
Step 7081 | Loss 2.74 | Speed 2075 tokens/sec | Learning rate 0.00034313
Step 7121 | Loss 3.17 | Speed 2204 tokens/sec | Learning rate 0.00034271
Step 7161 | Loss 3.61 | Speed 2010 tokens/sec | Learning rate 0.0003423
Step 7201 | Loss 2.52 | Speed 2100 tokens/sec | Learning rate 0.00034189
Step 7241 | Loss 2.90 | Speed 2062 tokens/sec | Learning rate 0.00034148
Step 7281 | Loss 3.61 | Speed 2107 tokens/sec | Learning rate 0.00034108
Step 7321 | Loss 3.81 | Speed 2152 tokens/sec | Learning rate 0.00034067
Step 7361 | Loss 3.18 | Speed 2185 tokens/sec | Learning rate 0.00034027
Step 7401 | Loss 2.87 | Speed 2209 tokens/sec | Learning rate 0.00033986
Step 7441 | Loss 3.67 | Speed 2090 tokens/sec | Learning rate 0.00033946
Step 7481 | Loss 3.82 | Speed 2207 tokens/sec | Learning rate 0.00033906
Step 7521 | Loss 3.26 | Speed 2090 tokens/sec | Learning rate 0.00033867
Step 7561 | Loss 3.23 | Speed 2093 tokens/sec | Learning rate 0.00033827
Step 7601 | Loss 3.34 | Speed 1998 tokens/sec | Learning rate 0.00033787
Step 7641 | Loss 2.79 | Speed 2205 tokens/sec | Learning rate 0.00033748
Step 7681 | Loss 3.59 | Speed 2171 tokens/sec | Learning rate 0.00033709
Step 7721 | Loss 3.49 | Speed 2174 tokens/sec | Learning rate 0.00033669
Step 7761 | Loss 3.24 | Speed 2121 tokens/sec | Learning rate 0.0003363
Step 7801 | Loss 3.32 | Speed 2193 tokens/sec | Learning rate 0.00033591
Step 7841 | Loss 3.02 | Speed 2032 tokens/sec | Learning rate 0.00033553
Step 7881 | Loss 3.77 | Speed 2032 tokens/sec | Learning rate 0.00033514
Step 7921 | Loss 3.16 | Speed 2167 tokens/sec | Learning rate 0.00033476
Step 7961 | Loss 3.11 | Speed 2065 tokens/sec | Learning rate 0.00033437
Saved dailydialog_local38k8e_step_17500.pt
Saved dailydialog_local38k8e_last.pt
Step 8001 | Loss 3.56 | Speed 1245 tokens/sec | Learning rate 0.00033399
Step 8041 | Loss 3.18 | Speed 2092 tokens/sec | Learning rate 0.00033361
Step 8081 | Loss 3.63 | Speed 2125 tokens/sec | Learning rate 0.00033323
Step 8121 | Loss 3.68 | Speed 2183 tokens/sec | Learning rate 0.00033285
Step 8161 | Loss 4.21 | Speed 2174 tokens/sec | Learning rate 0.00033248
Step 8201 | Loss 3.46 | Speed 1994 tokens/sec | Learning rate 0.0003321
Step 8241 | Loss 3.06 | Speed 2127 tokens/sec | Learning rate 0.00033172
Step 8281 | Loss 3.15 | Speed 2083 tokens/sec | Learning rate 0.00033135
Step 8321 | Loss 3.33 | Speed 2087 tokens/sec | Learning rate 0.00033098
Step 8361 | Loss 3.16 | Speed 2092 tokens/sec | Learning rate 0.00033061
Step 8401 | Loss 3.68 | Speed 2232 tokens/sec | Learning rate 0.00033024
Step 8441 | Loss 3.43 | Speed 2099 tokens/sec | Learning rate 0.00032987
Step 8481 | Loss 3.86 | Speed 1964 tokens/sec | Learning rate 0.0003295
Step 8521 | Loss 3.13 | Speed 2102 tokens/sec | Learning rate 0.00032914
Step 8561 | Loss 2.86 | Speed 2048 tokens/sec | Learning rate 0.00032877
Step 8601 | Loss 3.40 | Speed 2166 tokens/sec | Learning rate 0.00032841
Step 8641 | Loss 3.16 | Speed 2126 tokens/sec | Learning rate 0.00032805
Step 8681 | Loss 2.72 | Speed 2060 tokens/sec | Learning rate 0.00032769
Step 8721 | Loss 3.47 | Speed 2185 tokens/sec | Learning rate 0.00032733
Step 8761 | Loss 3.06 | Speed 2042 tokens/sec | Learning rate 0.00032697
Step 8801 | Loss 3.35 | Speed 2107 tokens/sec | Learning rate 0.00032661
Step 8841 | Loss 3.64 | Speed 1953 tokens/sec | Learning rate 0.00032626
Step 8881 | Loss 3.15 | Speed 2104 tokens/sec | Learning rate 0.0003259
Step 8921 | Loss 2.97 | Speed 1761 tokens/sec | Learning rate 0.00032555
Step 8961 | Loss 3.51 | Speed 2047 tokens/sec | Learning rate 0.00032519
Step 9001 | Loss 2.42 | Speed 2056 tokens/sec | Learning rate 0.00032484
Step 9041 | Loss 3.43 | Speed 1950 tokens/sec | Learning rate 0.00032449
Step 9081 | Loss 2.72 | Speed 1962 tokens/sec | Learning rate 0.00032414
Step 9121 | Loss 3.63 | Speed 1921 tokens/sec | Learning rate 0.0003238
Step 9161 | Loss 3.30 | Speed 1882 tokens/sec | Learning rate 0.00032345
Step 9201 | Loss 3.07 | Speed 1816 tokens/sec | Learning rate 0.0003231
Step 9241 | Loss 3.44 | Speed 1536 tokens/sec | Learning rate 0.00032276
Step 9281 | Loss 3.44 | Speed 2038 tokens/sec | Learning rate 0.00032241
Step 9321 | Loss 3.26 | Speed 2084 tokens/sec | Learning rate 0.00032207
Step 9361 | Loss 3.74 | Speed 2197 tokens/sec | Learning rate 0.00032173
Step 9401 | Loss 3.93 | Speed 2231 tokens/sec | Learning rate 0.00032139
Step 9441 | Loss 3.29 | Speed 2187 tokens/sec | Learning rate 0.00032105
Step 9481 | Loss 2.94 | Speed 2227 tokens/sec | Learning rate 0.00032071
| ID | GPU | MEM |
------------------
|  0 | 89% | 27% |
Epoch 1 Validation ====
Validation loss: 3.2482
[███████░░░░░░░░░░░░░░░░░░░░░]  epoch 2/8 complete
  train_loss=3.3696  val_loss=3.2482  steps=19014  tokens_seen=2296718

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_1.pt
Saved dailydialog_local38k8e_last.pt
Epoch 2 Training ====
Step 1 | Loss 3.23 | Speed 2185 tokens/sec | Learning rate 0.00032048
Step 41 | Loss 3.01 | Speed 2125 tokens/sec | Learning rate 0.00032015
Step 81 | Loss 3.26 | Speed 2167 tokens/sec | Learning rate 0.00031981
Step 121 | Loss 3.14 | Speed 1991 tokens/sec | Learning rate 0.00031948
Step 161 | Loss 3.25 | Speed 2084 tokens/sec | Learning rate 0.00031914
Step 201 | Loss 3.58 | Speed 1944 tokens/sec | Learning rate 0.00031881
Step 241 | Loss 2.82 | Speed 2125 tokens/sec | Learning rate 0.00031848
Step 281 | Loss 3.11 | Speed 2184 tokens/sec | Learning rate 0.00031815
Step 321 | Loss 2.61 | Speed 2088 tokens/sec | Learning rate 0.00031782
Step 361 | Loss 2.61 | Speed 1963 tokens/sec | Learning rate 0.00031749
Step 401 | Loss 2.86 | Speed 2053 tokens/sec | Learning rate 0.00031716
Step 441 | Loss 3.69 | Speed 2150 tokens/sec | Learning rate 0.00031684
Step 481 | Loss 3.32 | Speed 2089 tokens/sec | Learning rate 0.00031651
Step 521 | Loss 3.57 | Speed 2137 tokens/sec | Learning rate 0.00031619
Step 561 | Loss 3.25 | Speed 1957 tokens/sec | Learning rate 0.00031587
Step 601 | Loss 2.68 | Speed 2069 tokens/sec | Learning rate 0.00031554
Step 641 | Loss 2.42 | Speed 2085 tokens/sec | Learning rate 0.00031522
Step 681 | Loss 3.19 | Speed 2159 tokens/sec | Learning rate 0.0003149
Step 721 | Loss 3.50 | Speed 2097 tokens/sec | Learning rate 0.00031458
Step 761 | Loss 3.58 | Speed 2133 tokens/sec | Learning rate 0.00031426
Step 801 | Loss 3.23 | Speed 2184 tokens/sec | Learning rate 0.00031395
Step 841 | Loss 3.61 | Speed 1990 tokens/sec | Learning rate 0.00031363
Step 881 | Loss 2.37 | Speed 2161 tokens/sec | Learning rate 0.00031332
Step 921 | Loss 3.22 | Speed 1987 tokens/sec | Learning rate 0.000313
Step 961 | Loss 3.09 | Speed 2088 tokens/sec | Learning rate 0.00031269
Saved dailydialog_local38k8e_step_20000.pt
Saved dailydialog_local38k8e_last.pt
Step 1001 | Loss 3.15 | Speed 1339 tokens/sec | Learning rate 0.00031238
Step 1041 | Loss 3.24 | Speed 2109 tokens/sec | Learning rate 0.00031206
Step 1081 | Loss 2.68 | Speed 2103 tokens/sec | Learning rate 0.00031175
Step 1121 | Loss 3.20 | Speed 2086 tokens/sec | Learning rate 0.00031144
Step 1161 | Loss 2.70 | Speed 2095 tokens/sec | Learning rate 0.00031113
Step 1201 | Loss 2.69 | Speed 2049 tokens/sec | Learning rate 0.00031083
Step 1241 | Loss 3.75 | Speed 2164 tokens/sec | Learning rate 0.00031052
Step 1281 | Loss 3.25 | Speed 2099 tokens/sec | Learning rate 0.00031021
Step 1321 | Loss 2.56 | Speed 2119 tokens/sec | Learning rate 0.00030991
Step 1361 | Loss 2.92 | Speed 2330 tokens/sec | Learning rate 0.0003096
Step 1401 | Loss 2.88 | Speed 2039 tokens/sec | Learning rate 0.0003093
Step 1441 | Loss 2.87 | Speed 2187 tokens/sec | Learning rate 0.000309
Step 1481 | Loss 3.45 | Speed 2260 tokens/sec | Learning rate 0.0003087
Step 1521 | Loss 3.23 | Speed 2100 tokens/sec | Learning rate 0.00030839
Step 1561 | Loss 3.51 | Speed 2216 tokens/sec | Learning rate 0.00030809
Step 1601 | Loss 3.73 | Speed 2078 tokens/sec | Learning rate 0.0003078
Step 1641 | Loss 3.27 | Speed 2028 tokens/sec | Learning rate 0.0003075
Step 1681 | Loss 3.29 | Speed 2097 tokens/sec | Learning rate 0.0003072
Step 1721 | Loss 2.98 | Speed 2103 tokens/sec | Learning rate 0.0003069
Step 1761 | Loss 2.87 | Speed 2000 tokens/sec | Learning rate 0.00030661
Step 1801 | Loss 2.67 | Speed 2108 tokens/sec | Learning rate 0.00030631
Step 1841 | Loss 3.00 | Speed 1893 tokens/sec | Learning rate 0.00030602
Step 1881 | Loss 3.06 | Speed 1855 tokens/sec | Learning rate 0.00030573
Step 1921 | Loss 3.23 | Speed 2111 tokens/sec | Learning rate 0.00030543
Step 1961 | Loss 3.10 | Speed 2224 tokens/sec | Learning rate 0.00030514
Step 2001 | Loss 3.39 | Speed 2025 tokens/sec | Learning rate 0.00030485
Step 2041 | Loss 3.12 | Speed 2163 tokens/sec | Learning rate 0.00030456
Step 2081 | Loss 3.31 | Speed 1990 tokens/sec | Learning rate 0.00030427
Step 2121 | Loss 3.27 | Speed 2040 tokens/sec | Learning rate 0.00030399
Step 2161 | Loss 3.52 | Speed 2187 tokens/sec | Learning rate 0.0003037
Step 2201 | Loss 2.58 | Speed 2091 tokens/sec | Learning rate 0.00030341
Step 2241 | Loss 3.36 | Speed 2190 tokens/sec | Learning rate 0.00030313
Step 2281 | Loss 3.10 | Speed 2054 tokens/sec | Learning rate 0.00030284
Step 2321 | Loss 2.95 | Speed 2060 tokens/sec | Learning rate 0.00030256
Step 2361 | Loss 3.48 | Speed 2139 tokens/sec | Learning rate 0.00030227
Step 2401 | Loss 3.28 | Speed 2080 tokens/sec | Learning rate 0.00030199
Step 2441 | Loss 3.12 | Speed 2057 tokens/sec | Learning rate 0.00030171
Step 2481 | Loss 2.96 | Speed 2164 tokens/sec | Learning rate 0.00030143
Step 2521 | Loss 3.62 | Speed 2170 tokens/sec | Learning rate 0.00030115
Step 2561 | Loss 3.05 | Speed 1990 tokens/sec | Learning rate 0.00030087
Step 2601 | Loss 3.25 | Speed 2259 tokens/sec | Learning rate 0.00030059
Step 2641 | Loss 3.10 | Speed 2209 tokens/sec | Learning rate 0.00030031
Step 2681 | Loss 3.58 | Speed 2338 tokens/sec | Learning rate 0.00030004
Step 2721 | Loss 2.97 | Speed 1988 tokens/sec | Learning rate 0.00029976
Step 2761 | Loss 3.33 | Speed 2242 tokens/sec | Learning rate 0.00029949
Step 2801 | Loss 3.00 | Speed 2015 tokens/sec | Learning rate 0.00029921
Step 2841 | Loss 3.40 | Speed 2117 tokens/sec | Learning rate 0.00029894
Step 2881 | Loss 2.98 | Speed 2162 tokens/sec | Learning rate 0.00029866
Step 2921 | Loss 3.90 | Speed 2029 tokens/sec | Learning rate 0.00029839
Step 2961 | Loss 3.26 | Speed 2227 tokens/sec | Learning rate 0.00029812
Step 3001 | Loss 3.45 | Speed 2257 tokens/sec | Learning rate 0.00029785
Step 3041 | Loss 3.38 | Speed 2051 tokens/sec | Learning rate 0.00029758
Step 3081 | Loss 3.10 | Speed 2043 tokens/sec | Learning rate 0.00029731
Step 3121 | Loss 3.04 | Speed 2176 tokens/sec | Learning rate 0.00029704
Step 3161 | Loss 2.96 | Speed 2095 tokens/sec | Learning rate 0.00029677
Step 3201 | Loss 3.19 | Speed 2143 tokens/sec | Learning rate 0.00029651
Step 3241 | Loss 2.86 | Speed 2043 tokens/sec | Learning rate 0.00029624
Step 3281 | Loss 3.45 | Speed 2087 tokens/sec | Learning rate 0.00029597
Step 3321 | Loss 3.46 | Speed 2075 tokens/sec | Learning rate 0.00029571
Step 3361 | Loss 2.82 | Speed 2115 tokens/sec | Learning rate 0.00029544
Step 3401 | Loss 2.88 | Speed 1946 tokens/sec | Learning rate 0.00029518
Step 3441 | Loss 2.93 | Speed 2049 tokens/sec | Learning rate 0.00029492
Step 3481 | Loss 3.61 | Speed 2148 tokens/sec | Learning rate 0.00029465
Saved dailydialog_local38k8e_step_22500.pt
Saved dailydialog_local38k8e_last.pt
Step 3521 | Loss 3.01 | Speed 1052 tokens/sec | Learning rate 0.00029439
Step 3561 | Loss 3.44 | Speed 2059 tokens/sec | Learning rate 0.00029413
Step 3601 | Loss 3.07 | Speed 1992 tokens/sec | Learning rate 0.00029387
Step 3641 | Loss 3.28 | Speed 2243 tokens/sec | Learning rate 0.00029361
Step 3681 | Loss 3.39 | Speed 2188 tokens/sec | Learning rate 0.00029335
Step 3721 | Loss 2.69 | Speed 2135 tokens/sec | Learning rate 0.00029309
Step 3761 | Loss 2.64 | Speed 2126 tokens/sec | Learning rate 0.00029284
Step 3801 | Loss 3.52 | Speed 2286 tokens/sec | Learning rate 0.00029258
Step 3841 | Loss 3.06 | Speed 2021 tokens/sec | Learning rate 0.00029232
Step 3881 | Loss 3.04 | Speed 1970 tokens/sec | Learning rate 0.00029207
Step 3921 | Loss 3.22 | Speed 2127 tokens/sec | Learning rate 0.00029181
Step 3961 | Loss 3.26 | Speed 2040 tokens/sec | Learning rate 0.00029156
Step 4001 | Loss 2.89 | Speed 2125 tokens/sec | Learning rate 0.00029131
Step 4041 | Loss 2.88 | Speed 2007 tokens/sec | Learning rate 0.00029105
Step 4081 | Loss 2.77 | Speed 2099 tokens/sec | Learning rate 0.0002908
Step 4121 | Loss 3.20 | Speed 2065 tokens/sec | Learning rate 0.00029055
Step 4161 | Loss 3.11 | Speed 2240 tokens/sec | Learning rate 0.0002903
Step 4201 | Loss 3.14 | Speed 2050 tokens/sec | Learning rate 0.00029005
Step 4241 | Loss 3.87 | Speed 2255 tokens/sec | Learning rate 0.0002898
Step 4281 | Loss 3.60 | Speed 2085 tokens/sec | Learning rate 0.00028955
Step 4321 | Loss 3.42 | Speed 2189 tokens/sec | Learning rate 0.0002893
Step 4361 | Loss 3.46 | Speed 2110 tokens/sec | Learning rate 0.00028905
Step 4401 | Loss 3.45 | Speed 2093 tokens/sec | Learning rate 0.00028881
Step 4441 | Loss 3.00 | Speed 2104 tokens/sec | Learning rate 0.00028856
Step 4481 | Loss 3.21 | Speed 2218 tokens/sec | Learning rate 0.00028832
Step 4521 | Loss 2.85 | Speed 2026 tokens/sec | Learning rate 0.00028807
Step 4561 | Loss 3.51 | Speed 2136 tokens/sec | Learning rate 0.00028783
Step 4601 | Loss 3.21 | Speed 2112 tokens/sec | Learning rate 0.00028758
Step 4641 | Loss 3.64 | Speed 1971 tokens/sec | Learning rate 0.00028734
Step 4681 | Loss 3.33 | Speed 2077 tokens/sec | Learning rate 0.0002871
Step 4721 | Loss 2.71 | Speed 2265 tokens/sec | Learning rate 0.00028685
Step 4761 | Loss 2.79 | Speed 2111 tokens/sec | Learning rate 0.00028661
Step 4801 | Loss 3.36 | Speed 2136 tokens/sec | Learning rate 0.00028637
Step 4841 | Loss 3.20 | Speed 2163 tokens/sec | Learning rate 0.00028613
Step 4881 | Loss 3.55 | Speed 1999 tokens/sec | Learning rate 0.00028589
Step 4921 | Loss 3.03 | Speed 2149 tokens/sec | Learning rate 0.00028565
Step 4961 | Loss 3.64 | Speed 2046 tokens/sec | Learning rate 0.00028541
Step 5001 | Loss 2.78 | Speed 2275 tokens/sec | Learning rate 0.00028518
Step 5041 | Loss 3.23 | Speed 2220 tokens/sec | Learning rate 0.00028494
Step 5081 | Loss 2.72 | Speed 2033 tokens/sec | Learning rate 0.0002847
Step 5121 | Loss 3.34 | Speed 2195 tokens/sec | Learning rate 0.00028447
Step 5161 | Loss 3.10 | Speed 2277 tokens/sec | Learning rate 0.00028423
Step 5201 | Loss 3.81 | Speed 2240 tokens/sec | Learning rate 0.000284
Step 5241 | Loss 3.32 | Speed 2029 tokens/sec | Learning rate 0.00028376
Step 5281 | Loss 3.08 | Speed 2112 tokens/sec | Learning rate 0.00028353
Step 5321 | Loss 3.73 | Speed 2148 tokens/sec | Learning rate 0.0002833
Step 5361 | Loss 3.01 | Speed 2158 tokens/sec | Learning rate 0.00028306
Step 5401 | Loss 3.28 | Speed 1952 tokens/sec | Learning rate 0.00028283
Step 5441 | Loss 3.20 | Speed 2270 tokens/sec | Learning rate 0.0002826
Step 5481 | Loss 3.39 | Speed 2050 tokens/sec | Learning rate 0.00028237
Step 5521 | Loss 3.80 | Speed 2199 tokens/sec | Learning rate 0.00028214
Step 5561 | Loss 3.42 | Speed 2180 tokens/sec | Learning rate 0.00028191
Step 5601 | Loss 2.12 | Speed 2134 tokens/sec | Learning rate 0.00028168
Step 5641 | Loss 3.53 | Speed 2110 tokens/sec | Learning rate 0.00028145
Step 5681 | Loss 2.75 | Speed 2088 tokens/sec | Learning rate 0.00028122
Step 5721 | Loss 3.24 | Speed 1993 tokens/sec | Learning rate 0.000281
Step 5761 | Loss 3.21 | Speed 2032 tokens/sec | Learning rate 0.00028077
Step 5801 | Loss 2.88 | Speed 2118 tokens/sec | Learning rate 0.00028054
Step 5841 | Loss 2.89 | Speed 2194 tokens/sec | Learning rate 0.00028032
Step 5881 | Loss 2.92 | Speed 2029 tokens/sec | Learning rate 0.00028009
Step 5921 | Loss 3.18 | Speed 2134 tokens/sec | Learning rate 0.00027987
Step 5961 | Loss 3.29 | Speed 2291 tokens/sec | Learning rate 0.00027964
Saved dailydialog_local38k8e_step_25000.pt
Saved dailydialog_local38k8e_last.pt
Step 6001 | Loss 3.09 | Speed 1328 tokens/sec | Learning rate 0.00027942
Step 6041 | Loss 3.26 | Speed 2070 tokens/sec | Learning rate 0.0002792
Step 6081 | Loss 3.04 | Speed 2076 tokens/sec | Learning rate 0.00027897
Step 6121 | Loss 3.12 | Speed 2288 tokens/sec | Learning rate 0.00027875
Step 6161 | Loss 3.28 | Speed 2063 tokens/sec | Learning rate 0.00027853
Step 6201 | Loss 3.09 | Speed 2024 tokens/sec | Learning rate 0.00027831
Step 6241 | Loss 3.11 | Speed 2181 tokens/sec | Learning rate 0.00027809
Step 6281 | Loss 2.87 | Speed 2150 tokens/sec | Learning rate 0.00027787
Step 6321 | Loss 3.40 | Speed 2109 tokens/sec | Learning rate 0.00027765
Step 6361 | Loss 3.58 | Speed 2195 tokens/sec | Learning rate 0.00027743
Step 6401 | Loss 3.67 | Speed 2123 tokens/sec | Learning rate 0.00027721
Step 6441 | Loss 3.25 | Speed 2197 tokens/sec | Learning rate 0.00027699
Step 6481 | Loss 2.93 | Speed 1991 tokens/sec | Learning rate 0.00027678
Step 6521 | Loss 3.70 | Speed 2114 tokens/sec | Learning rate 0.00027656
Step 6561 | Loss 3.46 | Speed 2066 tokens/sec | Learning rate 0.00027634
Step 6601 | Loss 3.33 | Speed 2142 tokens/sec | Learning rate 0.00027613
Step 6641 | Loss 2.99 | Speed 2121 tokens/sec | Learning rate 0.00027591
Step 6681 | Loss 2.75 | Speed 2020 tokens/sec | Learning rate 0.0002757
Step 6721 | Loss 2.83 | Speed 2027 tokens/sec | Learning rate 0.00027548
Step 6761 | Loss 3.43 | Speed 2090 tokens/sec | Learning rate 0.00027527
Step 6801 | Loss 3.47 | Speed 2092 tokens/sec | Learning rate 0.00027506
Step 6841 | Loss 3.08 | Speed 2086 tokens/sec | Learning rate 0.00027484
Step 6881 | Loss 3.15 | Speed 2058 tokens/sec | Learning rate 0.00027463
Step 6921 | Loss 3.17 | Speed 2076 tokens/sec | Learning rate 0.00027442
Step 6961 | Loss 3.27 | Speed 2059 tokens/sec | Learning rate 0.00027421
Step 7001 | Loss 3.13 | Speed 2293 tokens/sec | Learning rate 0.000274
Step 7041 | Loss 2.79 | Speed 1962 tokens/sec | Learning rate 0.00027379
Step 7081 | Loss 2.36 | Speed 2199 tokens/sec | Learning rate 0.00027358
Step 7121 | Loss 3.44 | Speed 2161 tokens/sec | Learning rate 0.00027337
Step 7161 | Loss 2.64 | Speed 2346 tokens/sec | Learning rate 0.00027316
Step 7201 | Loss 2.85 | Speed 2052 tokens/sec | Learning rate 0.00027295
Step 7241 | Loss 3.43 | Speed 2074 tokens/sec | Learning rate 0.00027274
Step 7281 | Loss 3.26 | Speed 2083 tokens/sec | Learning rate 0.00027253
Step 7321 | Loss 3.67 | Speed 2107 tokens/sec | Learning rate 0.00027233
Step 7361 | Loss 3.45 | Speed 2125 tokens/sec | Learning rate 0.00027212
Step 7401 | Loss 2.71 | Speed 2196 tokens/sec | Learning rate 0.00027191
Step 7441 | Loss 2.52 | Speed 1986 tokens/sec | Learning rate 0.00027171
Step 7481 | Loss 2.55 | Speed 2162 tokens/sec | Learning rate 0.0002715
Step 7521 | Loss 3.16 | Speed 2045 tokens/sec | Learning rate 0.0002713
Step 7561 | Loss 3.39 | Speed 2008 tokens/sec | Learning rate 0.00027109
Step 7601 | Loss 3.38 | Speed 2047 tokens/sec | Learning rate 0.00027089
Step 7641 | Loss 3.38 | Speed 2016 tokens/sec | Learning rate 0.00027069
Step 7681 | Loss 3.41 | Speed 2200 tokens/sec | Learning rate 0.00027048
Step 7721 | Loss 3.22 | Speed 1984 tokens/sec | Learning rate 0.00027028
Step 7761 | Loss 2.99 | Speed 2038 tokens/sec | Learning rate 0.00027008
Step 7801 | Loss 2.75 | Speed 2116 tokens/sec | Learning rate 0.00026988
Step 7841 | Loss 3.32 | Speed 1995 tokens/sec | Learning rate 0.00026968
Step 7881 | Loss 2.69 | Speed 2018 tokens/sec | Learning rate 0.00026948
Step 7921 | Loss 3.08 | Speed 2010 tokens/sec | Learning rate 0.00026928
Step 7961 | Loss 3.02 | Speed 2097 tokens/sec | Learning rate 0.00026908
Step 8001 | Loss 3.38 | Speed 2002 tokens/sec | Learning rate 0.00026888
Step 8041 | Loss 3.13 | Speed 1965 tokens/sec | Learning rate 0.00026868
Step 8081 | Loss 3.48 | Speed 2231 tokens/sec | Learning rate 0.00026848
Step 8121 | Loss 2.38 | Speed 2082 tokens/sec | Learning rate 0.00026828
Step 8161 | Loss 2.93 | Speed 2146 tokens/sec | Learning rate 0.00026808
Step 8201 | Loss 3.26 | Speed 2092 tokens/sec | Learning rate 0.00026789
Step 8241 | Loss 2.98 | Speed 2111 tokens/sec | Learning rate 0.00026769
Step 8281 | Loss 3.65 | Speed 2082 tokens/sec | Learning rate 0.00026749
Step 8321 | Loss 2.78 | Speed 2075 tokens/sec | Learning rate 0.0002673
Step 8361 | Loss 3.19 | Speed 2114 tokens/sec | Learning rate 0.0002671
Step 8401 | Loss 3.32 | Speed 2082 tokens/sec | Learning rate 0.00026691
Step 8441 | Loss 3.67 | Speed 2099 tokens/sec | Learning rate 0.00026671
Step 8481 | Loss 3.27 | Speed 2147 tokens/sec | Learning rate 0.00026652
Saved dailydialog_local38k8e_step_27500.pt
Saved dailydialog_local38k8e_last.pt
Step 8521 | Loss 3.29 | Speed 1128 tokens/sec | Learning rate 0.00026633
Step 8561 | Loss 3.42 | Speed 2181 tokens/sec | Learning rate 0.00026613
Step 8601 | Loss 3.20 | Speed 2014 tokens/sec | Learning rate 0.00026594
Step 8641 | Loss 3.41 | Speed 2148 tokens/sec | Learning rate 0.00026575
Step 8681 | Loss 3.54 | Speed 2120 tokens/sec | Learning rate 0.00026556
Step 8721 | Loss 3.27 | Speed 2095 tokens/sec | Learning rate 0.00026536
Step 8761 | Loss 3.17 | Speed 2150 tokens/sec | Learning rate 0.00026517
Step 8801 | Loss 3.17 | Speed 2066 tokens/sec | Learning rate 0.00026498
Step 8841 | Loss 3.13 | Speed 2262 tokens/sec | Learning rate 0.00026479
Step 8881 | Loss 3.79 | Speed 2156 tokens/sec | Learning rate 0.0002646
Step 8921 | Loss 3.01 | Speed 1925 tokens/sec | Learning rate 0.00026441
Step 8961 | Loss 2.61 | Speed 2118 tokens/sec | Learning rate 0.00026422
Step 9001 | Loss 3.22 | Speed 2103 tokens/sec | Learning rate 0.00026404
Step 9041 | Loss 2.78 | Speed 2091 tokens/sec | Learning rate 0.00026385
Step 9081 | Loss 3.53 | Speed 2029 tokens/sec | Learning rate 0.00026366
Step 9121 | Loss 3.23 | Speed 2120 tokens/sec | Learning rate 0.00026347
Step 9161 | Loss 2.86 | Speed 2148 tokens/sec | Learning rate 0.00026328
Step 9201 | Loss 3.54 | Speed 2019 tokens/sec | Learning rate 0.0002631
Step 9241 | Loss 2.82 | Speed 2190 tokens/sec | Learning rate 0.00026291
Step 9281 | Loss 3.33 | Speed 2018 tokens/sec | Learning rate 0.00026273
Step 9321 | Loss 3.05 | Speed 2132 tokens/sec | Learning rate 0.00026254
Step 9361 | Loss 3.08 | Speed 2210 tokens/sec | Learning rate 0.00026236
Step 9401 | Loss 3.25 | Speed 2160 tokens/sec | Learning rate 0.00026217
Step 9441 | Loss 2.93 | Speed 2139 tokens/sec | Learning rate 0.00026199
Step 9481 | Loss 2.73 | Speed 2120 tokens/sec | Learning rate 0.0002618
| ID | GPU | MEM |
------------------
|  0 | 91% | 27% |
Epoch 2 Validation ====
Validation loss: 3.1571
[██████████░░░░░░░░░░░░░░░░░░]  epoch 3/8 complete
  train_loss=3.2045  val_loss=3.1571  steps=28521  tokens_seen=3445077

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_2.pt
Saved dailydialog_local38k8e_last.pt
Epoch 3 Training ====
Step 1 | Loss 2.40 | Speed 1477 tokens/sec | Learning rate 0.00026168
Step 41 | Loss 2.84 | Speed 2044 tokens/sec | Learning rate 0.00026149
Step 81 | Loss 2.58 | Speed 2240 tokens/sec | Learning rate 0.00026131
Step 121 | Loss 2.79 | Speed 2027 tokens/sec | Learning rate 0.00026113
Step 161 | Loss 2.66 | Speed 2060 tokens/sec | Learning rate 0.00026095
Step 201 | Loss 2.95 | Speed 2145 tokens/sec | Learning rate 0.00026077
Step 241 | Loss 2.58 | Speed 2139 tokens/sec | Learning rate 0.00026058
Step 281 | Loss 2.62 | Speed 2073 tokens/sec | Learning rate 0.0002604
Step 321 | Loss 2.98 | Speed 1998 tokens/sec | Learning rate 0.00026022
Step 361 | Loss 3.19 | Speed 2010 tokens/sec | Learning rate 0.00026004
Step 401 | Loss 2.55 | Speed 2130 tokens/sec | Learning rate 0.00025986
Step 441 | Loss 3.19 | Speed 2191 tokens/sec | Learning rate 0.00025968
Step 481 | Loss 3.17 | Speed 2078 tokens/sec | Learning rate 0.0002595
Step 521 | Loss 3.16 | Speed 2056 tokens/sec | Learning rate 0.00025932
Step 561 | Loss 3.62 | Speed 2191 tokens/sec | Learning rate 0.00025915
Step 601 | Loss 3.11 | Speed 1930 tokens/sec | Learning rate 0.00025897
Step 641 | Loss 3.22 | Speed 2086 tokens/sec | Learning rate 0.00025879
Step 681 | Loss 3.18 | Speed 2289 tokens/sec | Learning rate 0.00025861
Step 721 | Loss 3.42 | Speed 2221 tokens/sec | Learning rate 0.00025844
Step 761 | Loss 2.96 | Speed 2037 tokens/sec | Learning rate 0.00025826
Step 801 | Loss 3.57 | Speed 2040 tokens/sec | Learning rate 0.00025808
Step 841 | Loss 3.57 | Speed 2223 tokens/sec | Learning rate 0.00025791
Step 881 | Loss 3.03 | Speed 2145 tokens/sec | Learning rate 0.00025773
Step 921 | Loss 2.71 | Speed 2092 tokens/sec | Learning rate 0.00025756
Step 961 | Loss 3.39 | Speed 2108 tokens/sec | Learning rate 0.00025738
Step 1001 | Loss 2.70 | Speed 2141 tokens/sec | Learning rate 0.00025721
Step 1041 | Loss 2.59 | Speed 1991 tokens/sec | Learning rate 0.00025703
Step 1081 | Loss 3.18 | Speed 2055 tokens/sec | Learning rate 0.00025686
Step 1121 | Loss 3.56 | Speed 1995 tokens/sec | Learning rate 0.00025669
Step 1161 | Loss 3.06 | Speed 2063 tokens/sec | Learning rate 0.00025651
Step 1201 | Loss 3.38 | Speed 2079 tokens/sec | Learning rate 0.00025634
Step 1241 | Loss 3.12 | Speed 2114 tokens/sec | Learning rate 0.00025617
Step 1281 | Loss 3.55 | Speed 2170 tokens/sec | Learning rate 0.000256
Step 1321 | Loss 2.92 | Speed 2214 tokens/sec | Learning rate 0.00025583
Step 1361 | Loss 3.12 | Speed 2112 tokens/sec | Learning rate 0.00025565
Step 1401 | Loss 2.90 | Speed 2072 tokens/sec | Learning rate 0.00025548
Step 1441 | Loss 2.32 | Speed 2008 tokens/sec | Learning rate 0.00025531
Saved dailydialog_local38k8e_step_30000.pt
Saved dailydialog_local38k8e_last.pt
Step 1481 | Loss 3.14 | Speed 1215 tokens/sec | Learning rate 0.00025514
Step 1521 | Loss 2.66 | Speed 2173 tokens/sec | Learning rate 0.00025497
Step 1561 | Loss 3.09 | Speed 2006 tokens/sec | Learning rate 0.0002548
Step 1601 | Loss 2.88 | Speed 1995 tokens/sec | Learning rate 0.00025463
Step 1641 | Loss 3.06 | Speed 2148 tokens/sec | Learning rate 0.00025446
Step 1681 | Loss 2.57 | Speed 2229 tokens/sec | Learning rate 0.0002543
Step 1721 | Loss 2.80 | Speed 2336 tokens/sec | Learning rate 0.00025413
Step 1761 | Loss 2.92 | Speed 2035 tokens/sec | Learning rate 0.00025396
Step 1801 | Loss 3.39 | Speed 2013 tokens/sec | Learning rate 0.00025379
Step 1841 | Loss 3.22 | Speed 2063 tokens/sec | Learning rate 0.00025363
Step 1881 | Loss 3.15 | Speed 2113 tokens/sec | Learning rate 0.00025346
Step 1921 | Loss 3.58 | Speed 2102 tokens/sec | Learning rate 0.00025329
Step 1961 | Loss 2.98 | Speed 1964 tokens/sec | Learning rate 0.00025313
Step 2001 | Loss 2.50 | Speed 2223 tokens/sec | Learning rate 0.00025296
Step 2041 | Loss 2.88 | Speed 2264 tokens/sec | Learning rate 0.00025279
Step 2081 | Loss 3.29 | Speed 2231 tokens/sec | Learning rate 0.00025263
Step 2121 | Loss 3.04 | Speed 2231 tokens/sec | Learning rate 0.00025246
Step 2161 | Loss 2.86 | Speed 2158 tokens/sec | Learning rate 0.0002523
Step 2201 | Loss 2.96 | Speed 2141 tokens/sec | Learning rate 0.00025214
Step 2241 | Loss 2.98 | Speed 2115 tokens/sec | Learning rate 0.00025197
Step 2281 | Loss 3.08 | Speed 2100 tokens/sec | Learning rate 0.00025181
Step 2321 | Loss 3.42 | Speed 2031 tokens/sec | Learning rate 0.00025164
Step 2361 | Loss 2.84 | Speed 2237 tokens/sec | Learning rate 0.00025148
Step 2401 | Loss 3.31 | Speed 2223 tokens/sec | Learning rate 0.00025132
Step 2441 | Loss 3.05 | Speed 2139 tokens/sec | Learning rate 0.00025116
Step 2481 | Loss 3.13 | Speed 2223 tokens/sec | Learning rate 0.00025099
Step 2521 | Loss 3.07 | Speed 2136 tokens/sec | Learning rate 0.00025083
Step 2561 | Loss 3.16 | Speed 2087 tokens/sec | Learning rate 0.00025067
Step 2601 | Loss 2.95 | Speed 2169 tokens/sec | Learning rate 0.00025051
Step 2641 | Loss 3.25 | Speed 1960 tokens/sec | Learning rate 0.00025035
Step 2681 | Loss 3.61 | Speed 2271 tokens/sec | Learning rate 0.00025019
Step 2721 | Loss 3.28 | Speed 2110 tokens/sec | Learning rate 0.00025003
Step 2761 | Loss 2.99 | Speed 2084 tokens/sec | Learning rate 0.00024987
Step 2801 | Loss 2.67 | Speed 2207 tokens/sec | Learning rate 0.00024971
Step 2841 | Loss 3.73 | Speed 2135 tokens/sec | Learning rate 0.00024955
Step 2881 | Loss 3.09 | Speed 2093 tokens/sec | Learning rate 0.00024939
Step 2921 | Loss 3.21 | Speed 2138 tokens/sec | Learning rate 0.00024923
Step 2961 | Loss 2.59 | Speed 2143 tokens/sec | Learning rate 0.00024907
Step 3001 | Loss 2.85 | Speed 2069 tokens/sec | Learning rate 0.00024892
Step 3041 | Loss 3.05 | Speed 2054 tokens/sec | Learning rate 0.00024876
Step 3081 | Loss 2.78 | Speed 2125 tokens/sec | Learning rate 0.0002486
Step 3121 | Loss 2.96 | Speed 2001 tokens/sec | Learning rate 0.00024844
Step 3161 | Loss 3.19 | Speed 2183 tokens/sec | Learning rate 0.00024829
Step 3201 | Loss 3.47 | Speed 2114 tokens/sec | Learning rate 0.00024813
Step 3241 | Loss 3.17 | Speed 2151 tokens/sec | Learning rate 0.00024797
Step 3281 | Loss 2.96 | Speed 2078 tokens/sec | Learning rate 0.00024782
Step 3321 | Loss 2.37 | Speed 2050 tokens/sec | Learning rate 0.00024766
Step 3361 | Loss 3.23 | Speed 2135 tokens/sec | Learning rate 0.00024751
Step 3401 | Loss 3.37 | Speed 2014 tokens/sec | Learning rate 0.00024735
Step 3441 | Loss 2.83 | Speed 2221 tokens/sec | Learning rate 0.0002472
Step 3481 | Loss 3.18 | Speed 2141 tokens/sec | Learning rate 0.00024704
Step 3521 | Loss 2.86 | Speed 1980 tokens/sec | Learning rate 0.00024689
Step 3561 | Loss 3.28 | Speed 2004 tokens/sec | Learning rate 0.00024673
Step 3601 | Loss 2.89 | Speed 2120 tokens/sec | Learning rate 0.00024658
Step 3641 | Loss 3.00 | Speed 2259 tokens/sec | Learning rate 0.00024643
Step 3681 | Loss 3.08 | Speed 2175 tokens/sec | Learning rate 0.00024627
Step 3721 | Loss 3.34 | Speed 2141 tokens/sec | Learning rate 0.00024612
Step 3761 | Loss 2.16 | Speed 2113 tokens/sec | Learning rate 0.00024597
Step 3801 | Loss 3.02 | Speed 2142 tokens/sec | Learning rate 0.00024582
Step 3841 | Loss 3.18 | Speed 2254 tokens/sec | Learning rate 0.00024566
Step 3881 | Loss 3.77 | Speed 2018 tokens/sec | Learning rate 0.00024551
Step 3921 | Loss 2.74 | Speed 2039 tokens/sec | Learning rate 0.00024536
Step 3961 | Loss 3.67 | Speed 2099 tokens/sec | Learning rate 0.00024521
Saved dailydialog_local38k8e_step_32500.pt
Saved dailydialog_local38k8e_last.pt
Step 4001 | Loss 3.01 | Speed 1115 tokens/sec | Learning rate 0.00024506
Step 4041 | Loss 3.10 | Speed 2169 tokens/sec | Learning rate 0.00024491
Step 4081 | Loss 2.28 | Speed 2057 tokens/sec | Learning rate 0.00024476
Step 4121 | Loss 3.49 | Speed 2096 tokens/sec | Learning rate 0.00024461
Step 4161 | Loss 3.01 | Speed 2025 tokens/sec | Learning rate 0.00024446
Step 4201 | Loss 3.45 | Speed 2160 tokens/sec | Learning rate 0.00024431
Step 4241 | Loss 3.55 | Speed 1996 tokens/sec | Learning rate 0.00024416
Step 4281 | Loss 3.36 | Speed 2151 tokens/sec | Learning rate 0.00024401
Step 4321 | Loss 3.38 | Speed 2194 tokens/sec | Learning rate 0.00024386
Step 4361 | Loss 2.95 | Speed 2050 tokens/sec | Learning rate 0.00024371
Step 4401 | Loss 2.96 | Speed 2145 tokens/sec | Learning rate 0.00024357
Step 4441 | Loss 3.42 | Speed 2159 tokens/sec | Learning rate 0.00024342
Step 4481 | Loss 2.87 | Speed 2100 tokens/sec | Learning rate 0.00024327
Step 4521 | Loss 3.23 | Speed 2172 tokens/sec | Learning rate 0.00024312
Step 4561 | Loss 3.29 | Speed 2145 tokens/sec | Learning rate 0.00024298
Step 4601 | Loss 3.48 | Speed 2075 tokens/sec | Learning rate 0.00024283
Step 4641 | Loss 3.12 | Speed 2122 tokens/sec | Learning rate 0.00024268
Step 4681 | Loss 2.89 | Speed 2184 tokens/sec | Learning rate 0.00024254
Step 4721 | Loss 2.81 | Speed 2098 tokens/sec | Learning rate 0.00024239
Step 4761 | Loss 2.71 | Speed 2137 tokens/sec | Learning rate 0.00024224
Step 4801 | Loss 3.30 | Speed 2230 tokens/sec | Learning rate 0.0002421
Step 4841 | Loss 2.88 | Speed 2173 tokens/sec | Learning rate 0.00024195
Step 4881 | Loss 2.72 | Speed 2173 tokens/sec | Learning rate 0.00024181
Step 4921 | Loss 3.08 | Speed 2085 tokens/sec | Learning rate 0.00024166
Step 4961 | Loss 2.78 | Speed 1881 tokens/sec | Learning rate 0.00024152
Step 5001 | Loss 3.09 | Speed 2034 tokens/sec | Learning rate 0.00024138
Step 5041 | Loss 2.74 | Speed 2101 tokens/sec | Learning rate 0.00024123
Step 5081 | Loss 2.99 | Speed 2047 tokens/sec | Learning rate 0.00024109
Step 5121 | Loss 2.63 | Speed 2081 tokens/sec | Learning rate 0.00024094
Step 5161 | Loss 3.23 | Speed 2060 tokens/sec | Learning rate 0.0002408
Step 5201 | Loss 3.14 | Speed 2039 tokens/sec | Learning rate 0.00024066
Step 5241 | Loss 3.33 | Speed 2242 tokens/sec | Learning rate 0.00024052
Step 5281 | Loss 2.83 | Speed 2047 tokens/sec | Learning rate 0.00024037
Step 5321 | Loss 3.34 | Speed 2033 tokens/sec | Learning rate 0.00024023
Step 5361 | Loss 2.44 | Speed 2104 tokens/sec | Learning rate 0.00024009
Step 5401 | Loss 3.24 | Speed 2096 tokens/sec | Learning rate 0.00023995
Step 5441 | Loss 2.66 | Speed 2125 tokens/sec | Learning rate 0.00023981
Step 5481 | Loss 2.67 | Speed 1965 tokens/sec | Learning rate 0.00023967
Step 5521 | Loss 2.95 | Speed 1921 tokens/sec | Learning rate 0.00023953
Step 5561 | Loss 2.79 | Speed 2100 tokens/sec | Learning rate 0.00023938
Step 5601 | Loss 3.07 | Speed 2223 tokens/sec | Learning rate 0.00023924
Step 5641 | Loss 3.40 | Speed 2103 tokens/sec | Learning rate 0.0002391
Step 5681 | Loss 3.25 | Speed 2119 tokens/sec | Learning rate 0.00023896
Step 5721 | Loss 3.13 | Speed 2059 tokens/sec | Learning rate 0.00023882
Step 5761 | Loss 3.06 | Speed 2338 tokens/sec | Learning rate 0.00023869
Step 5801 | Loss 3.05 | Speed 2116 tokens/sec | Learning rate 0.00023855
Step 5841 | Loss 3.14 | Speed 2022 tokens/sec | Learning rate 0.00023841
Step 5881 | Loss 2.88 | Speed 2107 tokens/sec | Learning rate 0.00023827
Step 5921 | Loss 2.74 | Speed 2137 tokens/sec | Learning rate 0.00023813
Step 5961 | Loss 2.99 | Speed 2008 tokens/sec | Learning rate 0.00023799
Step 6001 | Loss 3.09 | Speed 2195 tokens/sec | Learning rate 0.00023785
Step 6041 | Loss 2.84 | Speed 2092 tokens/sec | Learning rate 0.00023772
Step 6081 | Loss 2.96 | Speed 2364 tokens/sec | Learning rate 0.00023758
Step 6121 | Loss 2.47 | Speed 2061 tokens/sec | Learning rate 0.00023744
Step 6161 | Loss 2.46 | Speed 2109 tokens/sec | Learning rate 0.0002373
Step 6201 | Loss 3.40 | Speed 2291 tokens/sec | Learning rate 0.00023717
Step 6241 | Loss 3.87 | Speed 1954 tokens/sec | Learning rate 0.00023703
Step 6281 | Loss 3.02 | Speed 2051 tokens/sec | Learning rate 0.0002369
Step 6321 | Loss 2.42 | Speed 2162 tokens/sec | Learning rate 0.00023676
Step 6361 | Loss 3.53 | Speed 2105 tokens/sec | Learning rate 0.00023662
Step 6401 | Loss 3.07 | Speed 2246 tokens/sec | Learning rate 0.00023649
Step 6441 | Loss 3.33 | Speed 2117 tokens/sec | Learning rate 0.00023635
Saved dailydialog_local38k8e_step_35000.pt
Saved dailydialog_local38k8e_last.pt
Step 6481 | Loss 3.02 | Speed 1260 tokens/sec | Learning rate 0.00023622
Step 6521 | Loss 2.78 | Speed 2159 tokens/sec | Learning rate 0.00023608
Step 6561 | Loss 2.73 | Speed 2067 tokens/sec | Learning rate 0.00023595
Step 6601 | Loss 3.28 | Speed 2041 tokens/sec | Learning rate 0.00023581
Step 6641 | Loss 2.96 | Speed 2060 tokens/sec | Learning rate 0.00023568
Step 6681 | Loss 2.72 | Speed 2140 tokens/sec | Learning rate 0.00023555
Step 6721 | Loss 2.92 | Speed 2050 tokens/sec | Learning rate 0.00023541
Step 6761 | Loss 2.85 | Speed 2179 tokens/sec | Learning rate 0.00023528
Step 6801 | Loss 2.86 | Speed 1969 tokens/sec | Learning rate 0.00023515
Step 6841 | Loss 3.12 | Speed 2087 tokens/sec | Learning rate 0.00023501
Step 6881 | Loss 3.15 | Speed 2168 tokens/sec | Learning rate 0.00023488
Step 6921 | Loss 3.32 | Speed 2129 tokens/sec | Learning rate 0.00023475
Step 6961 | Loss 2.90 | Speed 2030 tokens/sec | Learning rate 0.00023461
Step 7001 | Loss 2.98 | Speed 2198 tokens/sec | Learning rate 0.00023448
Step 7041 | Loss 3.35 | Speed 1948 tokens/sec | Learning rate 0.00023435
Step 7081 | Loss 2.99 | Speed 1987 tokens/sec | Learning rate 0.00023422
Step 7121 | Loss 3.33 | Speed 2206 tokens/sec | Learning rate 0.00023409
Step 7161 | Loss 3.00 | Speed 2153 tokens/sec | Learning rate 0.00023396
Step 7201 | Loss 3.27 | Speed 1946 tokens/sec | Learning rate 0.00023383
Step 7241 | Loss 2.89 | Speed 2055 tokens/sec | Learning rate 0.00023369
Step 7281 | Loss 2.98 | Speed 2090 tokens/sec | Learning rate 0.00023356
Step 7321 | Loss 3.17 | Speed 2061 tokens/sec | Learning rate 0.00023343
Step 7361 | Loss 2.99 | Speed 2077 tokens/sec | Learning rate 0.0002333
Step 7401 | Loss 2.98 | Speed 2279 tokens/sec | Learning rate 0.00023317
Step 7441 | Loss 2.52 | Speed 1994 tokens/sec | Learning rate 0.00023304
Step 7481 | Loss 3.42 | Speed 2056 tokens/sec | Learning rate 0.00023291
Step 7521 | Loss 2.90 | Speed 2217 tokens/sec | Learning rate 0.00023278
Step 7561 | Loss 2.95 | Speed 1995 tokens/sec | Learning rate 0.00023266
Step 7601 | Loss 3.18 | Speed 2150 tokens/sec | Learning rate 0.00023253
Step 7641 | Loss 2.83 | Speed 2012 tokens/sec | Learning rate 0.0002324
Step 7681 | Loss 3.13 | Speed 2132 tokens/sec | Learning rate 0.00023227
Step 7721 | Loss 3.11 | Speed 1946 tokens/sec | Learning rate 0.00023214
Step 7761 | Loss 3.22 | Speed 2094 tokens/sec | Learning rate 0.00023201
Step 7801 | Loss 2.85 | Speed 2106 tokens/sec | Learning rate 0.00023189
Step 7841 | Loss 2.94 | Speed 2148 tokens/sec | Learning rate 0.00023176
Step 7881 | Loss 2.73 | Speed 2100 tokens/sec | Learning rate 0.00023163
Step 7921 | Loss 3.57 | Speed 2127 tokens/sec | Learning rate 0.0002315
Step 7961 | Loss 3.16 | Speed 2139 tokens/sec | Learning rate 0.00023138
Step 8001 | Loss 2.50 | Speed 2031 tokens/sec | Learning rate 0.00023125
Step 8041 | Loss 3.08 | Speed 2124 tokens/sec | Learning rate 0.00023112
Step 8081 | Loss 2.90 | Speed 2131 tokens/sec | Learning rate 0.000231
Step 8121 | Loss 3.61 | Speed 1966 tokens/sec | Learning rate 0.00023087
Step 8161 | Loss 3.16 | Speed 2003 tokens/sec | Learning rate 0.00023075
Step 8201 | Loss 2.61 | Speed 2070 tokens/sec | Learning rate 0.00023062
Step 8241 | Loss 3.14 | Speed 2082 tokens/sec | Learning rate 0.00023049
Step 8281 | Loss 2.70 | Speed 2126 tokens/sec | Learning rate 0.00023037
Step 8321 | Loss 3.56 | Speed 2024 tokens/sec | Learning rate 0.00023024
Step 8361 | Loss 3.04 | Speed 2082 tokens/sec | Learning rate 0.00023012
Step 8401 | Loss 3.00 | Speed 2049 tokens/sec | Learning rate 0.00022999
Step 8441 | Loss 3.23 | Speed 2056 tokens/sec | Learning rate 0.00022987
Step 8481 | Loss 3.11 | Speed 2002 tokens/sec | Learning rate 0.00022975
Step 8521 | Loss 3.32 | Speed 2181 tokens/sec | Learning rate 0.00022962
Step 8561 | Loss 2.98 | Speed 2157 tokens/sec | Learning rate 0.0002295
Step 8601 | Loss 2.68 | Speed 2090 tokens/sec | Learning rate 0.00022937
Step 8641 | Loss 3.06 | Speed 2219 tokens/sec | Learning rate 0.00022925
Step 8681 | Loss 2.97 | Speed 2089 tokens/sec | Learning rate 0.00022913
Step 8721 | Loss 2.72 | Speed 2152 tokens/sec | Learning rate 0.000229
Step 8761 | Loss 2.47 | Speed 1961 tokens/sec | Learning rate 0.00022888
Step 8801 | Loss 2.96 | Speed 2131 tokens/sec | Learning rate 0.00022876
Step 8841 | Loss 2.84 | Speed 2034 tokens/sec | Learning rate 0.00022864
Step 8881 | Loss 2.94 | Speed 2106 tokens/sec | Learning rate 0.00022851
Step 8921 | Loss 3.25 | Speed 2021 tokens/sec | Learning rate 0.00022839
Step 8961 | Loss 3.30 | Speed 2250 tokens/sec | Learning rate 0.00022827
Saved dailydialog_local38k8e_step_37500.pt
Saved dailydialog_local38k8e_last.pt
Step 9001 | Loss 2.87 | Speed 1109 tokens/sec | Learning rate 0.00022815
Step 9041 | Loss 2.97 | Speed 2057 tokens/sec | Learning rate 0.00022803
Step 9081 | Loss 2.91 | Speed 2243 tokens/sec | Learning rate 0.0002279
Step 9121 | Loss 2.79 | Speed 2119 tokens/sec | Learning rate 0.00022778
Step 9161 | Loss 3.12 | Speed 2063 tokens/sec | Learning rate 0.00022766
Step 9201 | Loss 2.66 | Speed 2039 tokens/sec | Learning rate 0.00022754
Step 9241 | Loss 3.07 | Speed 2184 tokens/sec | Learning rate 0.00022742
Step 9281 | Loss 2.32 | Speed 1980 tokens/sec | Learning rate 0.0002273
Step 9321 | Loss 3.38 | Speed 2127 tokens/sec | Learning rate 0.00022718
Step 9361 | Loss 2.93 | Speed 2037 tokens/sec | Learning rate 0.00022706
Step 9401 | Loss 2.85 | Speed 2242 tokens/sec | Learning rate 0.00022694
Step 9441 | Loss 3.29 | Speed 2140 tokens/sec | Learning rate 0.00022682
Step 9481 | Loss 2.73 | Speed 2154 tokens/sec | Learning rate 0.0002267
| ID | GPU | MEM |
------------------
|  0 | 90% | 27% |
Epoch 3 Validation ====
Validation loss: 3.0980
[██████████████░░░░░░░░░░░░░░]  epoch 4/8 complete
  train_loss=3.0819  val_loss=3.0980  steps=38028  tokens_seen=4593436

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_3.pt
Saved dailydialog_local38k8e_last.pt
Epoch 4 Training ====
Step 1 | Loss 2.55 | Speed 1558 tokens/sec | Learning rate 0.00022662
Step 41 | Loss 2.78 | Speed 2171 tokens/sec | Learning rate 0.0002265
Step 81 | Loss 2.47 | Speed 1981 tokens/sec | Learning rate 0.00022638
Step 121 | Loss 3.29 | Speed 2097 tokens/sec | Learning rate 0.00022627
Step 161 | Loss 2.98 | Speed 1995 tokens/sec | Learning rate 0.00022615
Step 201 | Loss 2.82 | Speed 2077 tokens/sec | Learning rate 0.00022603
Step 241 | Loss 3.17 | Speed 2008 tokens/sec | Learning rate 0.00022591
Step 281 | Loss 3.08 | Speed 2034 tokens/sec | Learning rate 0.00022579
Step 321 | Loss 3.43 | Speed 2225 tokens/sec | Learning rate 0.00022567
Step 361 | Loss 2.71 | Speed 2024 tokens/sec | Learning rate 0.00022556
Step 401 | Loss 3.14 | Speed 2050 tokens/sec | Learning rate 0.00022544
Step 441 | Loss 2.86 | Speed 1974 tokens/sec | Learning rate 0.00022532
Step 481 | Loss 2.31 | Speed 2117 tokens/sec | Learning rate 0.00022521
Step 521 | Loss 2.68 | Speed 2114 tokens/sec | Learning rate 0.00022509
Step 561 | Loss 2.45 | Speed 2071 tokens/sec | Learning rate 0.00022497
Step 601 | Loss 3.07 | Speed 2156 tokens/sec | Learning rate 0.00022486
Step 641 | Loss 3.39 | Speed 2075 tokens/sec | Learning rate 0.00022474
Step 681 | Loss 2.76 | Speed 1981 tokens/sec | Learning rate 0.00022462
Step 721 | Loss 3.09 | Speed 2151 tokens/sec | Learning rate 0.00022451
Step 761 | Loss 2.98 | Speed 1993 tokens/sec | Learning rate 0.00022439
Step 801 | Loss 3.02 | Speed 2094 tokens/sec | Learning rate 0.00022428
Step 841 | Loss 3.05 | Speed 1979 tokens/sec | Learning rate 0.00022416
Step 881 | Loss 2.89 | Speed 2075 tokens/sec | Learning rate 0.00022404
Step 921 | Loss 2.72 | Speed 2014 tokens/sec | Learning rate 0.00022393
Step 961 | Loss 3.01 | Speed 2049 tokens/sec | Learning rate 0.00022381
Step 1001 | Loss 3.15 | Speed 1950 tokens/sec | Learning rate 0.0002237
Step 1041 | Loss 3.08 | Speed 2178 tokens/sec | Learning rate 0.00022359
Step 1081 | Loss 3.05 | Speed 1983 tokens/sec | Learning rate 0.00022347
Step 1121 | Loss 3.34 | Speed 1995 tokens/sec | Learning rate 0.00022336
Step 1161 | Loss 3.13 | Speed 2080 tokens/sec | Learning rate 0.00022324
Step 1201 | Loss 2.25 | Speed 2069 tokens/sec | Learning rate 0.00022313
Step 1241 | Loss 2.87 | Speed 2115 tokens/sec | Learning rate 0.00022302
Step 1281 | Loss 2.90 | Speed 2110 tokens/sec | Learning rate 0.0002229
Step 1321 | Loss 3.00 | Speed 2124 tokens/sec | Learning rate 0.00022279
Step 1361 | Loss 3.06 | Speed 2180 tokens/sec | Learning rate 0.00022268
Step 1401 | Loss 3.13 | Speed 2049 tokens/sec | Learning rate 0.00022256
Step 1441 | Loss 2.91 | Speed 2016 tokens/sec | Learning rate 0.00022245
Step 1481 | Loss 2.65 | Speed 2185 tokens/sec | Learning rate 0.00022234
Step 1521 | Loss 2.75 | Speed 2002 tokens/sec | Learning rate 0.00022222
Step 1561 | Loss 2.87 | Speed 2083 tokens/sec | Learning rate 0.00022211
Step 1601 | Loss 3.19 | Speed 2004 tokens/sec | Learning rate 0.000222
Step 1641 | Loss 2.72 | Speed 2216 tokens/sec | Learning rate 0.00022189
Step 1681 | Loss 2.84 | Speed 2070 tokens/sec | Learning rate 0.00022178
Step 1721 | Loss 2.74 | Speed 2062 tokens/sec | Learning rate 0.00022166
Step 1761 | Loss 2.30 | Speed 1905 tokens/sec | Learning rate 0.00022155
Step 1801 | Loss 2.76 | Speed 2009 tokens/sec | Learning rate 0.00022144
Step 1841 | Loss 3.45 | Speed 2146 tokens/sec | Learning rate 0.00022133
Step 1881 | Loss 3.21 | Speed 2145 tokens/sec | Learning rate 0.00022122
Step 1921 | Loss 2.50 | Speed 2187 tokens/sec | Learning rate 0.00022111
Step 1961 | Loss 2.69 | Speed 2053 tokens/sec | Learning rate 0.000221
Saved dailydialog_local38k8e_step_40000.pt
Saved dailydialog_local38k8e_last.pt
Step 2001 | Loss 2.85 | Speed 1054 tokens/sec | Learning rate 0.00022089
Step 2041 | Loss 2.88 | Speed 2035 tokens/sec | Learning rate 0.00022078
Step 2081 | Loss 2.72 | Speed 2092 tokens/sec | Learning rate 0.00022067
Step 2121 | Loss 3.05 | Speed 2171 tokens/sec | Learning rate 0.00022056
Step 2161 | Loss 2.87 | Speed 2115 tokens/sec | Learning rate 0.00022045
Step 2201 | Loss 3.60 | Speed 2293 tokens/sec | Learning rate 0.00022034
Step 2241 | Loss 2.76 | Speed 2170 tokens/sec | Learning rate 0.00022023
Step 2281 | Loss 2.63 | Speed 1956 tokens/sec | Learning rate 0.00022012
Step 2321 | Loss 2.78 | Speed 2018 tokens/sec | Learning rate 0.00022001
Step 2361 | Loss 2.86 | Speed 1942 tokens/sec | Learning rate 0.0002199
Step 2401 | Loss 3.06 | Speed 2037 tokens/sec | Learning rate 0.00021979
Step 2441 | Loss 2.71 | Speed 2117 tokens/sec | Learning rate 0.00021968
Step 2481 | Loss 2.95 | Speed 1964 tokens/sec | Learning rate 0.00021958
Step 2521 | Loss 3.03 | Speed 2124 tokens/sec | Learning rate 0.00021947
Step 2561 | Loss 2.92 | Speed 2093 tokens/sec | Learning rate 0.00021936
Step 2601 | Loss 2.98 | Speed 2148 tokens/sec | Learning rate 0.00021925
Step 2641 | Loss 2.35 | Speed 2005 tokens/sec | Learning rate 0.00021914
Step 2681 | Loss 3.25 | Speed 2008 tokens/sec | Learning rate 0.00021904
Step 2721 | Loss 2.82 | Speed 2088 tokens/sec | Learning rate 0.00021893
Step 2761 | Loss 3.21 | Speed 2189 tokens/sec | Learning rate 0.00021882
Step 2801 | Loss 3.15 | Speed 2147 tokens/sec | Learning rate 0.00021871
Step 2841 | Loss 2.44 | Speed 2112 tokens/sec | Learning rate 0.00021861
Step 2881 | Loss 3.35 | Speed 2120 tokens/sec | Learning rate 0.0002185
Step 2921 | Loss 3.09 | Speed 2083 tokens/sec | Learning rate 0.00021839
Step 2961 | Loss 2.62 | Speed 2042 tokens/sec | Learning rate 0.00021829
Step 3001 | Loss 3.60 | Speed 2101 tokens/sec | Learning rate 0.00021818
Step 3041 | Loss 2.73 | Speed 2022 tokens/sec | Learning rate 0.00021807
Step 3081 | Loss 3.31 | Speed 2154 tokens/sec | Learning rate 0.00021797
Step 3121 | Loss 3.47 | Speed 1978 tokens/sec | Learning rate 0.00021786
Step 3161 | Loss 3.47 | Speed 1958 tokens/sec | Learning rate 0.00021776
Step 3201 | Loss 3.20 | Speed 2148 tokens/sec | Learning rate 0.00021765
Step 3241 | Loss 3.00 | Speed 2017 tokens/sec | Learning rate 0.00021754
Step 3281 | Loss 2.85 | Speed 2178 tokens/sec | Learning rate 0.00021744
Step 3321 | Loss 3.14 | Speed 2147 tokens/sec | Learning rate 0.00021733
Step 3361 | Loss 2.70 | Speed 2138 tokens/sec | Learning rate 0.00021723
Step 3401 | Loss 2.91 | Speed 2049 tokens/sec | Learning rate 0.00021712
Step 3441 | Loss 2.89 | Speed 2165 tokens/sec | Learning rate 0.00021702
Step 3481 | Loss 3.01 | Speed 2170 tokens/sec | Learning rate 0.00021691
Step 3521 | Loss 2.99 | Speed 2146 tokens/sec | Learning rate 0.00021681
Step 3561 | Loss 2.93 | Speed 2015 tokens/sec | Learning rate 0.00021671
Step 3601 | Loss 2.99 | Speed 1973 tokens/sec | Learning rate 0.0002166
Step 3641 | Loss 2.88 | Speed 1963 tokens/sec | Learning rate 0.0002165
Step 3681 | Loss 2.92 | Speed 2092 tokens/sec | Learning rate 0.00021639
Step 3721 | Loss 3.09 | Speed 2113 tokens/sec | Learning rate 0.00021629
Step 3761 | Loss 2.80 | Speed 1940 tokens/sec | Learning rate 0.00021619
Step 3801 | Loss 3.16 | Speed 2075 tokens/sec | Learning rate 0.00021608
Step 3841 | Loss 3.63 | Speed 2168 tokens/sec | Learning rate 0.00021598
Step 3881 | Loss 2.70 | Speed 2099 tokens/sec | Learning rate 0.00021588
Step 3921 | Loss 3.09 | Speed 1997 tokens/sec | Learning rate 0.00021577
Step 3961 | Loss 2.99 | Speed 2069 tokens/sec | Learning rate 0.00021567
Step 4001 | Loss 2.88 | Speed 2077 tokens/sec | Learning rate 0.00021557
Step 4041 | Loss 3.77 | Speed 2103 tokens/sec | Learning rate 0.00021547
Step 4081 | Loss 2.43 | Speed 1919 tokens/sec | Learning rate 0.00021536
Step 4121 | Loss 3.45 | Speed 2063 tokens/sec | Learning rate 0.00021526
Step 4161 | Loss 2.85 | Speed 1949 tokens/sec | Learning rate 0.00021516
Step 4201 | Loss 2.63 | Speed 2132 tokens/sec | Learning rate 0.00021506
Step 4241 | Loss 3.17 | Speed 2079 tokens/sec | Learning rate 0.00021496
Step 4281 | Loss 2.89 | Speed 2177 tokens/sec | Learning rate 0.00021485
Step 4321 | Loss 2.82 | Speed 1960 tokens/sec | Learning rate 0.00021475
Step 4361 | Loss 2.77 | Speed 2013 tokens/sec | Learning rate 0.00021465
Step 4401 | Loss 3.32 | Speed 1991 tokens/sec | Learning rate 0.00021455
Step 4441 | Loss 3.14 | Speed 2213 tokens/sec | Learning rate 0.00021445
Saved dailydialog_local38k8e_step_42500.pt
Saved dailydialog_local38k8e_last.pt
Step 4481 | Loss 2.16 | Speed 1020 tokens/sec | Learning rate 0.00021435
Step 4521 | Loss 2.93 | Speed 1995 tokens/sec | Learning rate 0.00021425
Step 4561 | Loss 2.59 | Speed 2119 tokens/sec | Learning rate 0.00021415
Step 4601 | Loss 2.91 | Speed 2251 tokens/sec | Learning rate 0.00021405
Step 4641 | Loss 2.28 | Speed 2160 tokens/sec | Learning rate 0.00021395
Step 4681 | Loss 3.08 | Speed 2056 tokens/sec | Learning rate 0.00021385
Step 4721 | Loss 2.62 | Speed 2068 tokens/sec | Learning rate 0.00021375
Step 4761 | Loss 3.16 | Speed 2116 tokens/sec | Learning rate 0.00021365
Step 4801 | Loss 3.33 | Speed 2193 tokens/sec | Learning rate 0.00021355
Step 4841 | Loss 2.81 | Speed 2118 tokens/sec | Learning rate 0.00021345
Step 4881 | Loss 2.61 | Speed 2009 tokens/sec | Learning rate 0.00021335
Step 4921 | Loss 2.99 | Speed 2134 tokens/sec | Learning rate 0.00021325
Step 4961 | Loss 2.19 | Speed 2127 tokens/sec | Learning rate 0.00021315
Step 5001 | Loss 2.60 | Speed 2116 tokens/sec | Learning rate 0.00021305
Step 5041 | Loss 2.85 | Speed 2056 tokens/sec | Learning rate 0.00021295
Step 5081 | Loss 2.51 | Speed 2230 tokens/sec | Learning rate 0.00021285
Step 5121 | Loss 2.92 | Speed 2041 tokens/sec | Learning rate 0.00021275
Step 5161 | Loss 3.02 | Speed 2072 tokens/sec | Learning rate 0.00021265
Step 5201 | Loss 3.09 | Speed 2161 tokens/sec | Learning rate 0.00021256
Step 5241 | Loss 2.82 | Speed 1977 tokens/sec | Learning rate 0.00021246
Step 5281 | Loss 2.83 | Speed 2164 tokens/sec | Learning rate 0.00021236
Step 5321 | Loss 2.97 | Speed 2033 tokens/sec | Learning rate 0.00021226
Step 5361 | Loss 2.85 | Speed 2033 tokens/sec | Learning rate 0.00021216
Step 5401 | Loss 3.14 | Speed 2088 tokens/sec | Learning rate 0.00021207
Step 5441 | Loss 3.06 | Speed 2134 tokens/sec | Learning rate 0.00021197
Step 5481 | Loss 3.10 | Speed 2118 tokens/sec | Learning rate 0.00021187
Step 5521 | Loss 2.96 | Speed 2050 tokens/sec | Learning rate 0.00021177
Step 5561 | Loss 2.90 | Speed 1977 tokens/sec | Learning rate 0.00021168
Step 5601 | Loss 2.53 | Speed 2165 tokens/sec | Learning rate 0.00021158
Step 5641 | Loss 3.13 | Speed 2061 tokens/sec | Learning rate 0.00021148
Step 5681 | Loss 2.72 | Speed 2057 tokens/sec | Learning rate 0.00021139
Step 5721 | Loss 2.56 | Speed 2101 tokens/sec | Learning rate 0.00021129
Step 5761 | Loss 2.88 | Speed 2110 tokens/sec | Learning rate 0.00021119
Step 5801 | Loss 2.98 | Speed 2076 tokens/sec | Learning rate 0.0002111
Step 5841 | Loss 2.99 | Speed 2051 tokens/sec | Learning rate 0.000211
Step 5881 | Loss 3.22 | Speed 2230 tokens/sec | Learning rate 0.0002109
Step 5921 | Loss 3.14 | Speed 1995 tokens/sec | Learning rate 0.00021081
Step 5961 | Loss 2.49 | Speed 2189 tokens/sec | Learning rate 0.00021071
Step 6001 | Loss 3.42 | Speed 2038 tokens/sec | Learning rate 0.00021062
Step 6041 | Loss 2.59 | Speed 2049 tokens/sec | Learning rate 0.00021052
Step 6081 | Loss 2.86 | Speed 2020 tokens/sec | Learning rate 0.00021042
Step 6121 | Loss 3.20 | Speed 2059 tokens/sec | Learning rate 0.00021033
Step 6161 | Loss 3.25 | Speed 2070 tokens/sec | Learning rate 0.00021023
Step 6201 | Loss 2.52 | Speed 2212 tokens/sec | Learning rate 0.00021014
Step 6241 | Loss 2.49 | Speed 2153 tokens/sec | Learning rate 0.00021004
Step 6281 | Loss 2.81 | Speed 1991 tokens/sec | Learning rate 0.00020995
Step 6321 | Loss 2.61 | Speed 1927 tokens/sec | Learning rate 0.00020985
Step 6361 | Loss 2.73 | Speed 1899 tokens/sec | Learning rate 0.00020976
Step 6401 | Loss 2.44 | Speed 2160 tokens/sec | Learning rate 0.00020967
Step 6441 | Loss 3.47 | Speed 2247 tokens/sec | Learning rate 0.00020957
Step 6481 | Loss 3.15 | Speed 1942 tokens/sec | Learning rate 0.00020948
Step 6521 | Loss 3.50 | Speed 2016 tokens/sec | Learning rate 0.00020938
Step 6561 | Loss 2.79 | Speed 2102 tokens/sec | Learning rate 0.00020929
Step 6601 | Loss 3.21 | Speed 2050 tokens/sec | Learning rate 0.0002092
Step 6641 | Loss 3.17 | Speed 2120 tokens/sec | Learning rate 0.0002091
Step 6681 | Loss 2.96 | Speed 2083 tokens/sec | Learning rate 0.00020901
Step 6721 | Loss 3.23 | Speed 2228 tokens/sec | Learning rate 0.00020891
Step 6761 | Loss 2.74 | Speed 2176 tokens/sec | Learning rate 0.00020882
Step 6801 | Loss 2.82 | Speed 2030 tokens/sec | Learning rate 0.00020873
Step 6841 | Loss 2.81 | Speed 2026 tokens/sec | Learning rate 0.00020863
Step 6881 | Loss 3.21 | Speed 2064 tokens/sec | Learning rate 0.00020854
Step 6921 | Loss 2.58 | Speed 2187 tokens/sec | Learning rate 0.00020845
Step 6961 | Loss 2.96 | Speed 2125 tokens/sec | Learning rate 0.00020836
Saved dailydialog_local38k8e_step_45000.pt
Saved dailydialog_local38k8e_last.pt
Step 7001 | Loss 3.10 | Speed 1138 tokens/sec | Learning rate 0.00020826
Step 7041 | Loss 2.45 | Speed 2245 tokens/sec | Learning rate 0.00020817
Step 7081 | Loss 2.76 | Speed 2039 tokens/sec | Learning rate 0.00020808
Step 7121 | Loss 2.15 | Speed 2100 tokens/sec | Learning rate 0.00020799
Step 7161 | Loss 3.05 | Speed 2162 tokens/sec | Learning rate 0.00020789
Step 7201 | Loss 3.19 | Speed 2061 tokens/sec | Learning rate 0.0002078
Step 7241 | Loss 2.69 | Speed 2234 tokens/sec | Learning rate 0.00020771
Step 7281 | Loss 3.33 | Speed 2248 tokens/sec | Learning rate 0.00020762
Step 7321 | Loss 2.75 | Speed 2179 tokens/sec | Learning rate 0.00020753
Step 7361 | Loss 2.96 | Speed 1941 tokens/sec | Learning rate 0.00020744
Step 7401 | Loss 2.12 | Speed 2114 tokens/sec | Learning rate 0.00020735
Step 7441 | Loss 3.21 | Speed 2109 tokens/sec | Learning rate 0.00020725
Step 7481 | Loss 2.11 | Speed 2271 tokens/sec | Learning rate 0.00020716
Step 7521 | Loss 2.99 | Speed 2079 tokens/sec | Learning rate 0.00020707
Step 7561 | Loss 2.84 | Speed 2086 tokens/sec | Learning rate 0.00020698
Step 7601 | Loss 2.98 | Speed 1928 tokens/sec | Learning rate 0.00020689
Step 7641 | Loss 3.54 | Speed 2133 tokens/sec | Learning rate 0.0002068
Step 7681 | Loss 2.86 | Speed 1976 tokens/sec | Learning rate 0.00020671
Step 7721 | Loss 2.73 | Speed 1984 tokens/sec | Learning rate 0.00020662
Step 7761 | Loss 3.04 | Speed 2131 tokens/sec | Learning rate 0.00020653
Step 7801 | Loss 2.74 | Speed 2036 tokens/sec | Learning rate 0.00020644
Step 7841 | Loss 2.64 | Speed 2174 tokens/sec | Learning rate 0.00020635
Step 7881 | Loss 2.18 | Speed 2156 tokens/sec | Learning rate 0.00020626
Step 7921 | Loss 3.01 | Speed 1986 tokens/sec | Learning rate 0.00020617
Step 7961 | Loss 2.60 | Speed 2191 tokens/sec | Learning rate 0.00020608
Step 8001 | Loss 2.67 | Speed 1912 tokens/sec | Learning rate 0.00020599
Step 8041 | Loss 2.99 | Speed 1921 tokens/sec | Learning rate 0.0002059
Step 8081 | Loss 2.63 | Speed 1974 tokens/sec | Learning rate 0.00020581
Step 8121 | Loss 3.26 | Speed 2007 tokens/sec | Learning rate 0.00020572
Step 8161 | Loss 2.81 | Speed 1938 tokens/sec | Learning rate 0.00020563
Step 8201 | Loss 3.35 | Speed 2103 tokens/sec | Learning rate 0.00020554
Step 8241 | Loss 3.40 | Speed 2101 tokens/sec | Learning rate 0.00020545
Step 8281 | Loss 2.68 | Speed 2142 tokens/sec | Learning rate 0.00020537
Step 8321 | Loss 3.64 | Speed 2109 tokens/sec | Learning rate 0.00020528
Step 8361 | Loss 3.10 | Speed 2020 tokens/sec | Learning rate 0.00020519
Step 8401 | Loss 3.44 | Speed 2147 tokens/sec | Learning rate 0.0002051
Step 8441 | Loss 2.59 | Speed 2187 tokens/sec | Learning rate 0.00020501
Step 8481 | Loss 2.97 | Speed 2137 tokens/sec | Learning rate 0.00020492
Step 8521 | Loss 2.89 | Speed 1959 tokens/sec | Learning rate 0.00020484
Step 8561 | Loss 2.76 | Speed 2142 tokens/sec | Learning rate 0.00020475
Step 8601 | Loss 3.36 | Speed 1953 tokens/sec | Learning rate 0.00020466
Step 8641 | Loss 2.40 | Speed 2003 tokens/sec | Learning rate 0.00020457
Step 8681 | Loss 2.75 | Speed 2074 tokens/sec | Learning rate 0.00020448
Step 8721 | Loss 3.02 | Speed 2098 tokens/sec | Learning rate 0.0002044
Step 8761 | Loss 2.92 | Speed 2018 tokens/sec | Learning rate 0.00020431
Step 8801 | Loss 2.93 | Speed 1935 tokens/sec | Learning rate 0.00020422
Step 8841 | Loss 2.79 | Speed 2070 tokens/sec | Learning rate 0.00020414
Step 8881 | Loss 2.98 | Speed 2003 tokens/sec | Learning rate 0.00020405
Step 8921 | Loss 2.95 | Speed 2058 tokens/sec | Learning rate 0.00020396
Step 8961 | Loss 2.77 | Speed 2045 tokens/sec | Learning rate 0.00020387
Step 9001 | Loss 2.71 | Speed 2088 tokens/sec | Learning rate 0.00020379
Step 9041 | Loss 3.09 | Speed 1955 tokens/sec | Learning rate 0.0002037
Step 9081 | Loss 2.59 | Speed 2041 tokens/sec | Learning rate 0.00020361
Step 9121 | Loss 2.91 | Speed 2225 tokens/sec | Learning rate 0.00020353
Step 9161 | Loss 2.81 | Speed 1951 tokens/sec | Learning rate 0.00020344
Step 9201 | Loss 2.55 | Speed 2017 tokens/sec | Learning rate 0.00020336
Step 9241 | Loss 2.95 | Speed 2008 tokens/sec | Learning rate 0.00020327
Step 9281 | Loss 3.13 | Speed 2126 tokens/sec | Learning rate 0.00020318
Step 9321 | Loss 2.81 | Speed 2085 tokens/sec | Learning rate 0.0002031
Step 9361 | Loss 2.71 | Speed 1925 tokens/sec | Learning rate 0.00020301
Step 9401 | Loss 2.95 | Speed 2047 tokens/sec | Learning rate 0.00020293
Step 9441 | Loss 2.96 | Speed 1992 tokens/sec | Learning rate 0.00020284
Saved dailydialog_local38k8e_step_47500.pt
Saved dailydialog_local38k8e_last.pt
Step 9481 | Loss 2.45 | Speed 1070 tokens/sec | Learning rate 0.00020276
| ID | GPU | MEM |
------------------
|  0 | 90% | 27% |
Epoch 4 Validation ====
Validation loss: 3.0543
[█████████████████░░░░░░░░░░░]  epoch 5/8 complete
  train_loss=2.9795  val_loss=3.0543  steps=47535  tokens_seen=5741795

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_4.pt
Saved dailydialog_local38k8e_last.pt
Epoch 5 Training ====
Step 1 | Loss 2.67 | Speed 1970 tokens/sec | Learning rate 0.0002027
Step 41 | Loss 2.87 | Speed 2061 tokens/sec | Learning rate 0.00020261
Step 81 | Loss 2.81 | Speed 1927 tokens/sec | Learning rate 0.00020253
Step 121 | Loss 2.84 | Speed 2071 tokens/sec | Learning rate 0.00020244
Step 161 | Loss 2.61 | Speed 2191 tokens/sec | Learning rate 0.00020236
Step 201 | Loss 2.69 | Speed 2128 tokens/sec | Learning rate 0.00020227
Step 241 | Loss 2.50 | Speed 2077 tokens/sec | Learning rate 0.00020219
Step 281 | Loss 3.04 | Speed 2035 tokens/sec | Learning rate 0.0002021
Step 321 | Loss 2.64 | Speed 2090 tokens/sec | Learning rate 0.00020202
Step 361 | Loss 2.94 | Speed 1907 tokens/sec | Learning rate 0.00020193
Step 401 | Loss 2.87 | Speed 2061 tokens/sec | Learning rate 0.00020185
Step 441 | Loss 3.03 | Speed 2097 tokens/sec | Learning rate 0.00020177
Step 481 | Loss 2.90 | Speed 1971 tokens/sec | Learning rate 0.00020168
Step 521 | Loss 2.55 | Speed 1933 tokens/sec | Learning rate 0.0002016
Step 561 | Loss 2.61 | Speed 2063 tokens/sec | Learning rate 0.00020151
Step 601 | Loss 2.73 | Speed 2019 tokens/sec | Learning rate 0.00020143
Step 641 | Loss 2.77 | Speed 1978 tokens/sec | Learning rate 0.00020135
Step 681 | Loss 3.01 | Speed 1973 tokens/sec | Learning rate 0.00020126
Step 721 | Loss 3.03 | Speed 2095 tokens/sec | Learning rate 0.00020118
Step 761 | Loss 2.83 | Speed 1932 tokens/sec | Learning rate 0.0002011
Step 801 | Loss 2.71 | Speed 2062 tokens/sec | Learning rate 0.00020101
Step 841 | Loss 2.86 | Speed 2047 tokens/sec | Learning rate 0.00020093
Step 881 | Loss 2.79 | Speed 2069 tokens/sec | Learning rate 0.00020085
Step 921 | Loss 2.64 | Speed 2068 tokens/sec | Learning rate 0.00020076
Step 961 | Loss 3.03 | Speed 1835 tokens/sec | Learning rate 0.00020068
Step 1001 | Loss 2.57 | Speed 2250 tokens/sec | Learning rate 0.0002006
Step 1041 | Loss 2.76 | Speed 1975 tokens/sec | Learning rate 0.00020052
Step 1081 | Loss 2.89 | Speed 2093 tokens/sec | Learning rate 0.00020043
Step 1121 | Loss 2.60 | Speed 1958 tokens/sec | Learning rate 0.00020035
Step 1161 | Loss 3.13 | Speed 2108 tokens/sec | Learning rate 0.00020027
Step 1201 | Loss 2.69 | Speed 2095 tokens/sec | Learning rate 0.00020019
Step 1241 | Loss 3.11 | Speed 1984 tokens/sec | Learning rate 0.0002001
Step 1281 | Loss 2.68 | Speed 2133 tokens/sec | Learning rate 0.00020002
Step 1321 | Loss 2.87 | Speed 2154 tokens/sec | Learning rate 0.00019994
Step 1361 | Loss 2.69 | Speed 2112 tokens/sec | Learning rate 0.00019986
Step 1401 | Loss 2.98 | Speed 2169 tokens/sec | Learning rate 0.00019978
Step 1441 | Loss 2.71 | Speed 2078 tokens/sec | Learning rate 0.0001997
Step 1481 | Loss 3.16 | Speed 1975 tokens/sec | Learning rate 0.00019961
Step 1521 | Loss 3.35 | Speed 2027 tokens/sec | Learning rate 0.00019953
Step 1561 | Loss 3.17 | Speed 2005 tokens/sec | Learning rate 0.00019945
Step 1601 | Loss 3.27 | Speed 2005 tokens/sec | Learning rate 0.00019937
Step 1641 | Loss 2.56 | Speed 2114 tokens/sec | Learning rate 0.00019929
Step 1681 | Loss 2.65 | Speed 2047 tokens/sec | Learning rate 0.00019921
Step 1721 | Loss 3.11 | Speed 2072 tokens/sec | Learning rate 0.00019913
Step 1761 | Loss 2.96 | Speed 2177 tokens/sec | Learning rate 0.00019905
Step 1801 | Loss 2.98 | Speed 2131 tokens/sec | Learning rate 0.00019897
Step 1841 | Loss 3.29 | Speed 2092 tokens/sec | Learning rate 0.00019889
Step 1881 | Loss 2.78 | Speed 2035 tokens/sec | Learning rate 0.0001988
Step 1921 | Loss 2.50 | Speed 2055 tokens/sec | Learning rate 0.00019872
Step 1961 | Loss 2.95 | Speed 1901 tokens/sec | Learning rate 0.00019864
Step 2001 | Loss 2.62 | Speed 2110 tokens/sec | Learning rate 0.00019856
Step 2041 | Loss 2.65 | Speed 1946 tokens/sec | Learning rate 0.00019848
Step 2081 | Loss 2.63 | Speed 2076 tokens/sec | Learning rate 0.0001984
Step 2121 | Loss 2.99 | Speed 2142 tokens/sec | Learning rate 0.00019832
Step 2161 | Loss 3.18 | Speed 2179 tokens/sec | Learning rate 0.00019824
Step 2201 | Loss 3.21 | Speed 2187 tokens/sec | Learning rate 0.00019816
Step 2241 | Loss 3.41 | Speed 2187 tokens/sec | Learning rate 0.00019808
Step 2281 | Loss 3.08 | Speed 1978 tokens/sec | Learning rate 0.00019801
Step 2321 | Loss 2.85 | Speed 2140 tokens/sec | Learning rate 0.00019793
Step 2361 | Loss 2.85 | Speed 2060 tokens/sec | Learning rate 0.00019785
Step 2401 | Loss 2.59 | Speed 2111 tokens/sec | Learning rate 0.00019777
Step 2441 | Loss 3.63 | Speed 2139 tokens/sec | Learning rate 0.00019769
Saved dailydialog_local38k8e_step_50000.pt
Saved dailydialog_local38k8e_last.pt
Step 2481 | Loss 3.74 | Speed 1288 tokens/sec | Learning rate 0.00019761
Step 2521 | Loss 3.04 | Speed 2135 tokens/sec | Learning rate 0.00019753
Step 2561 | Loss 2.10 | Speed 1943 tokens/sec | Learning rate 0.00019745
Step 2601 | Loss 2.45 | Speed 1997 tokens/sec | Learning rate 0.00019737
Step 2641 | Loss 3.08 | Speed 2146 tokens/sec | Learning rate 0.00019729
Step 2681 | Loss 2.62 | Speed 2020 tokens/sec | Learning rate 0.00019721
Step 2721 | Loss 2.43 | Speed 2079 tokens/sec | Learning rate 0.00019714
Step 2761 | Loss 2.88 | Speed 2036 tokens/sec | Learning rate 0.00019706
Step 2801 | Loss 3.33 | Speed 2082 tokens/sec | Learning rate 0.00019698
Step 2841 | Loss 3.07 | Speed 1974 tokens/sec | Learning rate 0.0001969
Step 2881 | Loss 2.75 | Speed 2073 tokens/sec | Learning rate 0.00019682
Step 2921 | Loss 2.74 | Speed 2019 tokens/sec | Learning rate 0.00019675
Step 2961 | Loss 2.96 | Speed 1876 tokens/sec | Learning rate 0.00019667
Step 3001 | Loss 2.49 | Speed 2222 tokens/sec | Learning rate 0.00019659
Step 3041 | Loss 3.03 | Speed 1952 tokens/sec | Learning rate 0.00019651
Step 3081 | Loss 2.71 | Speed 2056 tokens/sec | Learning rate 0.00019643
Step 3121 | Loss 2.93 | Speed 2024 tokens/sec | Learning rate 0.00019636
Step 3161 | Loss 2.81 | Speed 2037 tokens/sec | Learning rate 0.00019628
Step 3201 | Loss 2.73 | Speed 2056 tokens/sec | Learning rate 0.0001962
Step 3241 | Loss 2.90 | Speed 2061 tokens/sec | Learning rate 0.00019612
Step 3281 | Loss 2.96 | Speed 2161 tokens/sec | Learning rate 0.00019605
Step 3321 | Loss 3.56 | Speed 2033 tokens/sec | Learning rate 0.00019597
Step 3361 | Loss 2.90 | Speed 2114 tokens/sec | Learning rate 0.00019589
Step 3401 | Loss 2.46 | Speed 2104 tokens/sec | Learning rate 0.00019582
Step 3441 | Loss 2.65 | Speed 2023 tokens/sec | Learning rate 0.00019574
Step 3481 | Loss 2.67 | Speed 1954 tokens/sec | Learning rate 0.00019566
Step 3521 | Loss 2.95 | Speed 1962 tokens/sec | Learning rate 0.00019559
Step 3561 | Loss 2.94 | Speed 2211 tokens/sec | Learning rate 0.00019551
Step 3601 | Loss 3.58 | Speed 2064 tokens/sec | Learning rate 0.00019543
Step 3641 | Loss 2.72 | Speed 1911 tokens/sec | Learning rate 0.00019536
Step 3681 | Loss 2.69 | Speed 1965 tokens/sec | Learning rate 0.00019528
Step 3721 | Loss 2.00 | Speed 2180 tokens/sec | Learning rate 0.0001952
Step 3761 | Loss 3.13 | Speed 1983 tokens/sec | Learning rate 0.00019513
Step 3801 | Loss 3.27 | Speed 2211 tokens/sec | Learning rate 0.00019505
Step 3841 | Loss 2.06 | Speed 2167 tokens/sec | Learning rate 0.00019498
Step 3881 | Loss 2.67 | Speed 2063 tokens/sec | Learning rate 0.0001949
Step 3921 | Loss 3.03 | Speed 2109 tokens/sec | Learning rate 0.00019482
Step 3961 | Loss 2.84 | Speed 1964 tokens/sec | Learning rate 0.00019475
Step 4001 | Loss 2.49 | Speed 2051 tokens/sec | Learning rate 0.00019467
Step 4041 | Loss 3.30 | Speed 2097 tokens/sec | Learning rate 0.0001946
Step 4081 | Loss 3.32 | Speed 1927 tokens/sec | Learning rate 0.00019452
Step 4121 | Loss 2.92 | Speed 2085 tokens/sec | Learning rate 0.00019445
Step 4161 | Loss 2.48 | Speed 2091 tokens/sec | Learning rate 0.00019437
Step 4201 | Loss 2.76 | Speed 2159 tokens/sec | Learning rate 0.0001943
Step 4241 | Loss 2.80 | Speed 1982 tokens/sec | Learning rate 0.00019422
Step 4281 | Loss 3.12 | Speed 2014 tokens/sec | Learning rate 0.00019415
Step 4321 | Loss 2.41 | Speed 2283 tokens/sec | Learning rate 0.00019407
Step 4361 | Loss 3.14 | Speed 2096 tokens/sec | Learning rate 0.000194
Step 4401 | Loss 2.66 | Speed 1942 tokens/sec | Learning rate 0.00019392
Step 4441 | Loss 2.37 | Speed 2097 tokens/sec | Learning rate 0.00019385
Step 4481 | Loss 3.08 | Speed 2162 tokens/sec | Learning rate 0.00019377
Step 4521 | Loss 3.34 | Speed 2048 tokens/sec | Learning rate 0.0001937
Step 4561 | Loss 3.21 | Speed 1998 tokens/sec | Learning rate 0.00019362
Step 4601 | Loss 2.88 | Speed 2058 tokens/sec | Learning rate 0.00019355
Step 4641 | Loss 3.22 | Speed 1871 tokens/sec | Learning rate 0.00019348
Step 4681 | Loss 2.39 | Speed 1809 tokens/sec | Learning rate 0.0001934
Step 4721 | Loss 2.57 | Speed 2057 tokens/sec | Learning rate 0.00019333
Step 4761 | Loss 2.22 | Speed 2036 tokens/sec | Learning rate 0.00019325
Step 4801 | Loss 3.12 | Speed 1994 tokens/sec | Learning rate 0.00019318
Step 4841 | Loss 2.90 | Speed 1940 tokens/sec | Learning rate 0.00019311
Step 4881 | Loss 2.97 | Speed 1786 tokens/sec | Learning rate 0.00019303
Step 4921 | Loss 2.70 | Speed 1977 tokens/sec | Learning rate 0.00019296
Step 4961 | Loss 3.20 | Speed 1804 tokens/sec | Learning rate 0.00019288
Saved dailydialog_local38k8e_step_52500.pt
Saved dailydialog_local38k8e_last.pt
Step 5001 | Loss 2.77 | Speed 958 tokens/sec | Learning rate 0.00019281
Step 5041 | Loss 3.26 | Speed 1836 tokens/sec | Learning rate 0.00019274
Step 5081 | Loss 2.48 | Speed 1870 tokens/sec | Learning rate 0.00019266
Step 5121 | Loss 2.86 | Speed 1999 tokens/sec | Learning rate 0.00019259
Step 5161 | Loss 2.50 | Speed 1954 tokens/sec | Learning rate 0.00019252
Step 5201 | Loss 3.32 | Speed 2219 tokens/sec | Learning rate 0.00019245
Step 5241 | Loss 3.12 | Speed 2065 tokens/sec | Learning rate 0.00019237
Step 5281 | Loss 3.81 | Speed 2027 tokens/sec | Learning rate 0.0001923
Step 5321 | Loss 3.60 | Speed 1857 tokens/sec | Learning rate 0.00019223
Step 5361 | Loss 2.47 | Speed 2109 tokens/sec | Learning rate 0.00019215
Step 5401 | Loss 3.06 | Speed 2125 tokens/sec | Learning rate 0.00019208
Step 5441 | Loss 2.75 | Speed 2314 tokens/sec | Learning rate 0.00019201
Step 5481 | Loss 3.24 | Speed 2120 tokens/sec | Learning rate 0.00019194
Step 5521 | Loss 3.07 | Speed 2074 tokens/sec | Learning rate 0.00019186
Step 5561 | Loss 2.89 | Speed 1951 tokens/sec | Learning rate 0.00019179
Step 5601 | Loss 3.19 | Speed 1860 tokens/sec | Learning rate 0.00019172
Step 5641 | Loss 2.60 | Speed 1921 tokens/sec | Learning rate 0.00019165
Step 5681 | Loss 2.92 | Speed 2062 tokens/sec | Learning rate 0.00019158
Step 5721 | Loss 2.47 | Speed 2128 tokens/sec | Learning rate 0.0001915
Step 5761 | Loss 3.13 | Speed 2046 tokens/sec | Learning rate 0.00019143
Step 5801 | Loss 3.01 | Speed 2140 tokens/sec | Learning rate 0.00019136
Step 5841 | Loss 2.97 | Speed 2028 tokens/sec | Learning rate 0.00019129
Step 5881 | Loss 2.96 | Speed 2118 tokens/sec | Learning rate 0.00019122
Step 5921 | Loss 3.14 | Speed 1948 tokens/sec | Learning rate 0.00019114
Step 5961 | Loss 3.26 | Speed 2235 tokens/sec | Learning rate 0.00019107
Step 6001 | Loss 3.05 | Speed 2151 tokens/sec | Learning rate 0.000191
Step 6041 | Loss 2.92 | Speed 2119 tokens/sec | Learning rate 0.00019093
Step 6081 | Loss 3.08 | Speed 2115 tokens/sec | Learning rate 0.00019086
Step 6121 | Loss 3.02 | Speed 2151 tokens/sec | Learning rate 0.00019079
Step 6161 | Loss 3.01 | Speed 1965 tokens/sec | Learning rate 0.00019072
Step 6201 | Loss 2.64 | Speed 2119 tokens/sec | Learning rate 0.00019065
Step 6241 | Loss 2.75 | Speed 2088 tokens/sec | Learning rate 0.00019058
Step 6281 | Loss 2.93 | Speed 2053 tokens/sec | Learning rate 0.0001905
Step 6321 | Loss 3.09 | Speed 2157 tokens/sec | Learning rate 0.00019043
Step 6361 | Loss 2.89 | Speed 1955 tokens/sec | Learning rate 0.00019036
Step 6401 | Loss 2.58 | Speed 1874 tokens/sec | Learning rate 0.00019029
Step 6441 | Loss 2.93 | Speed 2182 tokens/sec | Learning rate 0.00019022
Step 6481 | Loss 3.27 | Speed 2073 tokens/sec | Learning rate 0.00019015
Step 6521 | Loss 2.79 | Speed 2109 tokens/sec | Learning rate 0.00019008
Step 6561 | Loss 2.98 | Speed 1952 tokens/sec | Learning rate 0.00019001
Step 6601 | Loss 3.15 | Speed 2080 tokens/sec | Learning rate 0.00018994
Step 6641 | Loss 3.17 | Speed 2070 tokens/sec | Learning rate 0.00018987
Step 6681 | Loss 2.59 | Speed 2020 tokens/sec | Learning rate 0.0001898
Step 6721 | Loss 3.25 | Speed 2030 tokens/sec | Learning rate 0.00018973
Step 6761 | Loss 2.70 | Speed 2089 tokens/sec | Learning rate 0.00018966
Step 6801 | Loss 2.87 | Speed 2047 tokens/sec | Learning rate 0.00018959
Step 6841 | Loss 2.59 | Speed 2057 tokens/sec | Learning rate 0.00018952
Step 6881 | Loss 2.42 | Speed 2045 tokens/sec | Learning rate 0.00018945
Step 6921 | Loss 2.94 | Speed 2116 tokens/sec | Learning rate 0.00018938
Step 6961 | Loss 3.41 | Speed 2039 tokens/sec | Learning rate 0.00018931
Step 7001 | Loss 2.89 | Speed 2163 tokens/sec | Learning rate 0.00018924
Step 7041 | Loss 2.97 | Speed 2126 tokens/sec | Learning rate 0.00018917
Step 7081 | Loss 2.78 | Speed 2110 tokens/sec | Learning rate 0.0001891
Step 7121 | Loss 2.68 | Speed 2101 tokens/sec | Learning rate 0.00018903
Step 7161 | Loss 3.03 | Speed 2032 tokens/sec | Learning rate 0.00018897
Step 7201 | Loss 2.71 | Speed 2128 tokens/sec | Learning rate 0.0001889
Step 7241 | Loss 2.61 | Speed 2043 tokens/sec | Learning rate 0.00018883
Step 7281 | Loss 3.07 | Speed 2090 tokens/sec | Learning rate 0.00018876
Step 7321 | Loss 2.92 | Speed 2061 tokens/sec | Learning rate 0.00018869
Step 7361 | Loss 3.04 | Speed 1981 tokens/sec | Learning rate 0.00018862
Step 7401 | Loss 2.44 | Speed 2051 tokens/sec | Learning rate 0.00018855
Step 7441 | Loss 2.75 | Speed 2138 tokens/sec | Learning rate 0.00018848
Saved dailydialog_local38k8e_step_55000.pt
Saved dailydialog_local38k8e_last.pt
Step 7481 | Loss 2.73 | Speed 1228 tokens/sec | Learning rate 0.00018842
Step 7521 | Loss 3.29 | Speed 2176 tokens/sec | Learning rate 0.00018835
Step 7561 | Loss 2.59 | Speed 2034 tokens/sec | Learning rate 0.00018828
Step 7601 | Loss 2.65 | Speed 2254 tokens/sec | Learning rate 0.00018821
Step 7641 | Loss 3.14 | Speed 2217 tokens/sec | Learning rate 0.00018814
Step 7681 | Loss 3.10 | Speed 1993 tokens/sec | Learning rate 0.00018807
Step 7721 | Loss 3.14 | Speed 2278 tokens/sec | Learning rate 0.00018801
Step 7761 | Loss 3.26 | Speed 2043 tokens/sec | Learning rate 0.00018794
Step 7801 | Loss 3.41 | Speed 2110 tokens/sec | Learning rate 0.00018787
Step 7841 | Loss 2.86 | Speed 2146 tokens/sec | Learning rate 0.0001878
Step 7881 | Loss 2.86 | Speed 2209 tokens/sec | Learning rate 0.00018773
Step 7921 | Loss 2.79 | Speed 1998 tokens/sec | Learning rate 0.00018767
Step 7961 | Loss 2.68 | Speed 2075 tokens/sec | Learning rate 0.0001876
Step 8001 | Loss 3.16 | Speed 2029 tokens/sec | Learning rate 0.00018753
Step 8041 | Loss 2.73 | Speed 2187 tokens/sec | Learning rate 0.00018746
Step 8081 | Loss 2.82 | Speed 2074 tokens/sec | Learning rate 0.0001874
Step 8121 | Loss 3.09 | Speed 2066 tokens/sec | Learning rate 0.00018733
Step 8161 | Loss 2.94 | Speed 2004 tokens/sec | Learning rate 0.00018726
Step 8201 | Loss 2.98 | Speed 2146 tokens/sec | Learning rate 0.00018719
Step 8241 | Loss 2.82 | Speed 2043 tokens/sec | Learning rate 0.00018713
Step 8281 | Loss 3.03 | Speed 2027 tokens/sec | Learning rate 0.00018706
Step 8321 | Loss 3.27 | Speed 2152 tokens/sec | Learning rate 0.00018699
Step 8361 | Loss 2.67 | Speed 2132 tokens/sec | Learning rate 0.00018693
Step 8401 | Loss 2.86 | Speed 2079 tokens/sec | Learning rate 0.00018686
Step 8441 | Loss 2.80 | Speed 2091 tokens/sec | Learning rate 0.00018679
Step 8481 | Loss 2.74 | Speed 2048 tokens/sec | Learning rate 0.00018673
Step 8521 | Loss 2.88 | Speed 2108 tokens/sec | Learning rate 0.00018666
Step 8561 | Loss 3.37 | Speed 1913 tokens/sec | Learning rate 0.00018659
Step 8601 | Loss 3.23 | Speed 2030 tokens/sec | Learning rate 0.00018653
Step 8641 | Loss 2.44 | Speed 2080 tokens/sec | Learning rate 0.00018646
Step 8681 | Loss 3.09 | Speed 2052 tokens/sec | Learning rate 0.00018639
Step 8721 | Loss 3.32 | Speed 1994 tokens/sec | Learning rate 0.00018633
Step 8761 | Loss 3.01 | Speed 2115 tokens/sec | Learning rate 0.00018626
Step 8801 | Loss 2.61 | Speed 1994 tokens/sec | Learning rate 0.0001862
Step 8841 | Loss 3.08 | Speed 2068 tokens/sec | Learning rate 0.00018613
Step 8881 | Loss 2.66 | Speed 2043 tokens/sec | Learning rate 0.00018606
Step 8921 | Loss 2.69 | Speed 2169 tokens/sec | Learning rate 0.000186
Step 8961 | Loss 2.46 | Speed 2112 tokens/sec | Learning rate 0.00018593
Step 9001 | Loss 3.06 | Speed 2137 tokens/sec | Learning rate 0.00018587
Step 9041 | Loss 1.79 | Speed 2108 tokens/sec | Learning rate 0.0001858
Step 9081 | Loss 3.05 | Speed 2199 tokens/sec | Learning rate 0.00018573
Step 9121 | Loss 2.98 | Speed 2301 tokens/sec | Learning rate 0.00018567
Step 9161 | Loss 2.63 | Speed 2030 tokens/sec | Learning rate 0.0001856
Step 9201 | Loss 1.80 | Speed 2103 tokens/sec | Learning rate 0.00018554
Step 9241 | Loss 2.86 | Speed 2081 tokens/sec | Learning rate 0.00018547
Step 9281 | Loss 2.57 | Speed 2175 tokens/sec | Learning rate 0.00018541
Step 9321 | Loss 3.39 | Speed 2027 tokens/sec | Learning rate 0.00018534
Step 9361 | Loss 2.61 | Speed 2076 tokens/sec | Learning rate 0.00018528
Step 9401 | Loss 2.75 | Speed 2093 tokens/sec | Learning rate 0.00018521
Step 9441 | Loss 3.24 | Speed 2160 tokens/sec | Learning rate 0.00018515
Step 9481 | Loss 2.43 | Speed 2064 tokens/sec | Learning rate 0.00018508
| ID | GPU | MEM |
------------------
|  0 | 88% | 27% |
Epoch 5 Validation ====
Validation loss: 3.0162
[█████████████████████░░░░░░░]  epoch 6/8 complete
  train_loss=2.8900  val_loss=3.0162  steps=57042  tokens_seen=6890154

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_5.pt
Saved dailydialog_local38k8e_last.pt
Epoch 6 Training ====
Step 1 | Loss 2.77 | Speed 2081 tokens/sec | Learning rate 0.00018504
Step 41 | Loss 2.83 | Speed 2019 tokens/sec | Learning rate 0.00018497
Step 81 | Loss 2.48 | Speed 2045 tokens/sec | Learning rate 0.00018491
Step 121 | Loss 2.75 | Speed 1954 tokens/sec | Learning rate 0.00018484
Step 161 | Loss 2.61 | Speed 2098 tokens/sec | Learning rate 0.00018478
Step 201 | Loss 2.66 | Speed 1966 tokens/sec | Learning rate 0.00018471
Step 241 | Loss 2.99 | Speed 2039 tokens/sec | Learning rate 0.00018465
Step 281 | Loss 2.48 | Speed 1976 tokens/sec | Learning rate 0.00018459
Step 321 | Loss 2.81 | Speed 2111 tokens/sec | Learning rate 0.00018452
Step 361 | Loss 2.51 | Speed 1947 tokens/sec | Learning rate 0.00018446
Step 401 | Loss 2.48 | Speed 1958 tokens/sec | Learning rate 0.00018439
Step 441 | Loss 2.39 | Speed 2105 tokens/sec | Learning rate 0.00018433
Saved dailydialog_local38k8e_step_57500.pt
Saved dailydialog_local38k8e_last.pt
Step 481 | Loss 2.52 | Speed 1045 tokens/sec | Learning rate 0.00018426
Step 521 | Loss 3.09 | Speed 2020 tokens/sec | Learning rate 0.0001842
Step 561 | Loss 2.69 | Speed 2135 tokens/sec | Learning rate 0.00018414
Step 601 | Loss 2.44 | Speed 2063 tokens/sec | Learning rate 0.00018407
Step 641 | Loss 2.83 | Speed 1939 tokens/sec | Learning rate 0.00018401
Step 681 | Loss 2.61 | Speed 2016 tokens/sec | Learning rate 0.00018394
Step 721 | Loss 2.78 | Speed 2166 tokens/sec | Learning rate 0.00018388
Step 761 | Loss 2.88 | Speed 2049 tokens/sec | Learning rate 0.00018382
Step 801 | Loss 2.44 | Speed 2069 tokens/sec | Learning rate 0.00018375
Step 841 | Loss 2.85 | Speed 2124 tokens/sec | Learning rate 0.00018369
Step 881 | Loss 3.24 | Speed 2119 tokens/sec | Learning rate 0.00018363
Step 921 | Loss 2.80 | Speed 2110 tokens/sec | Learning rate 0.00018356
Step 961 | Loss 2.52 | Speed 2241 tokens/sec | Learning rate 0.0001835
Step 1001 | Loss 2.99 | Speed 2216 tokens/sec | Learning rate 0.00018344
Step 1041 | Loss 2.83 | Speed 1991 tokens/sec | Learning rate 0.00018337
Step 1081 | Loss 2.27 | Speed 2368 tokens/sec | Learning rate 0.00018331
Step 1121 | Loss 2.67 | Speed 2170 tokens/sec | Learning rate 0.00018325
Step 1161 | Loss 2.53 | Speed 2021 tokens/sec | Learning rate 0.00018318
Step 1201 | Loss 2.65 | Speed 2090 tokens/sec | Learning rate 0.00018312
Step 1241 | Loss 3.38 | Speed 2230 tokens/sec | Learning rate 0.00018306
Step 1281 | Loss 3.19 | Speed 2036 tokens/sec | Learning rate 0.000183
Step 1321 | Loss 2.59 | Speed 2098 tokens/sec | Learning rate 0.00018293
Step 1361 | Loss 2.60 | Speed 2172 tokens/sec | Learning rate 0.00018287
Step 1401 | Loss 3.22 | Speed 1870 tokens/sec | Learning rate 0.00018281
Step 1441 | Loss 2.24 | Speed 2114 tokens/sec | Learning rate 0.00018275
Step 1481 | Loss 2.94 | Speed 2216 tokens/sec | Learning rate 0.00018268
Step 1521 | Loss 2.61 | Speed 2265 tokens/sec | Learning rate 0.00018262
Step 1561 | Loss 2.60 | Speed 1990 tokens/sec | Learning rate 0.00018256
Step 1601 | Loss 3.12 | Speed 2053 tokens/sec | Learning rate 0.0001825
Step 1641 | Loss 2.70 | Speed 2119 tokens/sec | Learning rate 0.00018243
Step 1681 | Loss 3.18 | Speed 2142 tokens/sec | Learning rate 0.00018237
Step 1721 | Loss 2.76 | Speed 2130 tokens/sec | Learning rate 0.00018231
Step 1761 | Loss 2.74 | Speed 2062 tokens/sec | Learning rate 0.00018225
Step 1801 | Loss 3.03 | Speed 2102 tokens/sec | Learning rate 0.00018219
Step 1841 | Loss 3.27 | Speed 2133 tokens/sec | Learning rate 0.00018212
Step 1881 | Loss 2.88 | Speed 2075 tokens/sec | Learning rate 0.00018206
Step 1921 | Loss 2.40 | Speed 2186 tokens/sec | Learning rate 0.000182
Step 1961 | Loss 3.44 | Speed 1938 tokens/sec | Learning rate 0.00018194
Step 2001 | Loss 3.30 | Speed 2062 tokens/sec | Learning rate 0.00018188
Step 2041 | Loss 2.70 | Speed 2073 tokens/sec | Learning rate 0.00018182
Step 2081 | Loss 2.66 | Speed 2054 tokens/sec | Learning rate 0.00018175
Step 2121 | Loss 2.22 | Speed 2053 tokens/sec | Learning rate 0.00018169
Step 2161 | Loss 2.47 | Speed 2056 tokens/sec | Learning rate 0.00018163
Step 2201 | Loss 2.33 | Speed 2144 tokens/sec | Learning rate 0.00018157
Step 2241 | Loss 2.88 | Speed 2221 tokens/sec | Learning rate 0.00018151
Step 2281 | Loss 2.66 | Speed 2049 tokens/sec | Learning rate 0.00018145
Step 2321 | Loss 2.61 | Speed 2140 tokens/sec | Learning rate 0.00018139
Step 2361 | Loss 2.92 | Speed 2047 tokens/sec | Learning rate 0.00018132
Step 2401 | Loss 2.75 | Speed 2158 tokens/sec | Learning rate 0.00018126
Step 2441 | Loss 2.49 | Speed 2091 tokens/sec | Learning rate 0.0001812
Step 2481 | Loss 3.33 | Speed 2229 tokens/sec | Learning rate 0.00018114
Step 2521 | Loss 2.21 | Speed 2062 tokens/sec | Learning rate 0.00018108
Step 2561 | Loss 2.70 | Speed 2018 tokens/sec | Learning rate 0.00018102
Step 2601 | Loss 2.64 | Speed 2117 tokens/sec | Learning rate 0.00018096
Step 2641 | Loss 2.94 | Speed 2171 tokens/sec | Learning rate 0.0001809
Step 2681 | Loss 2.63 | Speed 2173 tokens/sec | Learning rate 0.00018084
Step 2721 | Loss 2.87 | Speed 2066 tokens/sec | Learning rate 0.00018078
Step 2761 | Loss 3.09 | Speed 2144 tokens/sec | Learning rate 0.00018072
Step 2801 | Loss 3.20 | Speed 2062 tokens/sec | Learning rate 0.00018066
Step 2841 | Loss 2.77 | Speed 2247 tokens/sec | Learning rate 0.0001806
Step 2881 | Loss 2.74 | Speed 2164 tokens/sec | Learning rate 0.00018054
Step 2921 | Loss 3.48 | Speed 1964 tokens/sec | Learning rate 0.00018048
Saved dailydialog_local38k8e_step_60000.pt
Saved dailydialog_local38k8e_last.pt
Step 2961 | Loss 2.30 | Speed 1302 tokens/sec | Learning rate 0.00018042
Step 3001 | Loss 2.87 | Speed 2006 tokens/sec | Learning rate 0.00018036
Step 3041 | Loss 3.20 | Speed 2168 tokens/sec | Learning rate 0.0001803
Step 3081 | Loss 2.39 | Speed 1986 tokens/sec | Learning rate 0.00018024
Step 3121 | Loss 3.25 | Speed 1935 tokens/sec | Learning rate 0.00018018
Step 3161 | Loss 2.41 | Speed 2107 tokens/sec | Learning rate 0.00018012
Step 3201 | Loss 2.21 | Speed 2252 tokens/sec | Learning rate 0.00018006
Step 3241 | Loss 2.76 | Speed 2067 tokens/sec | Learning rate 0.00018
Step 3281 | Loss 2.62 | Speed 1961 tokens/sec | Learning rate 0.00017994
Step 3321 | Loss 2.51 | Speed 2059 tokens/sec | Learning rate 0.00017988
Step 3361 | Loss 2.79 | Speed 2021 tokens/sec | Learning rate 0.00017982
Step 3401 | Loss 2.81 | Speed 2108 tokens/sec | Learning rate 0.00017976
Step 3441 | Loss 2.92 | Speed 2164 tokens/sec | Learning rate 0.0001797
Step 3481 | Loss 3.02 | Speed 1945 tokens/sec | Learning rate 0.00017964
Step 3521 | Loss 2.91 | Speed 1974 tokens/sec | Learning rate 0.00017958
Step 3561 | Loss 2.82 | Speed 2228 tokens/sec | Learning rate 0.00017952
Step 3601 | Loss 2.45 | Speed 2118 tokens/sec | Learning rate 0.00017946
Step 3641 | Loss 2.79 | Speed 2074 tokens/sec | Learning rate 0.0001794
Step 3681 | Loss 2.46 | Speed 2169 tokens/sec | Learning rate 0.00017934
Step 3721 | Loss 2.98 | Speed 2207 tokens/sec | Learning rate 0.00017928
Step 3761 | Loss 2.86 | Speed 1978 tokens/sec | Learning rate 0.00017923
Step 3801 | Loss 2.68 | Speed 1989 tokens/sec | Learning rate 0.00017917
Step 3841 | Loss 2.42 | Speed 2025 tokens/sec | Learning rate 0.00017911
Step 3881 | Loss 2.48 | Speed 2073 tokens/sec | Learning rate 0.00017905
Step 3921 | Loss 3.24 | Speed 2048 tokens/sec | Learning rate 0.00017899
Step 3961 | Loss 3.06 | Speed 2188 tokens/sec | Learning rate 0.00017893
Step 4001 | Loss 2.39 | Speed 2085 tokens/sec | Learning rate 0.00017887
Step 4041 | Loss 2.57 | Speed 1971 tokens/sec | Learning rate 0.00017881
Step 4081 | Loss 2.72 | Speed 2091 tokens/sec | Learning rate 0.00017876
Step 4121 | Loss 3.19 | Speed 2071 tokens/sec | Learning rate 0.0001787
Step 4161 | Loss 2.43 | Speed 2126 tokens/sec | Learning rate 0.00017864
Step 4201 | Loss 2.93 | Speed 2104 tokens/sec | Learning rate 0.00017858
Step 4241 | Loss 2.86 | Speed 2119 tokens/sec | Learning rate 0.00017852
Step 4281 | Loss 2.76 | Speed 2164 tokens/sec | Learning rate 0.00017846
Step 4321 | Loss 2.97 | Speed 2130 tokens/sec | Learning rate 0.00017841
Step 4361 | Loss 2.46 | Speed 2143 tokens/sec | Learning rate 0.00017835
Step 4401 | Loss 2.82 | Speed 2119 tokens/sec | Learning rate 0.00017829
Step 4441 | Loss 2.34 | Speed 1975 tokens/sec | Learning rate 0.00017823
Step 4481 | Loss 2.93 | Speed 2252 tokens/sec | Learning rate 0.00017817
Step 4521 | Loss 2.81 | Speed 2176 tokens/sec | Learning rate 0.00017812
Step 4561 | Loss 2.43 | Speed 2136 tokens/sec | Learning rate 0.00017806
Step 4601 | Loss 2.84 | Speed 2069 tokens/sec | Learning rate 0.000178
Step 4641 | Loss 3.05 | Speed 2277 tokens/sec | Learning rate 0.00017794
Step 4681 | Loss 2.50 | Speed 2160 tokens/sec | Learning rate 0.00017788
Step 4721 | Loss 2.94 | Speed 2002 tokens/sec | Learning rate 0.00017783
Step 4761 | Loss 2.36 | Speed 1960 tokens/sec | Learning rate 0.00017777
Step 4801 | Loss 2.88 | Speed 2019 tokens/sec | Learning rate 0.00017771
Step 4841 | Loss 2.92 | Speed 2129 tokens/sec | Learning rate 0.00017765
Step 4881 | Loss 2.62 | Speed 2093 tokens/sec | Learning rate 0.0001776
Step 4921 | Loss 2.11 | Speed 2061 tokens/sec | Learning rate 0.00017754
Step 4961 | Loss 1.85 | Speed 2204 tokens/sec | Learning rate 0.00017748
Step 5001 | Loss 2.74 | Speed 2132 tokens/sec | Learning rate 0.00017743
Step 5041 | Loss 3.17 | Speed 2180 tokens/sec | Learning rate 0.00017737
Step 5081 | Loss 3.14 | Speed 2056 tokens/sec | Learning rate 0.00017731
Step 5121 | Loss 3.20 | Speed 2090 tokens/sec | Learning rate 0.00017725
Step 5161 | Loss 2.84 | Speed 2102 tokens/sec | Learning rate 0.0001772
Step 5201 | Loss 2.61 | Speed 2202 tokens/sec | Learning rate 0.00017714
Step 5241 | Loss 2.72 | Speed 2095 tokens/sec | Learning rate 0.00017708
Step 5281 | Loss 3.34 | Speed 2086 tokens/sec | Learning rate 0.00017703
Step 5321 | Loss 2.87 | Speed 2130 tokens/sec | Learning rate 0.00017697
Step 5361 | Loss 2.59 | Speed 2062 tokens/sec | Learning rate 0.00017691
Step 5401 | Loss 2.52 | Speed 1938 tokens/sec | Learning rate 0.00017686
Step 5441 | Loss 2.87 | Speed 2196 tokens/sec | Learning rate 0.0001768
Saved dailydialog_local38k8e_step_62500.pt
Saved dailydialog_local38k8e_last.pt
Step 5481 | Loss 2.68 | Speed 1353 tokens/sec | Learning rate 0.00017674
Step 5521 | Loss 3.27 | Speed 2109 tokens/sec | Learning rate 0.00017669
Step 5561 | Loss 2.81 | Speed 2184 tokens/sec | Learning rate 0.00017663
Step 5601 | Loss 3.15 | Speed 2100 tokens/sec | Learning rate 0.00017657
Step 5641 | Loss 2.74 | Speed 2170 tokens/sec | Learning rate 0.00017652
Step 5681 | Loss 3.03 | Speed 2110 tokens/sec | Learning rate 0.00017646
Step 5721 | Loss 2.24 | Speed 2024 tokens/sec | Learning rate 0.0001764
Step 5761 | Loss 2.68 | Speed 2116 tokens/sec | Learning rate 0.00017635
Step 5801 | Loss 2.97 | Speed 2156 tokens/sec | Learning rate 0.00017629
Step 5841 | Loss 2.36 | Speed 2026 tokens/sec | Learning rate 0.00017624
Step 5881 | Loss 3.28 | Speed 2166 tokens/sec | Learning rate 0.00017618
Step 5921 | Loss 2.42 | Speed 2072 tokens/sec | Learning rate 0.00017612
Step 5961 | Loss 2.88 | Speed 2073 tokens/sec | Learning rate 0.00017607
Step 6001 | Loss 2.53 | Speed 2114 tokens/sec | Learning rate 0.00017601
Step 6041 | Loss 2.98 | Speed 2059 tokens/sec | Learning rate 0.00017596
Step 6081 | Loss 2.81 | Speed 2160 tokens/sec | Learning rate 0.0001759
Step 6121 | Loss 2.87 | Speed 2271 tokens/sec | Learning rate 0.00017585
Step 6161 | Loss 2.34 | Speed 2016 tokens/sec | Learning rate 0.00017579
Step 6201 | Loss 2.50 | Speed 1958 tokens/sec | Learning rate 0.00017573
Step 6241 | Loss 2.97 | Speed 2037 tokens/sec | Learning rate 0.00017568
Step 6281 | Loss 2.52 | Speed 2250 tokens/sec | Learning rate 0.00017562
Step 6321 | Loss 3.27 | Speed 2159 tokens/sec | Learning rate 0.00017557
Step 6361 | Loss 2.07 | Speed 2079 tokens/sec | Learning rate 0.00017551
Step 6401 | Loss 2.54 | Speed 2057 tokens/sec | Learning rate 0.00017546
Step 6441 | Loss 3.01 | Speed 2079 tokens/sec | Learning rate 0.0001754
Step 6481 | Loss 3.14 | Speed 1981 tokens/sec | Learning rate 0.00017535
Step 6521 | Loss 2.46 | Speed 2221 tokens/sec | Learning rate 0.00017529
Step 6561 | Loss 2.59 | Speed 2236 tokens/sec | Learning rate 0.00017524
Step 6601 | Loss 2.84 | Speed 2052 tokens/sec | Learning rate 0.00017518
Step 6641 | Loss 3.11 | Speed 2198 tokens/sec | Learning rate 0.00017513
Step 6681 | Loss 3.04 | Speed 2115 tokens/sec | Learning rate 0.00017507
Step 6721 | Loss 2.93 | Speed 2217 tokens/sec | Learning rate 0.00017502
Step 6761 | Loss 3.23 | Speed 2209 tokens/sec | Learning rate 0.00017496
Step 6801 | Loss 2.63 | Speed 2094 tokens/sec | Learning rate 0.00017491
Step 6841 | Loss 2.95 | Speed 2007 tokens/sec | Learning rate 0.00017485
Step 6881 | Loss 2.12 | Speed 2114 tokens/sec | Learning rate 0.0001748
Step 6921 | Loss 2.79 | Speed 2188 tokens/sec | Learning rate 0.00017474
Step 6961 | Loss 2.81 | Speed 2115 tokens/sec | Learning rate 0.00017469
Step 7001 | Loss 2.14 | Speed 2039 tokens/sec | Learning rate 0.00017463
Step 7041 | Loss 2.87 | Speed 2121 tokens/sec | Learning rate 0.00017458
Step 7081 | Loss 2.93 | Speed 2061 tokens/sec | Learning rate 0.00017452
Step 7121 | Loss 3.32 | Speed 2147 tokens/sec | Learning rate 0.00017447
Step 7161 | Loss 2.68 | Speed 2137 tokens/sec | Learning rate 0.00017442
Step 7201 | Loss 2.85 | Speed 2039 tokens/sec | Learning rate 0.00017436
Step 7241 | Loss 2.32 | Speed 2140 tokens/sec | Learning rate 0.00017431
Step 7281 | Loss 2.81 | Speed 2175 tokens/sec | Learning rate 0.00017425
Step 7321 | Loss 3.13 | Speed 2144 tokens/sec | Learning rate 0.0001742
Step 7361 | Loss 2.57 | Speed 2030 tokens/sec | Learning rate 0.00017414
Step 7401 | Loss 2.70 | Speed 2078 tokens/sec | Learning rate 0.00017409
Step 7441 | Loss 3.13 | Speed 2022 tokens/sec | Learning rate 0.00017404
Step 7481 | Loss 2.28 | Speed 2076 tokens/sec | Learning rate 0.00017398
Step 7521 | Loss 2.96 | Speed 2181 tokens/sec | Learning rate 0.00017393
Step 7561 | Loss 3.02 | Speed 2025 tokens/sec | Learning rate 0.00017387
Step 7601 | Loss 2.49 | Speed 2216 tokens/sec | Learning rate 0.00017382
Step 7641 | Loss 2.56 | Speed 1981 tokens/sec | Learning rate 0.00017377
Step 7681 | Loss 2.81 | Speed 2073 tokens/sec | Learning rate 0.00017371
Step 7721 | Loss 2.94 | Speed 2176 tokens/sec | Learning rate 0.00017366
Step 7761 | Loss 3.00 | Speed 2222 tokens/sec | Learning rate 0.00017361
Step 7801 | Loss 2.92 | Speed 2149 tokens/sec | Learning rate 0.00017355
Step 7841 | Loss 2.86 | Speed 2248 tokens/sec | Learning rate 0.0001735
Step 7881 | Loss 2.41 | Speed 2175 tokens/sec | Learning rate 0.00017345
Step 7921 | Loss 3.05 | Speed 1969 tokens/sec | Learning rate 0.00017339
Saved dailydialog_local38k8e_step_65000.pt
Saved dailydialog_local38k8e_last.pt
Step 7961 | Loss 2.83 | Speed 1264 tokens/sec | Learning rate 0.00017334
Step 8001 | Loss 2.74 | Speed 2092 tokens/sec | Learning rate 0.00017329
Step 8041 | Loss 2.75 | Speed 2179 tokens/sec | Learning rate 0.00017323
Step 8081 | Loss 2.74 | Speed 2215 tokens/sec | Learning rate 0.00017318
Step 8121 | Loss 2.62 | Speed 2065 tokens/sec | Learning rate 0.00017313
Step 8161 | Loss 3.03 | Speed 2136 tokens/sec | Learning rate 0.00017307
Step 8201 | Loss 3.23 | Speed 2089 tokens/sec | Learning rate 0.00017302
Step 8241 | Loss 2.81 | Speed 1968 tokens/sec | Learning rate 0.00017297
Step 8281 | Loss 2.68 | Speed 1979 tokens/sec | Learning rate 0.00017291
Step 8321 | Loss 2.86 | Speed 2103 tokens/sec | Learning rate 0.00017286
Step 8361 | Loss 2.41 | Speed 2259 tokens/sec | Learning rate 0.00017281
Step 8401 | Loss 2.53 | Speed 2210 tokens/sec | Learning rate 0.00017275
Step 8441 | Loss 3.13 | Speed 2034 tokens/sec | Learning rate 0.0001727
Step 8481 | Loss 3.14 | Speed 2190 tokens/sec | Learning rate 0.00017265
Step 8521 | Loss 2.74 | Speed 2137 tokens/sec | Learning rate 0.0001726
Step 8561 | Loss 2.60 | Speed 1950 tokens/sec | Learning rate 0.00017254
Step 8601 | Loss 3.05 | Speed 2108 tokens/sec | Learning rate 0.00017249
Step 8641 | Loss 2.85 | Speed 2132 tokens/sec | Learning rate 0.00017244
Step 8681 | Loss 2.87 | Speed 2183 tokens/sec | Learning rate 0.00017239
Step 8721 | Loss 3.03 | Speed 1995 tokens/sec | Learning rate 0.00017233
Step 8761 | Loss 3.53 | Speed 2155 tokens/sec | Learning rate 0.00017228
Step 8801 | Loss 2.01 | Speed 2135 tokens/sec | Learning rate 0.00017223
Step 8841 | Loss 3.20 | Speed 2299 tokens/sec | Learning rate 0.00017218
Step 8881 | Loss 3.05 | Speed 2067 tokens/sec | Learning rate 0.00017212
Step 8921 | Loss 3.09 | Speed 2203 tokens/sec | Learning rate 0.00017207
Step 8961 | Loss 3.22 | Speed 2041 tokens/sec | Learning rate 0.00017202
Step 9001 | Loss 2.50 | Speed 2013 tokens/sec | Learning rate 0.00017197
Step 9041 | Loss 2.62 | Speed 2165 tokens/sec | Learning rate 0.00017192
Step 9081 | Loss 2.88 | Speed 2004 tokens/sec | Learning rate 0.00017186
Step 9121 | Loss 3.08 | Speed 2093 tokens/sec | Learning rate 0.00017181
Step 9161 | Loss 3.06 | Speed 2164 tokens/sec | Learning rate 0.00017176
Step 9201 | Loss 2.67 | Speed 2107 tokens/sec | Learning rate 0.00017171
Step 9241 | Loss 2.98 | Speed 2118 tokens/sec | Learning rate 0.00017166
Step 9281 | Loss 2.99 | Speed 2058 tokens/sec | Learning rate 0.0001716
Step 9321 | Loss 2.46 | Speed 2141 tokens/sec | Learning rate 0.00017155
Step 9361 | Loss 2.90 | Speed 2013 tokens/sec | Learning rate 0.0001715
Step 9401 | Loss 2.61 | Speed 2077 tokens/sec | Learning rate 0.00017145
Step 9441 | Loss 3.10 | Speed 2100 tokens/sec | Learning rate 0.0001714
Step 9481 | Loss 2.48 | Speed 2113 tokens/sec | Learning rate 0.00017135
| ID | GPU | MEM |
------------------
|  0 | 90% | 27% |
Epoch 6 Validation ====
Validation loss: 3.0007
[████████████████████████░░░░]  epoch 7/8 complete
  train_loss=2.8088  val_loss=3.0007  steps=66549  tokens_seen=8038513

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_6.pt
Saved dailydialog_local38k8e_last.pt
Epoch 7 Training ====
Step 1 | Loss 2.93 | Speed 2247 tokens/sec | Learning rate 0.00017131
Step 41 | Loss 2.70 | Speed 2239 tokens/sec | Learning rate 0.00017126
Step 81 | Loss 2.78 | Speed 2087 tokens/sec | Learning rate 0.00017121
Step 121 | Loss 3.00 | Speed 2133 tokens/sec | Learning rate 0.00017116
Step 161 | Loss 2.05 | Speed 2040 tokens/sec | Learning rate 0.00017111
Step 201 | Loss 3.37 | Speed 2128 tokens/sec | Learning rate 0.00017106
Step 241 | Loss 2.05 | Speed 2088 tokens/sec | Learning rate 0.000171
Step 281 | Loss 2.94 | Speed 2080 tokens/sec | Learning rate 0.00017095
Step 321 | Loss 2.48 | Speed 2124 tokens/sec | Learning rate 0.0001709
Step 361 | Loss 2.67 | Speed 2027 tokens/sec | Learning rate 0.00017085
Step 401 | Loss 2.65 | Speed 2022 tokens/sec | Learning rate 0.0001708
Step 441 | Loss 2.76 | Speed 2052 tokens/sec | Learning rate 0.00017075
Step 481 | Loss 2.90 | Speed 2233 tokens/sec | Learning rate 0.0001707
Step 521 | Loss 2.65 | Speed 2071 tokens/sec | Learning rate 0.00017065
Step 561 | Loss 2.69 | Speed 1997 tokens/sec | Learning rate 0.0001706
Step 601 | Loss 2.63 | Speed 2084 tokens/sec | Learning rate 0.00017054
Step 641 | Loss 2.48 | Speed 2073 tokens/sec | Learning rate 0.00017049
Step 681 | Loss 2.97 | Speed 2048 tokens/sec | Learning rate 0.00017044
Step 721 | Loss 2.75 | Speed 2075 tokens/sec | Learning rate 0.00017039
Step 761 | Loss 2.52 | Speed 2085 tokens/sec | Learning rate 0.00017034
Step 801 | Loss 2.60 | Speed 2092 tokens/sec | Learning rate 0.00017029
Step 841 | Loss 2.81 | Speed 2025 tokens/sec | Learning rate 0.00017024
Step 881 | Loss 2.46 | Speed 2028 tokens/sec | Learning rate 0.00017019
Step 921 | Loss 2.49 | Speed 2259 tokens/sec | Learning rate 0.00017014
Saved dailydialog_local38k8e_step_67500.pt
Saved dailydialog_local38k8e_last.pt
Step 961 | Loss 3.18 | Speed 1263 tokens/sec | Learning rate 0.00017009
Step 1001 | Loss 2.89 | Speed 1991 tokens/sec | Learning rate 0.00017004
Step 1041 | Loss 2.72 | Speed 2062 tokens/sec | Learning rate 0.00016999
Step 1081 | Loss 2.67 | Speed 1933 tokens/sec | Learning rate 0.00016994
Step 1121 | Loss 2.50 | Speed 1943 tokens/sec | Learning rate 0.00016989
Step 1161 | Loss 3.28 | Speed 2132 tokens/sec | Learning rate 0.00016984
Step 1201 | Loss 2.99 | Speed 2095 tokens/sec | Learning rate 0.00016979
Step 1241 | Loss 2.58 | Speed 2136 tokens/sec | Learning rate 0.00016974
Step 1281 | Loss 2.65 | Speed 2030 tokens/sec | Learning rate 0.00016969
Step 1321 | Loss 2.84 | Speed 2164 tokens/sec | Learning rate 0.00016964
Step 1361 | Loss 2.38 | Speed 2154 tokens/sec | Learning rate 0.00016959
Step 1401 | Loss 2.36 | Speed 2079 tokens/sec | Learning rate 0.00016954
Step 1441 | Loss 2.63 | Speed 2007 tokens/sec | Learning rate 0.00016949
Step 1481 | Loss 2.85 | Speed 2251 tokens/sec | Learning rate 0.00016944
Step 1521 | Loss 2.40 | Speed 2142 tokens/sec | Learning rate 0.00016939
Step 1561 | Loss 2.76 | Speed 2041 tokens/sec | Learning rate 0.00016934
Step 1601 | Loss 2.89 | Speed 2070 tokens/sec | Learning rate 0.00016929
Step 1641 | Loss 2.86 | Speed 2217 tokens/sec | Learning rate 0.00016924
Step 1681 | Loss 2.44 | Speed 2086 tokens/sec | Learning rate 0.00016919
Step 1721 | Loss 2.62 | Speed 2121 tokens/sec | Learning rate 0.00016914
Step 1761 | Loss 3.18 | Speed 2064 tokens/sec | Learning rate 0.00016909
Step 1801 | Loss 2.92 | Speed 2268 tokens/sec | Learning rate 0.00016904
Step 1841 | Loss 2.83 | Speed 2045 tokens/sec | Learning rate 0.00016899
Step 1881 | Loss 2.59 | Speed 2108 tokens/sec | Learning rate 0.00016894
Step 1921 | Loss 2.87 | Speed 2185 tokens/sec | Learning rate 0.00016889
Step 1961 | Loss 3.04 | Speed 2137 tokens/sec | Learning rate 0.00016884
Step 2001 | Loss 3.22 | Speed 2054 tokens/sec | Learning rate 0.00016879
Step 2041 | Loss 2.61 | Speed 2115 tokens/sec | Learning rate 0.00016875
Step 2081 | Loss 2.21 | Speed 2129 tokens/sec | Learning rate 0.0001687
Step 2121 | Loss 2.65 | Speed 2233 tokens/sec | Learning rate 0.00016865
Step 2161 | Loss 2.27 | Speed 2239 tokens/sec | Learning rate 0.0001686
Step 2201 | Loss 2.64 | Speed 2166 tokens/sec | Learning rate 0.00016855
Step 2241 | Loss 2.84 | Speed 1903 tokens/sec | Learning rate 0.0001685
Step 2281 | Loss 3.19 | Speed 2230 tokens/sec | Learning rate 0.00016845
Step 2321 | Loss 3.52 | Speed 1999 tokens/sec | Learning rate 0.0001684
Step 2361 | Loss 3.12 | Speed 2133 tokens/sec | Learning rate 0.00016835
Step 2401 | Loss 3.17 | Speed 2140 tokens/sec | Learning rate 0.0001683
Step 2441 | Loss 2.82 | Speed 2090 tokens/sec | Learning rate 0.00016826
Step 2481 | Loss 2.68 | Speed 1942 tokens/sec | Learning rate 0.00016821
Step 2521 | Loss 3.06 | Speed 2147 tokens/sec | Learning rate 0.00016816
Step 2561 | Loss 2.54 | Speed 2075 tokens/sec | Learning rate 0.00016811
Step 2601 | Loss 2.49 | Speed 2155 tokens/sec | Learning rate 0.00016806
Step 2641 | Loss 2.64 | Speed 2177 tokens/sec | Learning rate 0.00016801
Step 2681 | Loss 2.40 | Speed 2139 tokens/sec | Learning rate 0.00016796
Step 2721 | Loss 2.94 | Speed 2146 tokens/sec | Learning rate 0.00016791
Step 2761 | Loss 3.21 | Speed 2077 tokens/sec | Learning rate 0.00016787
Step 2801 | Loss 2.48 | Speed 2139 tokens/sec | Learning rate 0.00016782
Step 2841 | Loss 2.25 | Speed 2018 tokens/sec | Learning rate 0.00016777
Step 2881 | Loss 3.00 | Speed 2120 tokens/sec | Learning rate 0.00016772
Step 2921 | Loss 3.15 | Speed 2164 tokens/sec | Learning rate 0.00016767
Step 2961 | Loss 2.61 | Speed 2152 tokens/sec | Learning rate 0.00016762
Step 3001 | Loss 2.37 | Speed 2272 tokens/sec | Learning rate 0.00016758
Step 3041 | Loss 2.36 | Speed 2091 tokens/sec | Learning rate 0.00016753
Step 3081 | Loss 3.08 | Speed 1976 tokens/sec | Learning rate 0.00016748
Step 3121 | Loss 2.92 | Speed 2071 tokens/sec | Learning rate 0.00016743
Step 3161 | Loss 2.57 | Speed 2107 tokens/sec | Learning rate 0.00016738
Step 3201 | Loss 2.67 | Speed 2039 tokens/sec | Learning rate 0.00016734
Step 3241 | Loss 2.55 | Speed 2121 tokens/sec | Learning rate 0.00016729
Step 3281 | Loss 3.08 | Speed 2106 tokens/sec | Learning rate 0.00016724
Step 3321 | Loss 2.65 | Speed 2069 tokens/sec | Learning rate 0.00016719
Step 3361 | Loss 2.46 | Speed 2039 tokens/sec | Learning rate 0.00016714
Step 3401 | Loss 2.77 | Speed 2116 tokens/sec | Learning rate 0.0001671
Step 3441 | Loss 2.83 | Speed 2031 tokens/sec | Learning rate 0.00016705
Saved dailydialog_local38k8e_step_70000.pt
Saved dailydialog_local38k8e_last.pt
Step 3481 | Loss 3.03 | Speed 1107 tokens/sec | Learning rate 0.000167
Step 3521 | Loss 2.58 | Speed 2208 tokens/sec | Learning rate 0.00016695
Step 3561 | Loss 2.68 | Speed 2200 tokens/sec | Learning rate 0.00016691
Step 3601 | Loss 2.76 | Speed 2126 tokens/sec | Learning rate 0.00016686
Step 3641 | Loss 2.71 | Speed 2108 tokens/sec | Learning rate 0.00016681
Step 3681 | Loss 2.80 | Speed 2052 tokens/sec | Learning rate 0.00016676
Step 3721 | Loss 2.42 | Speed 2102 tokens/sec | Learning rate 0.00016672
Step 3761 | Loss 2.44 | Speed 2092 tokens/sec | Learning rate 0.00016667
Step 3801 | Loss 2.97 | Speed 2073 tokens/sec | Learning rate 0.00016662
Step 3841 | Loss 3.07 | Speed 2233 tokens/sec | Learning rate 0.00016657
Step 3881 | Loss 2.74 | Speed 2134 tokens/sec | Learning rate 0.00016653
Step 3921 | Loss 3.11 | Speed 2088 tokens/sec | Learning rate 0.00016648
Step 3961 | Loss 2.64 | Speed 1993 tokens/sec | Learning rate 0.00016643
Step 4001 | Loss 2.87 | Speed 1986 tokens/sec | Learning rate 0.00016638
Step 4041 | Loss 2.92 | Speed 2317 tokens/sec | Learning rate 0.00016634
Step 4081 | Loss 2.95 | Speed 2075 tokens/sec | Learning rate 0.00016629
Step 4121 | Loss 2.79 | Speed 2208 tokens/sec | Learning rate 0.00016624
Step 4161 | Loss 3.13 | Speed 2132 tokens/sec | Learning rate 0.0001662
Step 4201 | Loss 2.60 | Speed 2135 tokens/sec | Learning rate 0.00016615
Step 4241 | Loss 2.72 | Speed 2098 tokens/sec | Learning rate 0.0001661
Step 4281 | Loss 2.65 | Speed 2146 tokens/sec | Learning rate 0.00016606
Step 4321 | Loss 2.97 | Speed 2084 tokens/sec | Learning rate 0.00016601
Step 4361 | Loss 2.39 | Speed 2143 tokens/sec | Learning rate 0.00016596
Step 4401 | Loss 2.38 | Speed 1975 tokens/sec | Learning rate 0.00016592
Step 4441 | Loss 3.00 | Speed 2109 tokens/sec | Learning rate 0.00016587
Step 4481 | Loss 3.12 | Speed 2192 tokens/sec | Learning rate 0.00016582
Step 4521 | Loss 2.25 | Speed 2075 tokens/sec | Learning rate 0.00016577
Step 4561 | Loss 2.13 | Speed 2068 tokens/sec | Learning rate 0.00016573
Step 4601 | Loss 3.02 | Speed 2175 tokens/sec | Learning rate 0.00016568
Step 4641 | Loss 2.53 | Speed 2034 tokens/sec | Learning rate 0.00016564
Step 4681 | Loss 2.18 | Speed 2051 tokens/sec | Learning rate 0.00016559
Step 4721 | Loss 3.32 | Speed 2167 tokens/sec | Learning rate 0.00016554
Step 4761 | Loss 2.87 | Speed 2042 tokens/sec | Learning rate 0.0001655
Step 4801 | Loss 2.21 | Speed 2085 tokens/sec | Learning rate 0.00016545
Step 4841 | Loss 2.78 | Speed 1999 tokens/sec | Learning rate 0.0001654
Step 4881 | Loss 2.54 | Speed 2159 tokens/sec | Learning rate 0.00016536
Step 4921 | Loss 3.18 | Speed 1995 tokens/sec | Learning rate 0.00016531
Step 4961 | Loss 2.21 | Speed 2091 tokens/sec | Learning rate 0.00016526
Step 5001 | Loss 3.17 | Speed 2221 tokens/sec | Learning rate 0.00016522
Step 5041 | Loss 2.38 | Speed 2080 tokens/sec | Learning rate 0.00016517
Step 5081 | Loss 2.96 | Speed 2316 tokens/sec | Learning rate 0.00016513
Step 5121 | Loss 2.98 | Speed 2018 tokens/sec | Learning rate 0.00016508
Step 5161 | Loss 2.32 | Speed 2066 tokens/sec | Learning rate 0.00016503
Step 5201 | Loss 2.37 | Speed 2225 tokens/sec | Learning rate 0.00016499
Step 5241 | Loss 3.71 | Speed 1992 tokens/sec | Learning rate 0.00016494
Step 5281 | Loss 2.88 | Speed 2207 tokens/sec | Learning rate 0.0001649
Step 5321 | Loss 2.46 | Speed 2212 tokens/sec | Learning rate 0.00016485
Step 5361 | Loss 2.88 | Speed 1975 tokens/sec | Learning rate 0.0001648
Step 5401 | Loss 2.89 | Speed 1985 tokens/sec | Learning rate 0.00016476
Step 5441 | Loss 2.57 | Speed 2098 tokens/sec | Learning rate 0.00016471
Step 5481 | Loss 2.76 | Speed 2058 tokens/sec | Learning rate 0.00016467
Step 5521 | Loss 3.02 | Speed 2082 tokens/sec | Learning rate 0.00016462
Step 5561 | Loss 2.38 | Speed 2029 tokens/sec | Learning rate 0.00016458
Step 5601 | Loss 2.66 | Speed 2080 tokens/sec | Learning rate 0.00016453
Step 5641 | Loss 2.46 | Speed 1899 tokens/sec | Learning rate 0.00016448
Step 5681 | Loss 2.77 | Speed 2149 tokens/sec | Learning rate 0.00016444
Step 5721 | Loss 2.60 | Speed 2087 tokens/sec | Learning rate 0.00016439
Step 5761 | Loss 2.33 | Speed 2080 tokens/sec | Learning rate 0.00016435
Step 5801 | Loss 3.12 | Speed 1992 tokens/sec | Learning rate 0.0001643
Step 5841 | Loss 2.47 | Speed 2037 tokens/sec | Learning rate 0.00016426
Step 5881 | Loss 3.10 | Speed 2096 tokens/sec | Learning rate 0.00016421
Step 5921 | Loss 2.91 | Speed 2174 tokens/sec | Learning rate 0.00016417
Saved dailydialog_local38k8e_step_72500.pt
Saved dailydialog_local38k8e_last.pt
Step 5961 | Loss 3.12 | Speed 1183 tokens/sec | Learning rate 0.00016412
Step 6001 | Loss 2.62 | Speed 2088 tokens/sec | Learning rate 0.00016408
Step 6041 | Loss 2.82 | Speed 2045 tokens/sec | Learning rate 0.00016403
Step 6081 | Loss 2.30 | Speed 2197 tokens/sec | Learning rate 0.00016398
Step 6121 | Loss 2.96 | Speed 2077 tokens/sec | Learning rate 0.00016394
Step 6161 | Loss 2.46 | Speed 2082 tokens/sec | Learning rate 0.00016389
Step 6201 | Loss 2.67 | Speed 2041 tokens/sec | Learning rate 0.00016385
Step 6241 | Loss 2.65 | Speed 1942 tokens/sec | Learning rate 0.0001638
Step 6281 | Loss 2.89 | Speed 2026 tokens/sec | Learning rate 0.00016376
Step 6321 | Loss 3.03 | Speed 2016 tokens/sec | Learning rate 0.00016371
Step 6361 | Loss 2.27 | Speed 1916 tokens/sec | Learning rate 0.00016367
Step 6401 | Loss 2.21 | Speed 2080 tokens/sec | Learning rate 0.00016362
Step 6441 | Loss 2.37 | Speed 2180 tokens/sec | Learning rate 0.00016358
Step 6481 | Loss 2.83 | Speed 2064 tokens/sec | Learning rate 0.00016354
Step 6521 | Loss 2.50 | Speed 2068 tokens/sec | Learning rate 0.00016349
Step 6561 | Loss 2.47 | Speed 1982 tokens/sec | Learning rate 0.00016345
Step 6601 | Loss 3.00 | Speed 2077 tokens/sec | Learning rate 0.0001634
Step 6641 | Loss 2.28 | Speed 2094 tokens/sec | Learning rate 0.00016336
Step 6681 | Loss 2.15 | Speed 2182 tokens/sec | Learning rate 0.00016331
Step 6721 | Loss 2.79 | Speed 2157 tokens/sec | Learning rate 0.00016327
Step 6761 | Loss 3.12 | Speed 2079 tokens/sec | Learning rate 0.00016322
Step 6801 | Loss 2.96 | Speed 1975 tokens/sec | Learning rate 0.00016318
Step 6841 | Loss 2.72 | Speed 2092 tokens/sec | Learning rate 0.00016313
Step 6881 | Loss 2.68 | Speed 2114 tokens/sec | Learning rate 0.00016309
Step 6921 | Loss 3.04 | Speed 2001 tokens/sec | Learning rate 0.00016304
Step 6961 | Loss 2.92 | Speed 2059 tokens/sec | Learning rate 0.000163
Step 7001 | Loss 2.84 | Speed 2156 tokens/sec | Learning rate 0.00016296
Step 7041 | Loss 2.47 | Speed 2101 tokens/sec | Learning rate 0.00016291
Step 7081 | Loss 2.90 | Speed 2124 tokens/sec | Learning rate 0.00016287
Step 7121 | Loss 2.83 | Speed 2079 tokens/sec | Learning rate 0.00016282
Step 7161 | Loss 2.56 | Speed 1920 tokens/sec | Learning rate 0.00016278
Step 7201 | Loss 2.52 | Speed 1999 tokens/sec | Learning rate 0.00016274
Step 7241 | Loss 2.62 | Speed 2064 tokens/sec | Learning rate 0.00016269
Step 7281 | Loss 2.68 | Speed 2045 tokens/sec | Learning rate 0.00016265
Step 7321 | Loss 2.48 | Speed 2192 tokens/sec | Learning rate 0.0001626
Step 7361 | Loss 2.71 | Speed 2017 tokens/sec | Learning rate 0.00016256
Step 7401 | Loss 2.78 | Speed 2032 tokens/sec | Learning rate 0.00016251
Step 7441 | Loss 2.59 | Speed 2039 tokens/sec | Learning rate 0.00016247
Step 7481 | Loss 3.29 | Speed 2111 tokens/sec | Learning rate 0.00016243
Step 7521 | Loss 2.75 | Speed 2062 tokens/sec | Learning rate 0.00016238
Step 7561 | Loss 2.40 | Speed 2018 tokens/sec | Learning rate 0.00016234
Step 7601 | Loss 2.98 | Speed 2110 tokens/sec | Learning rate 0.0001623
Step 7641 | Loss 3.16 | Speed 2088 tokens/sec | Learning rate 0.00016225
Step 7681 | Loss 2.67 | Speed 1963 tokens/sec | Learning rate 0.00016221
Step 7721 | Loss 2.64 | Speed 2045 tokens/sec | Learning rate 0.00016216
Step 7761 | Loss 2.55 | Speed 2057 tokens/sec | Learning rate 0.00016212
Step 7801 | Loss 2.93 | Speed 1903 tokens/sec | Learning rate 0.00016208
Step 7841 | Loss 2.44 | Speed 2106 tokens/sec | Learning rate 0.00016203
Step 7881 | Loss 2.27 | Speed 2091 tokens/sec | Learning rate 0.00016199
Step 7921 | Loss 2.26 | Speed 2030 tokens/sec | Learning rate 0.00016195
Step 7961 | Loss 2.58 | Speed 1973 tokens/sec | Learning rate 0.0001619
Step 8001 | Loss 2.81 | Speed 2275 tokens/sec | Learning rate 0.00016186
Step 8041 | Loss 2.73 | Speed 1935 tokens/sec | Learning rate 0.00016182
Step 8081 | Loss 3.13 | Speed 2096 tokens/sec | Learning rate 0.00016177
Step 8121 | Loss 2.64 | Speed 2123 tokens/sec | Learning rate 0.00016173
Step 8161 | Loss 2.55 | Speed 2093 tokens/sec | Learning rate 0.00016169
Step 8201 | Loss 2.38 | Speed 1930 tokens/sec | Learning rate 0.00016164
Step 8241 | Loss 1.77 | Speed 2125 tokens/sec | Learning rate 0.0001616
Step 8281 | Loss 2.45 | Speed 2264 tokens/sec | Learning rate 0.00016156
Step 8321 | Loss 2.88 | Speed 2054 tokens/sec | Learning rate 0.00016151
Step 8361 | Loss 2.80 | Speed 1970 tokens/sec | Learning rate 0.00016147
Step 8401 | Loss 2.48 | Speed 2142 tokens/sec | Learning rate 0.00016143
Step 8441 | Loss 2.50 | Speed 2039 tokens/sec | Learning rate 0.00016138
Saved dailydialog_local38k8e_step_75000.pt
Saved dailydialog_local38k8e_last.pt
Step 8481 | Loss 3.03 | Speed 1257 tokens/sec | Learning rate 0.00016134
Step 8521 | Loss 2.86 | Speed 1967 tokens/sec | Learning rate 0.0001613
Step 8561 | Loss 2.93 | Speed 2008 tokens/sec | Learning rate 0.00016126
Step 8601 | Loss 2.52 | Speed 2035 tokens/sec | Learning rate 0.00016121
Step 8641 | Loss 2.56 | Speed 2109 tokens/sec | Learning rate 0.00016117
Step 8681 | Loss 2.96 | Speed 2145 tokens/sec | Learning rate 0.00016113
Step 8721 | Loss 2.75 | Speed 1996 tokens/sec | Learning rate 0.00016108
Step 8761 | Loss 2.85 | Speed 2040 tokens/sec | Learning rate 0.00016104
Step 8801 | Loss 2.29 | Speed 1860 tokens/sec | Learning rate 0.000161
Step 8841 | Loss 2.73 | Speed 2187 tokens/sec | Learning rate 0.00016096
Step 8881 | Loss 2.73 | Speed 2092 tokens/sec | Learning rate 0.00016091
Step 8921 | Loss 2.63 | Speed 2037 tokens/sec | Learning rate 0.00016087
Step 8961 | Loss 2.58 | Speed 2077 tokens/sec | Learning rate 0.00016083
Step 9001 | Loss 2.66 | Speed 2164 tokens/sec | Learning rate 0.00016078
Step 9041 | Loss 2.61 | Speed 1840 tokens/sec | Learning rate 0.00016074
Step 9081 | Loss 2.61 | Speed 2109 tokens/sec | Learning rate 0.0001607
Step 9121 | Loss 3.05 | Speed 2085 tokens/sec | Learning rate 0.00016066
Step 9161 | Loss 2.62 | Speed 2070 tokens/sec | Learning rate 0.00016061
Step 9201 | Loss 3.17 | Speed 2097 tokens/sec | Learning rate 0.00016057
Step 9241 | Loss 3.14 | Speed 2146 tokens/sec | Learning rate 0.00016053
Step 9281 | Loss 2.97 | Speed 2024 tokens/sec | Learning rate 0.00016049
Step 9321 | Loss 3.18 | Speed 2037 tokens/sec | Learning rate 0.00016045
Step 9361 | Loss 2.91 | Speed 2168 tokens/sec | Learning rate 0.0001604
Step 9401 | Loss 2.71 | Speed 2132 tokens/sec | Learning rate 0.00016036
Step 9441 | Loss 2.85 | Speed 1879 tokens/sec | Learning rate 0.00016032
Step 9481 | Loss 2.98 | Speed 2117 tokens/sec | Learning rate 0.00016028
| ID | GPU | MEM |
------------------
|  0 | 89% | 27% |
Epoch 7 Validation ====
Validation loss: 2.9861
[████████████████████████████]  epoch 8/8 complete
  train_loss=2.7352  val_loss=2.9861  steps=76056  tokens_seen=9186872

### Training progress
Paper optimizer: Adam + warmup `rate()`. Charts record the same loop.

alt.VConcatChart(...)

Saved dailydialog_local38k8e_epoch_7.pt
Saved dailydialog_local38k8e_last.pt
Saved dailydialog_local38k8e_final.pt
Saved dailydialog_local38k8e_last.pt
============================================================
Training complete. Saved chat model: dailydialog_local38k8e_final.pt
Epochs finished: 8/8  final val_loss=2.9860851764678955
============================================================

### After training — model quality
Teacher-forced **token accuracy** scores next-token argmax vs `tgt_y` (padding ignored). **Expected** is the true DailyDialog reply. **Predicted** is paper greedy decode. **Overlap** is Jaccard on words. **missing / extra** is the word-level difference.

,epochs_configured,epochs_logged,N_layers,d_model,vocab_size,valid_pairs,token_accuracy,chance_accuracy,accuracy_minus_chance,correct_tokens,scored_tokens,val_loss,perplexity,mean_overlap,exact_match_shown
0,8,8,2,512,14578,7069,0.3782,0.000069,0.3781,1714,4532,2.9861,19.81,0.089,0

alt.HConcatChart(...)

**What to expect (local half-data):** 8 epochs, N=2, ~38k train pairs. Token accuracy should beat the old 15k/1-epoch run (~26%), but greedy replies can still look repetitive. That is normal for this 2017 model.

**Difference column:** `missing_from_pred` = words in the true reply the model dropped. `extra_in_pred` = words the model added.

,example,input,expected,predicted,overlap,missing_from_pred,extra_in_pred
0,0,"<s> Good morning , sir . Is there a bank near here ? </s>",<s> There is one . 5 blocks away from here ? </s>,"<s> Yes , I 'm looking for a new one . </s>",0.111,5 ? There away blocks from here is,"'m , I Yes a for looking new"
1,1,<s> There is one . 5 blocks away from here ? </s>,"<s> Well , that 's too far . Can you change some money for me ? </s>","<s> Yes , it is . </s>",0.111,'s ? Can Well change far for me money some that too you,Yes is it
2,2,"<s> Well , that 's too far . Can you change some money for me ? </s>","<s> Surely , of course . What kind of currency have you got ? </s>","<s> Yes , sir . </s>",0.143,? Surely What course currency got have kind of you,Yes sir
3,3,"<s> Surely , of course . What kind of currency have you got ? </s>",<s> RIB . </s>,<s> I 'm looking for a new student here . </s>,0.1,RIB,'m I a for here looking new student
4,4,<s> RIB . </s>,<s> How much would you like to change ? </s>,<s> OK . Here you are . </s>,0.083,? How change like much to would,. Here OK are
5,5,<s> How much would you like to change ? </s>,<s> 1000 Yuan . Here you are . </s>,<s> I 'm going to have to pay $ <unk> . </s>,0.071,1000 Here Yuan are you,$ 'm <unk> I going have pay to
6,6,"<s> Good afternoon . This is Michelle Li speaking , calling on <unk> of IBA . Is Mr Meng availab...","<s> This is Mr Meng speaking , Michelle . </s>","<s> Yes , I am . I am calling to call the manager and I have a reservation for a week . </s>",0.091,Meng Michelle Mr This is speaking,I Yes a am and call calling for have manager reservation the to week
7,7,"<s> This is Mr Meng speaking , Michelle . </s>","<s> Oh , hello ! Sorry about that . I 'm just calling to say that we 've received your new <unk>...",<s> What is the problem ? </s>,0,"! 'm 've , . <unk> Card I Oh Sorry about calling from hello just new received say that to we your",? What is problem the

alt.Chart(...)

Mean overlap on shown examples: 0.089  |  token accuracy: 37.820%  (1714/4532)  |  chance: 0.007%  |  lift: 37.813%

### How many weights, and how they look
Same Encoder / Decoder / Multi-Head Attention as the paper. These plots only **inspect** `named_parameters()`.

Total trainable weights: 37,121,266

alt.HConcatChart(...)

alt.HConcatChart(...)

,parameter,shape,n_weights,mean,std,l2,abs_max,part
90,generator.proj.weight,14578x512,7463936,-0.004674,0.07551154,206.6156,1.4182,generator
88,src_embed.0.lut.weight,14578x512,7463936,-0.00010472,0.02133973,58.279,0.21074742,embeddings + PE
89,tgt_embed.0.lut.weight,14578x512,7463936,-0.00042773,0.02350707,64.209,0.37994438,embeddings + PE
8,encoder.layers.0.feed_forward.w_1.weight,2048x512,1048576,0.00022415,0.0490574,50.2347,0.2621783,feed-forward
52,decoder.layers.0.feed_forward.w_2.weight,512x2048,1048576,0.00006185,0.05287613,54.1445,0.62224865,feed-forward
78,decoder.layers.1.feed_forward.w_2.weight,512x2048,1048576,0.00001894,0.05511209,56.4341,0.422133,feed-forward
50,decoder.layers.0.feed_forward.w_1.weight,2048x512,1048576,-0.00015106,0.0531638,54.4393,0.253631,feed-forward
76,decoder.layers.1.feed_forward.w_1.weight,2048x512,1048576,0.00015984,0.05386666,55.159,0.26673248,feed-forward
26,encoder.layers.1.feed_forward.w_2.weight,512x2048,1048576,0.00013246,0.03789252,38.8017,0.79360259,feed-forward
10,encoder.layers.0.feed_forward.w_2.weight,512x2048,1048576,0.00022743,0.05026075,51.4668,0.80639946,feed-forward
24,encoder.layers.1.feed_forward.w_1.weight,2048x512,1048576,0.00047631,0.03806359,38.9797,0.29437467,feed-forward
4,encoder.layers.0.self_attn.linears.2.weight,512x512,262144,0.00010407,0.06284201,32.175,0.26091,attention

Model ready. Checkpoints use prefix: dailydialog_local38k8e_
Preparing Data ...
Checking Model Outputs:

Example 0 ========

Input Utterance    : <s> Good morning , sir . Is there a bank near here ? </s>
Ground Truth Reply : <s> There is one . 5 blocks away from here ? </s>
Model Reply        : <s> Yes , I 'm looking for a new one . </s>

Example 1 ========

Input Utterance    : <s> There is one . 5 blocks away from here ? </s>
Ground Truth Reply : <s> Well , that 's too far . Can you change some money for me ? </s>
Model Reply        : <s> Yes , it is . </s>

Example 2 ========

Input Utterance    : <s> Well , that 's too far . Can you change some money for me ? </s>
Ground Truth Reply : <s> Surely , of course . What kind of currency have you got ? </s>
Model Reply        : <s> Yes , sir . </s>
Demo chat (non-interactive). This is a 2017 seq2seq reply model, not ChatGPT.
You: hello
Bot: Good morning , Mr. Smith .

You: how are you
Bot: I 'm glad you like it .

You: what are you doing today
Bot: I 'm going to be a good idea .

You: thanks a lot
Bot: What are you going to do now ?

Training/load done. Demo chat ran above. Run the last cell for Gradio chat.

# Chat (Gradio)

Run this cell **after** Part 3 has finished training or loading the model.

A chat box appears below. Use the **4 example buttons** or type your own sentence and press **Send**.
This is one-turn greedy decode from your paper Transformer, not ChatGPT.

If the box errors, re-run **this last cell only** after Part 3 finishes. Do not restart the kernel unless training is done.

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()
print("Opening Gradio chat. Type a sentence and press Send.")
launch_gradio_chat(model, vocab, spacy_en, max_padding=RUN_CONFIG["max_padding"])

Opening Gradio chat. Type a sentence and press Send.
Opening Gradio chat. This is one-turn seq2seq, not ChatGPT.
* Running on local URL:  http://127.0.0.1:7861
* To create a public link, set `share=True` in `launch()`.